const {chromium,expect}=require('@playwright/test');const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
(async()=>{const root=path.resolve('public');const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(404).end();return;}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});let deployPosts=0;await page.addInitScript(()=>localStorage.setItem('woori-account',JSON.stringify({access_token:'fixture'})));await page.route('**/api/admin/redeploy',r=>{if(r.request().method()==='POST'){deployPosts++;return r.fulfill({status:202,json:{state:'accepted'}});}return r.fulfill({json:{enabled:true}});});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/assets/account.js',route=>route.fulfill({contentType:'text/javascript',body:`
const content=document.getElementById('accountContent');content.hidden=false;document.getElementById('accountNotice').textContent='가상 데이터로 확인하는 관리자 화면';
const rows=[['서울 마포구 · 보장 점검','완료 확인 대기','테스트 설계사 A',''],['서울 강남구 · 보험금 청구','분쟁','테스트 설계사 B','확인 중: 일정 문의'],['인천 연수구 · 기존 보험 관리','완료','테스트 설계사 C','후기 5점 · 검토 대기']];
function render(){const list=document.getElementById('requestList');list.replaceChildren();for(const [i,row]of rows.entries()){if(document.querySelector('[name=state]').value==='awaiting_completion'&&i!==0)continue;const card=document.createElement('article');card.className='card booking-card';card.dataset.bookingId='fixture-'+i;card.innerHTML='<h2>'+row[0]+'</h2><p class="request-status">'+row[1]+'</p><p>'+row[2]+'</p><p>'+row[3]+'</p>'+(i===2?'<button>후기 검토 저장</button>':'');list.append(card);}}
document.getElementById('workflowFilters').onsubmit=e=>{e.preventDefault();render();};document.getElementById('refreshRequests').onclick=render;setTimeout(render,0);
`}));
await page.goto('http://127.0.0.1:'+server.address().port+'/admin-requests.html');await expect(page.locator('#adminCountAll')).toHaveText('3');await expect(page.locator('#adminCountWaiting')).toHaveText('1');await expect(page.locator('#adminCountIssues')).toHaveText('1');await expect(page.locator('#adminCountReviews')).toHaveText('1');
await page.locator('.admin-view-tabs [data-admin-view=issues]').click();await expect(page.locator('.booking-card:visible')).toHaveCount(1);await expect(page.locator('.booking-card:visible')).toContainText('강남구');
await page.locator('.admin-view-tabs [data-admin-view=reviews]').click();await expect(page.locator('.booking-card:visible')).toContainText('인천');
await page.locator('#adminListSearch').fill('없는 내용');await expect(page.locator('#adminEmptyView')).toBeVisible();await page.locator('#adminResetFilters').click();await expect(page.locator('.booking-card:visible')).toHaveCount(3);
await page.locator('[data-quick-state=awaiting_completion]').click();await expect(page.locator('.booking-card')).toHaveCount(1);await page.locator('#adminResetFilters').click();await expect(page.locator('.booking-card')).toHaveCount(3);
await expect(page.locator('#adminRedeploy')).toBeEnabled();page.once('dialog',d=>d.dismiss());await page.locator('#adminRedeploy').click();expect(deployPosts).toBe(0);page.once('dialog',d=>d.accept());await page.locator('#adminRedeploy').click();await expect(page.locator('#adminDeployStatus')).toContainText('접수');await expect(page.locator('#adminRedeploy')).toBeDisabled();expect(deployPosts).toBe(1);fs.mkdirSync('artifacts',{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/admin-console-desktop.png',fullPage:true});
await page.setViewportSize({width:360,height:800});await page.locator('#adminMenuToggle').click();await expect(page.locator('#adminSidebar')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.keyboard.press('Escape');await expect(page.locator('#adminSidebar')).toBeHidden();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/admin-console-mobile.png',fullPage:true});expect(errors).toEqual([]);console.log('PASS: admin dashboard counts, issue/review views, search/reset, state filters and 360px menu. Synthetic display data only; auth/backend not tested here.');
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
