import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {setupVisits} from './expert-visits-fixture.mjs';import {ids} from './commerce-fixture.mjs';
async function setup(){const f=await setupVisits();await f.db.exec('reset role');for(const n of ['052_optional_expert_profile.sql','053_connection_review.sql','054_profile_office_scope.sql','056_booking_hardening.sql','056_booking_hardening.sql'])await f.db.exec(await readFile('supabase/'+n,'utf8'));return f;}
const date=n=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date(Date.now()+n*86400000));
const payload=()=>({planner_id:ids.planner,purpose:'other',region:'경기 분당',method:'phone',preferred_at:date(2)+'T14:00:00+09:00',request_key:crypto.randomUUID()});
test('booking audit: canonical purposes, existing time, OFF, roster approval, synchronized display, private access and rollback',async()=>{const f=await setup();try{
 for(const [purpose,tags]of [['other',['critical']],['claim',['critical']],['claim',['surgery']],['management',['coverage']],['illness',['critical']],['medical',['surgery']]]){assert.equal((await f.db.query('select private.specialty_match($1,$2) ok',[purpose,tags])).rows[0].ok,true);}
 await f.db.exec("alter table auth.users add column if not exists email text;alter table auth.users add column if not exists email_confirmed_at timestamptz;update auth.users set email=id::text||'@fixture.test';");
 await f.db.query("insert into private.organization_roster(organization,email_hash,expires_at,created_by) select '확인 소속',encode(sha256(convert_to(lower(email),'UTF8')),'hex'),now()+interval '1 day',$1 from auth.users where id=$2",[ids.admin,ids.planner]);
 await f.db.exec("update auth.users set email_confirmed_at=now();");
 await f.db.query("update private.expert_profiles set specialties=array['critical','surgery'],start_hour=9,end_hour=18 where user_id=$1",[ids.planner]);
 let ep=(await f.db.query('select * from private.expert_profiles where user_id=$1',[ids.planner])).rows[0];assert.equal(ep.status,'APPROVED');assert.equal(ep.map_visible,true);
 await f.login(ids.customer);const cat=await f.rpc('planner_catalog',['','claim']);assert.ok(cat.planners.find(p=>p.id===ids.planner));assert.match(cat.planners.find(p=>p.id===ids.planner).hours,/09:00–18:00/);
 const r=await f.cmd('request',payload());
 await f.db.exec('reset role');const soon=new Date(Math.ceil((Date.now()+60000)/1800000)*1800000).toISOString();await f.db.query('update private.consultations set preferred_at=$1 where id=$2',[soon,r.id]);await f.db.query("update private.expert_profiles set weekdays=array[0],start_hour=1,end_hour=2 where user_id=$1",[ids.planner]);await f.db.query('update private.planner_directory set available=false where user_id=$1',[ids.planner]);
 await f.login(ids.planner);await f.cmd('accept',{id:r.id,revision:(await f.row(r.id,'partner')).revision});await f.login(ids.customer);await f.cmd('confirm',{id:r.id,revision:(await f.row(r.id)).revision,name:'확인 고객',share_consent:true});assert.equal((await f.row(r.id)).state,'scheduled');
 await assert.rejects(f.cmd('request',{...payload(),request_key:crypto.randomUUID()}),/invalid_partner|invalid_slot/);
 await f.db.exec('reset role');await f.db.query("update private.expert_profiles set weekdays=array[0,1,2,3,4,5,6],start_hour=0,end_hour=23 where user_id=$1",[ids.planner]);await f.db.query('update private.planner_directory set available=true where user_id=$1',[ids.planner]);
 await assert.rejects(f.db.query("select private.check_reservation_slot($1,null,$2,null,'phone')",[ids.planner,soon]),/invalid_slot/);
 await f.db.query("update private.consultations set preferred_at=now()-interval '1 minute' where id=$1",[r.id]);await assert.rejects(f.db.query("select private.check_reservation_slot(planner_id,office_id,preferred_at,id,method) from private.consultations where id=$1",[r.id]),/reservation_time_passed/);
 await f.db.exec('set role anon');await assert.rejects(f.db.query('select * from private.booking_hardening_snapshot'),/permission denied/);await f.db.exec('reset role');await f.db.exec(await readFile('supabase/rollback_booking_hardening.sql','utf8'));assert.equal((await f.db.query('select count(*) n from private.consultations')).rows[0].n,1);await f.db.exec(await readFile('supabase/056_booking_hardening.sql','utf8'));
 }finally{await f.db.close();}});
test('office confirmation keeps consent, duplicate slots fail, selected visits remain one recipient',async()=>{const f=await setup();try{
 await f.db.exec("insert into private.office_locations(id,name,region,status,address,latitude,longitude,weekdays) values('audit-office','확인 보험소','경기 분당','active','확인 사무실',37.3,127.1,array[0,1,2,3,4,5,6]);");await f.login(ids.customer);const r=await f.cmd('request',{...payload(),planner_id:null,office_id:'audit-office',office_assignment:true,method:'scheduled',preferred_at:date(2)+'T18:00:00+09:00'});
 await f.login(ids.admin);await f.cmd('office_assign',{id:r.id,revision:(await f.row(r.id,'admin')).revision,planner_id:ids.planner});await f.login(ids.planner);await f.cmd('accept',{id:r.id,revision:(await f.row(r.id,'partner')).revision});await f.login(ids.customer);await assert.rejects(f.cmd('confirm',{id:r.id,revision:(await f.row(r.id)).revision}),/consent_required/);await f.cmd('confirm',{id:r.id,revision:(await f.row(r.id)).revision,name:'확인 고객',share_consent:true});assert.equal((await f.row(r.id)).duration_minutes,60);
 await f.login(ids.other);await assert.rejects(f.cmd('request',{...payload(),planner_id:null,office_id:'audit-office',office_assignment:true,method:'scheduled',preferred_at:date(2)+'T18:00:00+09:00'}),/reservation_slot_taken/);
 const definition=(await f.db.query("select pg_get_functiondef('public.urgent_command(text,jsonb)'::regprocedure) code")).rows[0].code;assert.match(definition,/values\(r.id,target,1,/);
 }finally{await f.db.close();}});
