const {chromium,expect}=require(process.argv[2]||'@playwright/test');const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const {fixture,ids}=await import('./commerce-fixture.mjs');const f=await fixture();const root=path.resolve('public');let browser;let queue=Promise.resolve();const serial=fn=>{const next=queue.then(fn);queue=next.catch(()=>{});return next;};
 const server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/')pathname='/index.html';const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)){res.writeHead(404).end();return;}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const errors=[];const token=id=>{const exp=Math.floor(Date.now()/1000)+3600;return Buffer.from('{"alg":"HS256"}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:id,exp})).toString('base64url')+'.fixture';};
 const session=id=>({access_token:token(id),refresh_token:'fixture',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user:{id,email:Object.keys(ids).find(k=>ids[k]===id)+'@example.test',aud:'authenticated'}});
 async function pageFor(role,width){const page=await browser.newPage({viewport:{width,height:900}});page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/ads**',r=>r.fulfill({json:{enabled:false,ads:[]}}));
  await page.route('**/api/config',r=>r.fulfill({json:{enabled:true,url:'https://test.supabase.co',key:'sb_publishable_fixture',operator:'가상 운영자',contact:'test@example.test'}}));
  await page.route('https://test.supabase.co/**',route=>serial(async()=>{try{const req=route.request(),u=new URL(req.url()),body=req.postDataJSON()||{};const auth=req.headers().authorization?.replace('Bearer ','');let id;try{id=JSON.parse(Buffer.from(auth.split('.')[1],'base64url').toString()).sub;}catch{}
   if(u.pathname.includes('/auth/v1/token')){id=ids[String(body.email).split('@')[0]];if(!id)throw Error('test_login_only');await route.fulfill({json:session(id)});return;}
   if(u.pathname.includes('/auth/v1/user')){if(!id){await route.fulfill({status:401,json:{message:'not logged in'}});return;}await route.fulfill({json:session(id).user});return;}
   await f.login(id);const name=u.pathname.split('/').pop();
   let data;if(u.pathname.includes('/rpc/'))data=await f.rpc(name,Object.values(body));else if(name==='partner_applications'){const rows=(await f.db.query('select * from public.partner_applications')).rows;data=u.searchParams.has('user_id')?rows[0]||null:rows;}else throw Error('Unhandled '+u.pathname);
   await route.fulfill({json:data});
  }catch(e){await route.fulfill({status:400,json:{message:e.message}});}}));
  await page.route('**/api/payment',route=>serial(async()=>{try{const body=route.request().postDataJSON(),auth=route.request().headers().authorization.split(' ')[1],id=JSON.parse(Buffer.from(auth.split('.')[1],'base64url').toString()).sub;await f.login(id);let data;
   if(body.action==='checkout'){const order=await f.rpc('ad_checkout',[body.planId,body.slotId,body.requestKey,body.consent]);data={order,clientKey:'test_gck_fixture',successUrl:base+'/payment-result.html',failUrl:base+'/payment-result.html?failed=1',testOnly:true};}
   else if(body.action==='confirm'){const order=await f.rpc('ad_begin_confirm',[body.orderId,body.paymentKey,body.amount]);await f.login('','service_role');await f.rpc('ad_reconcile',[order.id,order.payment_key,order.amount,'DONE','https://dashboard.tosspayments.com/receipt','fixture-'+order.id]);data={status:'DONE'};}else if(body.action==='status'){const o=await f.rpc('ad_user_order',[body.orderId]);data={status:o.state};}else if(body.action==='refund'){const o=await f.rpc('ad_refund_request',[body.orderId,body.reason,body.platformFault]);await f.login('','service_role');await f.rpc('ad_reconcile',[o.id,o.payment_key,o.amount,'CANCELED',null,'fixture-refund']);data={status:'CANCELED'};}else throw Error('unhandled payment');await route.fulfill({json:data});
  }catch(e){await route.fulfill({status:400,json:{error:e.message}});}}));
  await page.addInitScript(()=>{window.TossPayments=()=>{let amt=0;return{widgets:()=>({setAmount:async a=>{amt=a.value;},renderPaymentMethods:async()=>{},renderAgreement:async()=>{},requestPayment:async options=>{if(!options.orderId||!amt)throw Error('invalid checkout');location.assign(options.successUrl+'?orderId='+options.orderId+'&paymentKey=fixture_'+options.orderId+'&amount='+amt);}})};};Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition:(_,reject)=>reject({code:1})},configurable:true});});
  await page.goto(base+'/login.html');await page.locator('[name=email]').fill(role+'@example.test');await page.locator('[name=password]').fill('fixture-password-1234');await page.locator('#loginForm button[type=submit],#loginForm button:not([type])').first().click();await page.waitForURL('**/account.html');await expect(page.locator('#membershipState')).toContainText('가입 완료');return page;
 }
 try{
  browser=await chromium.launch({channel:'msedge',headless:true});const c=await pageFor('customer',360),p=await pageFor('planner',1280),a=await pageFor('admin',1280);
  await c.goto(base+'/find.html');await expect(c.locator('.planner-card')).toHaveCount(2);await expect(c.locator('#plannerMap .leaflet-marker-icon')).toHaveCount(2);await c.locator('[name=location_consent]').check();await c.locator('#locatePlanners').click();await expect(c.locator('#directoryNotice')).toContainText('지역 선택');
  await c.getByRole('link',{name:'시간 약속하기',exact:true}).first().click();
  async function request(n){if(n)await c.goto(base+'/requests.html?planner='+ids.planner);await expect(c.locator('#requestForm')).toBeVisible();await c.locator('#requestForm [name=planner_id]').selectOption(ids.planner);const date=new Date(Date.now()+86400000).toISOString().slice(0,10);await c.locator('#requestForm [name=date]').fill(date);await c.locator('#requestForm [name=time]').fill(n?'15:00':'14:00');await expect(c.locator('#requestForm [name=automatic]')).toHaveCount(0);await c.getByRole('button',{name:'상담 요청 (무료)',exact:true}).click();await expect(c.locator('#accountMessage')).toHaveText('저장했습니다.');return serial(async()=>{await f.login(ids.customer);const rows=(await f.rpc('consultation_workspace',['customer'])).bookings;return rows[0].id;});}
  async function accept(id){await p.goto(base+'/partner-work.html');const card=p.locator('[data-booking-id="'+id+'"]');await expect(card).toBeVisible();await card.getByRole('button',{name:'상담 목적 확인·수락'}).click();await expect(card.locator('.request-status')).toHaveText('일정 조율');}
  async function confirmBooking(id){await c.reload();const card=c.locator('[data-booking-id="'+id+'"]');await card.locator('[name=name]').fill('가상 고객');await card.locator('[name=phone]').fill('01011112222');await card.locator('[name=share_consent]').check();await card.getByRole('button',{name:'동의하고 일정 확정'}).click();await expect(c.locator('#accountMessage')).toHaveText('저장했습니다.');}
  async function complete(id){await serial(async()=>{await f.db.exec('reset role');await f.db.query("update private.consultations set preferred_at=now()-interval '1 hour' where id=$1",[id]);});await p.goto(base+'/partner-work.html');await p.locator('[data-booking-id="'+id+'"]').getByRole('button',{name:'미팅 완료 확인 요청'}).click();await c.reload();await c.locator('[data-booking-id="'+id+'"]').getByRole('button',{name:'실제 미팅 완료 확인',exact:true}).click();await expect(c.locator('[data-booking-id="'+id+'"] .request-status')).toHaveText('완료');}
  await p.goto(base+'/partner-work.html');await expect(p.getByText('요금·기간·약정 노출수 확정 전')).toHaveCount(3);
  const free=await request(0);await accept(free);await confirmBooking(free);await expect(c.locator('[data-booking-id="'+free+'"] .request-status')).toHaveText('미팅 예정');await complete(free);
  await expect(c.locator('.payment-status')).toHaveCount(0);
  await a.goto(base+'/admin-requests.html');await a.getByText('구독 조건·노출 슬롯 설정',{exact:true}).click();
  await a.locator('#adPlanForm [name=amount]').fill('12000');await a.locator('#adPlanForm [name=period_days]').fill('30');await a.locator('#adPlanForm [name=guaranteed_impressions]').fill('100');await a.locator('#adPlanForm [name=reason]').fill('TEST ONLY browser fixture');await a.locator('#adPlanForm [name=enabled]').check();await a.getByRole('button',{name:'새 구독 조건 저장'}).click();await expect(a.locator('#accountMessage')).toHaveText('저장했습니다.');
  await a.getByText('구독 조건·노출 슬롯 설정',{exact:true}).click();await a.locator('#adSlotForm [name=region]').fill('서울 마포구');await a.locator('#adSlotForm [name=reason]').fill('TEST ONLY browser slot');await a.locator('#adSlotForm [name=enabled]').check();await a.getByRole('button',{name:'슬롯 저장',exact:true}).click();await expect(a.locator('#accountMessage')).toHaveText('저장했습니다.');
  await p.setViewportSize({width:360,height:900});await p.goto(base+'/partner-work.html');await p.locator('[data-plan-code=basic] [name=consent]').check();await p.getByRole('button',{name:'광고 구독 테스트 결제',exact:true}).click();await expect(p.getByRole('dialog')).toBeVisible();
  if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('payment mobile overflow');
  await p.getByRole('button',{name:'닫기',exact:true}).click();await expect(p.getByRole('dialog')).toHaveCount(0);
  await p.getByRole('button',{name:'이 주문 결제 계속하기'}).click();await p.getByRole('button',{name:'결제하기',exact:true}).click();await p.waitForURL('**/payment-result.html*');await expect(p.locator('#accountMessage')).toContainText('테스트 결제 승인을 확인');
  await p.goto(base+'/partner-work.html');await expect(p.locator('.ad-status')).toHaveText('이용 중');
  const second=await request(1);await accept(second);await confirmBooking(second);await complete(second);
  await p.goto(base+'/partner-work.html');await expect(p.locator('.ad-status')).toHaveCount(1);await expect(p.locator('.ad-status')).toHaveText('이용 중');
  await serial(async()=>{await f.db.exec('reset role');await f.db.exec("update private.ad_subscriptions set starts_at=now()-interval '31 days',ends_at=now()-interval '1 day'");});
  await a.goto(base+'/admin-requests.html');await a.locator('[name=platform_fault]').check();await a.locator('#adSubscriptions [name=reason]').last().fill('TEST verified exposure shortfall');await a.getByRole('button',{name:'광고 구독 테스트 전액 환불'}).click();await expect(a.locator('.ad-status')).toHaveText('환불 완료');
  const declined=await request(2);await p.goto(base+'/partner-work.html');await p.locator('[data-booking-id="'+declined+'"]').getByRole('button',{name:'이번 상담 패스'}).click();await c.reload();
  const after=await serial(async()=>{await f.login(ids.customer);return await f.row(declined);});if(after.planner_id!==null||after.state!=='unmatched')throw Error('Declined request was reassigned');
  await expect(c.getByRole('button',{name:'다음 후보 찾기'})).toHaveCount(0);
  const q=await pageFor('next',360);await q.goto(base+'/partner-work.html');await expect(q.locator('[data-booking-id="'+declined+'"]')).toHaveCount(0);
  c.once('dialog',d=>d.accept());await c.locator('[data-booking-id="'+declined+'"]').getByRole('button',{name:'예약 취소',exact:true}).click();await expect(c.locator('[data-booking-id="'+declined+'"] .request-status')).toHaveText('취소');

  const applicant=await pageFor('other',360);await applicant.goto(base+'/partner.html');
  const applicationForm=applicant.locator('#partnerForm');await expect(applicationForm).toBeVisible();
  for(const [name,value] of Object.entries({full_name:'가상 신규 전문가',organization:'테스트 회사',region:'서울 마포구',credential_reference:'TEST-EXPERT',credential_issuer:'테스트 확인 기관',business_contact:'01000000000',career_years:'4'}))await applicationForm.locator('[name='+name+']').fill(value);
  await applicationForm.locator('[name=consultation_modes][value=remote]').check();await applicationForm.locator('[name=verification_consent]').check();
  await applicationForm.getByRole('button',{name:'전문가 심사 신청',exact:true}).click();await expect(applicant.locator('#partnerState')).toHaveText('심사 대기');
  await a.goto(base+'/admin.html');const applicationCard=a.locator('#applications .card').filter({hasText:'가상 신규 전문가'});await applicationCard.locator('textarea').fill('등록 정보 추가 확인 필요');await applicationCard.getByRole('button',{name:'반려',exact:true}).click();await expect(a.locator('#accountMessage')).toHaveText('심사 결과를 저장했습니다.');
  await applicant.reload();await expect(applicant.locator('#partnerState')).toHaveText('보완 후 재신청');await applicationForm.locator('[name=credential_reference]').fill('TEST-UPDATED');await applicationForm.locator('[name=verification_consent]').check();await applicationForm.getByRole('button',{name:'보완 후 재신청',exact:true}).click();await expect(applicant.locator('#partnerState')).toHaveText('심사 대기');
  await applicant.getByRole('button',{name:'신청 철회',exact:true}).click();await expect(applicant.locator('#partnerState')).toHaveText('신청 철회');
  if(await applicant.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('expert signup mobile overflow');
  fs.mkdirSync('artifacts',{recursive:true});await applicant.screenshot({path:'artifacts/expert-onboarding.png',fullPage:true});
  await c.goto(base+'/admin-requests.html');await expect(c.locator('#accountContent')).toBeHidden();
  await c.goto(base+'/find.html');if(await c.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('mobile overflow');
  fs.mkdirSync('artifacts',{recursive:true});await c.screenshot({path:'artifacts/mobile-directory.png',fullPage:true});await p.screenshot({path:'artifacts/planner-payments.png',fullPage:true});
  if(errors.length)throw Error(errors.join('\n'));console.log('PASS: mobile + desktop login, directory, denied location, direct request, free consultations, independent prepaid advertising, widget close/resume, exposure refund, customer completion, unauthorized admin denied. PGlite DB; PG/auth simulated; no external payment/email.');
 }finally{if(browser)await browser.close();server.close();await queue;await f.db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
