const {chromium,expect}=require(process.argv[2]||'@playwright/test');const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const {fixture,ids}=await import('./commerce-fixture.mjs');const f=await fixture();const root=path.resolve('public');let browser;let queue=Promise.resolve();const serial=fn=>{const next=queue.then(fn);queue=next.catch(()=>{});return next;};
 const server=http.createServer((req,res)=>{let pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/')pathname='/index.html';const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)){res.writeHead(404).end();return;}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const errors=[];const token=id=>{const exp=Math.floor(Date.now()/1000)+3600;return Buffer.from('{"alg":"HS256"}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:id,exp})).toString('base64url')+'.fixture';};
 const session=id=>({access_token:token(id),refresh_token:'fixture',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user:{id,email:Object.keys(ids).find(k=>ids[k]===id)+'@example.test',aud:'authenticated'}});
 async function pageFor(role,width){const page=await browser.newPage({viewport:{width,height:900}});page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/config',r=>r.fulfill({json:{enabled:true,url:'https://test.supabase.co',key:'sb_publishable_fixture',operator:'가상 운영자',contact:'test@example.test'}}));
  await page.route('https://test.supabase.co/**',route=>serial(async()=>{try{const req=route.request(),u=new URL(req.url()),body=req.postDataJSON()||{};const auth=req.headers().authorization?.replace('Bearer ','');let id;try{id=JSON.parse(Buffer.from(auth.split('.')[1],'base64url').toString()).sub;}catch{}
   if(u.pathname.includes('/auth/v1/token')){id=ids[String(body.email).split('@')[0]];if(!id)throw Error('test_login_only');await route.fulfill({json:session(id)});return;}
   if(u.pathname.includes('/auth/v1/user')){if(!id){await route.fulfill({status:401,json:{message:'not logged in'}});return;}await route.fulfill({json:session(id).user});return;}
   await f.login(id);const name=u.pathname.split('/').pop();
   let data;if(u.pathname.includes('/rpc/'))data=await f.rpc(name,Object.values(body));else if(name==='partner_applications'){const rows=(await f.db.query('select * from public.partner_applications')).rows;data=u.searchParams.has('user_id')?rows[0]||null:rows;}else throw Error('Unhandled '+u.pathname);
   await route.fulfill({json:data});
  }catch(e){await route.fulfill({status:400,json:{message:e.message}});}}));
  await page.route('**/api/payment',route=>serial(async()=>{try{const body=route.request().postDataJSON(),auth=route.request().headers().authorization.split(' ')[1],id=JSON.parse(Buffer.from(auth.split('.')[1],'base64url').toString()).sub;await f.login(id);let data;
   if(body.action==='checkout'){const order=await f.rpc('connection_checkout',[body.bookingId,body.stage]);data={order,clientKey:'test_ck_fixture',successUrl:base+'/payment-result.html',failUrl:base+'/payment-result.html?failed=1',testOnly:true};}
   else if(body.action==='confirm'){const order=await f.rpc('connection_begin_confirm',[body.orderId,body.paymentKey,body.amount]);await f.login('','service_role');await f.rpc('connection_reconcile',[order.id,order.payment_key,order.amount,'DONE','https://dashboard.tosspayments.com/receipt','fixture-'+order.id]);data={status:'DONE'};}else throw Error('unhandled payment');await route.fulfill({json:data});
  }catch(e){await route.fulfill({status:400,json:{error:e.message}});}}));
  await page.addInitScript(()=>{window.TossPayments=()=>{let amt=0;return{widgets:()=>({setAmount:async a=>{amt=a.value;},renderPaymentMethods:async()=>{},renderAgreement:async()=>{},requestPayment:async options=>{if(!options.orderId||!amt)throw Error('invalid checkout');location.assign(options.successUrl+'?orderId='+options.orderId+'&paymentKey=fixture_'+options.orderId+'&amount='+amt);}})};};Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition:(_,reject)=>reject({code:1})},configurable:true});});
  await page.goto(base+'/login.html');await page.locator('[name=email]').fill(role+'@example.test');await page.locator('[name=password]').fill('fixture-password-1234');await page.locator('#loginForm button[type=submit],#loginForm button:not([type])').first().click();await page.waitForURL('**/account.html');await expect(page.locator('#membershipState')).toContainText('가입 완료');return page;
 }
 try{
  browser=await chromium.launch({channel:'msedge',headless:true});const c=await pageFor('customer',390),p=await pageFor('planner',1280),a=await pageFor('admin',1280);
  await c.goto(base+'/find.html');await expect(c.locator('.planner-card')).toHaveCount(2);await expect(c.locator('#plannerMap .leaflet-marker-icon')).toHaveCount(2);await c.locator('[name=location_consent]').check();await c.locator('#locatePlanners').click();await expect(c.locator('#directoryNotice')).toContainText('지역 선택');
  await c.getByRole('link',{name:'시간 약속하기',exact:true}).first().click();
  async function request(n,automatic=false){if(n)await c.goto(base+'/requests.html?planner='+ids.planner);await expect(c.locator('#requestForm')).toBeVisible();await c.locator('#requestForm [name=planner_id]').selectOption(ids.planner);const date=new Date(Date.now()+86400000).toISOString().slice(0,10);await c.locator('#requestForm [name=date]').fill(date);await c.locator('#requestForm [name=time]').fill(n?'15:00':'14:00');if(automatic)await c.locator('#requestForm [name=automatic]').check();await c.getByRole('button',{name:'상담 요청 (무료)',exact:true}).click();await expect(c.locator('#accountMessage')).toHaveText('저장했습니다.');return serial(async()=>{await f.login(ids.customer);const rows=(await f.rpc('consultation_workspace',['customer'])).bookings;return rows[0].id;});}
  async function accept(id,paid){await p.goto(base+'/partner-work.html');const card=p.locator('[data-booking-id="'+id+'"]');await expect(card).toBeVisible();if(paid)await card.locator('[name=paid_consent]').check();await card.getByRole('button',{name:'상담 목적 확인·수락'}).click();await expect(card.locator('.request-status')).toHaveText('일정 조율');}
  async function confirmBooking(id){await c.reload();const card=c.locator('[data-booking-id="'+id+'"]');await card.locator('[name=name]').fill('가상 고객');await card.locator('[name=phone]').fill('01011112222');await card.locator('[name=share_consent]').check();await card.getByRole('button',{name:'동의하고 일정 확정'}).click();await expect(c.locator('#accountMessage')).toHaveText('저장했습니다.');}
  async function complete(id){await serial(async()=>{await f.db.exec('reset role');await f.db.query("update private.consultations set preferred_at=now()-interval '1 hour' where id=$1",[id]);});await p.goto(base+'/partner-work.html');await p.locator('[data-booking-id="'+id+'"]').getByRole('button',{name:'미팅 완료 확인 요청'}).click();await c.reload();await c.locator('[data-booking-id="'+id+'"]').getByRole('button',{name:'실제 미팅 완료 확인',exact:true}).click();await expect(c.locator('[data-booking-id="'+id+'"] .request-status')).toHaveText('완료');}
  const free=await request(0);await accept(free,false);await confirmBooking(free);await expect(c.locator('[data-booking-id="'+free+'"] .payment-status')).toContainText('무료');await complete(free);
  await a.goto(base+'/admin-requests.html');await a.locator('[name=free_meetings]').fill('0');await a.locator('#workflowSummary [name=reason]').fill('유료 테스트 시나리오');await a.getByRole('button',{name:'신규 정책 저장'}).click();await expect(a.locator('#accountMessage')).toHaveText('저장했습니다.');
  const paid=await request(1);await accept(paid,true);await confirmBooking(paid);
  await p.goto(base+'/partner-work.html');await p.locator('[data-booking-id="'+paid+'"]').getByRole('button',{name:'1차 35,000원 테스트 결제 (카드·간편결제)'}).click();await p.getByRole('button',{name:'결제하기',exact:true}).click();await p.waitForURL('**/payment-result.html*');await expect(p.locator('#accountMessage')).toContainText('테스트 결제 승인을 확인');
  await complete(paid);await p.goto(base+'/partner-work.html');await p.locator('[data-booking-id="'+paid+'"]').getByRole('button',{name:'2차 35,000원 테스트 결제 (카드·간편결제)'}).click();await p.getByRole('button',{name:'결제하기',exact:true}).click();await p.waitForURL('**/payment-result.html*');await expect(p.locator('#accountMessage')).toContainText('테스트 결제 승인을 확인');
  await p.goto(base+'/partner-work.html');await expect(p.locator('[data-booking-id="'+paid+'"] .payment-status')).toContainText('전액 완료');
  const auto=await request(2,true);const offered=await serial(async()=>{await f.login(ids.customer);return (await f.row(auto)).planner_id;});const q=await pageFor(offered===ids.planner?'planner':'next',390);await q.goto(base+'/partner-work.html');await q.locator('[data-booking-id="'+auto+'"]').getByRole('button',{name:'이번 상담 패스'}).click();await c.reload();const after=await serial(async()=>{await f.login(ids.customer);return await f.row(auto);});if(!after.planner_id||after.planner_id===offered)throw Error('Next candidate not offered');c.once('dialog',d=>d.accept());await c.locator('[data-booking-id="'+auto+'"]').getByRole('button',{name:'예약 취소',exact:true}).click();await expect(c.locator('[data-booking-id="'+auto+'"] .request-status')).toHaveText('취소');
  await c.goto(base+'/admin-requests.html');await expect(c.locator('#accountContent')).toBeHidden();
  await c.goto(base+'/find.html');if(await c.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('mobile overflow');
  fs.mkdirSync('artifacts',{recursive:true});await c.screenshot({path:'artifacts/mobile-directory.png',fullPage:true});await p.screenshot({path:'artifacts/planner-payments.png',fullPage:true});
  if(errors.length)throw Error(errors.join('\n'));console.log('PASS: mobile + desktop login, directory, denied location, direct request, free meeting, paid consent, two separate mock card orders, customer completion, paid ledger, unauthorized admin denied. PGlite DB; PG/auth simulated; no external payment/email.');
 }finally{if(browser)await browser.close();server.close();await queue;await f.db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
