import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {setupVisits} from './expert-visits-fixture.mjs';import {ids} from './commerce-fixture.mjs';
async function setup(){const f=await setupVisits();await f.db.exec('reset role');await f.db.exec(await readFile('supabase/052_optional_expert_profile.sql','utf8'));const sql=await readFile('supabase/053_connection_review.sql','utf8');await f.db.exec(sql);await f.db.exec(sql);return f;}
const date=n=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date(Date.now()+n*86400000));
const payload=(target=ids.planner,n=2)=>({planner_id:target,office_assignment:false,purpose:'claim',region:'경기 분당',method:'phone',preferred_at:date(n)+'T14:00:00+09:00',request_key:crypto.randomUUID()});
test('direct recipient, replay conflict, refresh duplicates, OFF and actual office identity',async()=>{const f=await setup();try{
 await f.login(ids.customer);const p=payload(),r=await f.cmd('request',p);assert.equal((await f.row(r.id)).planner_id,ids.planner);assert.equal((await f.cmd('request',p)).id,r.id);assert.equal((await f.cmd('request',{...p,request_key:crypto.randomUUID()})).id,r.id);
 await assert.rejects(f.cmd('request',{...p,planner_id:ids.next}),/request_key_conflict/);await assert.rejects(f.cmd('request',{...payload(),planner_id:null,office_assignment:true}),/select_planner/);await assert.rejects(f.cmd('request',{...payload(),office_assignment:true}),/select_planner/);
 await f.db.exec('reset role');await f.db.query('update private.planner_directory set available=false where user_id=$1',[ids.next]);await f.login(ids.customer);await assert.rejects(f.cmd('request',payload(ids.next,3)),/invalid_partner/);
 await f.login(ids.other);assert.deepEqual((await f.rpc('consultation_workspace',['customer'])).bookings,[]);await assert.rejects(f.cmd('cancel',{id:r.id,revision:1}),/request_forbidden/);await assert.rejects(f.db.query('select * from private.consultation_schedule_proposals'),/permission denied/);
 await f.db.exec("reset role;insert into private.office_locations(id,name,region,status,address,latitude,longitude,weekdays) values('review-office','확인 보험소','경기 분당','active','확인 사무실',37.3,127.1,array[0,1,2,3,4,5,6]);");
 await f.login(ids.customer);const office={...payload(null,4),office_id:'review-office',office_assignment:true,method:'scheduled',preferred_at:date(4)+'T18:00:00+09:00'};const booked=await f.cmd('request',office),row=await f.row(booked.id);assert.equal(row.office_name,'확인 보험소');assert.equal(row.duration_minutes,60);assert.equal(row.planner_id,null);assert.equal(row.state,'requested');await assert.rejects(f.cmd('request',{...office,method:'phone'}),/invalid_method/);await assert.rejects(f.cmd('request',{...office,planner_id:ids.planner}),/select_planner/);
 await f.login(ids.other);await assert.rejects(f.cmd('request',{...office,request_key:crypto.randomUUID()}),/slot_unavailable/);
 await f.login(ids.customer);await f.cmd('cancel',{id:r.id,revision:(await f.row(r.id)).revision});assert.equal((await f.row(r.id)).state,'cancelled');await assert.rejects(f.cmd('request',p),/request_closed/);
 await f.db.exec('reset role;set role anon');await assert.rejects(f.cmd('request',payload()),/permission denied/);
 }finally{await f.db.close();}});
test('proposal preserves confirmed time until other party accepts, rejects stale/unauthorized/overlapping changes, safe rollback',async()=>{const f=await setup();try{
 await f.login(ids.customer);const p=payload(),r=await f.cmd('request',p);await f.login(ids.planner);await f.cmd('accept',{id:r.id,revision:(await f.row(r.id,'partner')).revision});await f.login(ids.customer);await f.cmd('confirm',{id:r.id,revision:(await f.row(r.id)).revision,name:'확인 고객',share_consent:true});let row=await f.row(r.id);assert.equal(row.state,'scheduled');const original=row.preferred_at;
 const next=date(3)+'T15:00:00+09:00';await f.cmd('propose',{id:r.id,revision:row.revision,preferred_at:next});row=await f.row(r.id);assert.equal(row.preferred_at,original);assert.equal(row.state,'scheduled');assert.equal(row.schedule_proposal.mine,true);assert.equal(row.schedule_proposal.can_accept,false);await assert.rejects(f.cmd('schedule_accept',{id:r.id,revision:row.revision}),/request_forbidden/);
 await f.db.exec('reset role');await assert.rejects(f.db.exec(await readFile('supabase/rollback_connection_review.sql','utf8')),/pending_schedule_changes_require_resolution/);await f.db.exec('rollback');
 await f.login(ids.next);await assert.rejects(f.cmd('schedule_accept',{id:r.id,revision:row.revision}),/request_forbidden/);await f.login(ids.planner);row=await f.row(r.id,'partner');assert.equal(row.schedule_proposal.can_accept,true);await assert.rejects(f.cmd('schedule_accept',{id:r.id,revision:row.revision-1}),/stale_request/);await f.cmd('schedule_decline',{id:r.id,revision:row.revision});row=await f.row(r.id,'partner');assert.equal(row.preferred_at,original);assert.equal(row.schedule_proposal,null);
 await f.cmd('propose',{id:r.id,revision:row.revision,preferred_at:next});await f.login(ids.customer);row=await f.row(r.id);await f.cmd('schedule_accept',{id:r.id,revision:row.revision});row=await f.row(r.id);assert.equal(Date.parse(row.preferred_at),Date.parse(next));assert.equal(row.state,'scheduled');assert.equal(row.schedule_proposal,null);
 await f.cmd('propose',{id:r.id,revision:row.revision,preferred_at:date(4)+'T15:00:00+09:00'});await f.db.exec('reset role');await f.db.query("insert into private.consultations(customer_id,planner_id,purpose,region,method,preferred_at,state,request_key,duration_minutes) values($1,$2,'claim','경기 분당','phone',$3,'scheduled',$4,60)",[ids.other,ids.planner,date(4)+'T15:00:00+09:00',crypto.randomUUID()]);await f.login(ids.planner);row=await f.row(r.id,'partner');await assert.rejects(f.cmd('schedule_accept',{id:r.id,revision:row.revision}),/slot_unavailable/);assert.equal(Date.parse((await f.row(r.id,'partner')).preferred_at),Date.parse(next));
 await f.login(ids.customer);await f.cmd('cancel',{id:r.id,revision:(await f.row(r.id)).revision});assert.equal((await f.row(r.id)).schedule_proposal,null);await f.db.exec('reset role');const count=(await f.db.query('select count(*) n from private.consultations')).rows[0].n;await f.db.exec(await readFile('supabase/rollback_connection_review.sql','utf8'));assert.equal((await f.db.query('select count(*) n from private.consultations')).rows[0].n,count);await f.db.exec(await readFile('supabase/053_connection_review.sql','utf8'));
 }finally{await f.db.close();}});
