import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {setupContact} from './contact-flow-fixture.mjs';import {ids} from './commerce-fixture.mjs';
const visit=()=>({area:'경기 분당',planner_id:ids.planner,request_key:crypto.randomUUID(),purpose:'claim',meeting_kind:'address',place:'격리 검증 장소',note:'상담 일정 문의',preferred_at:new Date(Date.now()+3600000).toISOString(),consent:true});
const day=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date(Date.now()+2*86400000));
const booking=()=>({planner_id:ids.planner,request_key:crypto.randomUUID(),purpose:'claim',region:'경기 분당',method:'phone',preferred_at:day()+'T10:00:00+09:00'});
test('contact first: both participants consent, verified number only, both contact acknowledgements, cancellation hides contacts and notifications are private',async()=>{const f=await setupContact();try{
 await f.login(ids.customer);const p=booking(),r=await f.cmd('request',p);await f.login(ids.planner);let row=await f.row(r.id,'partner');await f.cmd('accept',{id:r.id,revision:row.revision});
 await f.login(ids.customer);row=await f.row(r.id);const args={id:r.id,revision:row.revision};assert.equal(row.contactFlow,2);assert.equal(row.exchange.phone,null);assert.equal(row.contact,undefined);
 await assert.rejects(f.cmd('confirm',{...args,name:'검증 고객',confirmed:true,share_consent:true}),/contact_first_required/);
 await assert.rejects(f.cmd('share_contact',{...args,consent:false}),/contact_consent_required/);
 await f.cmd('share_contact',{...args,consent:true,phone:'01099999999'});await f.cmd('share_contact',{...args,consent:true});assert.equal((await f.row(r.id)).exchange.phone,null);
 await f.login(ids.planner);await f.cmd('share_contact',{...args,consent:true});row=await f.row(r.id,'partner');assert.equal(row.exchange.phone,'01000000001');await f.cmd('contacted',{...args,confirmed:true});
 await f.login(ids.customer);assert.equal((await f.row(r.id)).exchange.ready,false);await f.cmd('contacted',{...args,confirmed:true});assert.equal((await f.row(r.id)).exchange.ready,true);await f.cmd('confirm',{...args,name:'검증 고객',confirmed:true});row=await f.row(r.id);assert.equal(row.state,'scheduled');assert.ok(row.exchange.phone);
 const inbox=await f.rpc('notification_inbox');assert.ok(inbox.items.some(n=>n.title==='예약이 확정됐어요.'));assert.ok(!JSON.stringify(inbox).includes('01000000001'));await f.rpc('notification_inbox',['read',inbox.items[0].id]);
 await f.cmd('cancel',{id:r.id,revision:row.revision});assert.equal((await f.row(r.id)).exchange.phone,null);
 await f.login(ids.planner);assert.ok((await f.rpc('notification_inbox')).items.some(n=>n.title==='예약이 취소됐어요.'));assert.equal((await f.row(r.id,'partner')).exchange.phone,null);
 await f.login(ids.other);assert.equal((await f.rpc('notification_inbox')).items.length,0);await f.rpc('notification_inbox',['read',inbox.items[1].id]);await assert.rejects(f.cmd('share_contact',{...args,consent:true}),/request_forbidden/);await assert.rejects(f.db.query('select * from private.contact_permissions'),/permission denied/);
 await f.db.exec('reset role');assert.equal((await f.db.query('select count(*)::int n from private.contact_permissions')).rows[0].n,2);await assert.rejects(f.db.exec('update private.contact_permissions set version=version'),/append_only_consent/);
 }finally{await f.db.close();}});
test('availability: owner-only expert switch, admin-only office switch, OFF blocks new requests/slots but preserves pending booking',async()=>{const f=await setupContact();try{
 await f.db.exec("insert into private.office_locations(id,name,region,status,address,latitude,longitude,weekdays) values('flow-office','검증 보험소','경기 분당','active','검증 장소',37.38,127.12,array[0,1,2,3,4,5,6])");
 await f.login(ids.customer);const r=await f.cmd('request',booking());await assert.rejects(f.rpc('consultation_availability',['expert',{enabled:false}]),/expert_verification_required/);await assert.rejects(f.rpc('consultation_availability',['office',{office_id:'flow-office',enabled:false}]),/admin_required/);
 await f.login(ids.planner);await f.rpc('consultation_availability',['expert',{enabled:false}]);assert.equal((await f.rpc('consultation_availability')).expertEnabled,false);assert.equal((await f.urgent('settings')).instant.enabled,false);let row=await f.row(r.id,'partner');await f.cmd('accept',{id:r.id,revision:row.revision});assert.equal((await f.row(r.id,'partner')).state,'coordinating');
 await f.login(ids.other);await assert.rejects(f.cmd('request',{...booking(),preferred_at:day()+'T13:00:00+09:00'}),/reception_paused/);assert.deepEqual(await f.rpc('reservation_slots',[null,ids.planner,day(),'phone']),[]);
 await f.login(ids.admin);await f.rpc('consultation_availability',['office',{office_id:'flow-office',enabled:false}]);
 await f.login(null,'anon');assert.equal((await f.rpc('office_catalog')).find(o=>o.id==='flow-office').bookingEnabled,false);assert.deepEqual(await f.rpc('reservation_slots',['flow-office',null,day(),'scheduled']),[]);await assert.rejects(f.rpc('consultation_availability'),/permission denied/);
 await f.login(ids.admin);await f.rpc('consultation_availability',['office',{office_id:'flow-office',enabled:true}]);assert.ok((await f.rpc('reservation_slots',['flow-office',null,day(),'scheduled'])).includes('18:00'));
 await f.db.exec('reset role');assert.equal((await f.db.query('select count(*)::int n from private.contact_flow_backup')).rows[0].n,1);
 }finally{await f.db.close();}});
test('visit flow: OFF after request retains acceptance, reciprocal phone consent before address, confirm alerts both, trip and expiry hide sensitive fields',async()=>{const f=await setupContact();try{
 await f.login(ids.customer);const r=await f.urgent('request',visit());await f.login(ids.planner);await f.rpc('consultation_availability',['expert',{enabled:false}]);await f.urgent('accept',{id:r.id});let rows=await f.urgent('workspace');assert.equal(rows[0].details,null);await f.urgent('share_contact',{id:r.id,consent:true});
 await f.login(ids.customer);await f.urgent('share_contact',{id:r.id,consent:true});await f.urgent('contacted',{id:r.id,confirmed:true});await assert.rejects(f.urgent('confirm_visit',{id:r.id,consent:true}),/contact_first_required/);
 await f.login(ids.planner);await f.urgent('contacted',{id:r.id,confirmed:true});assert.equal((await f.urgent('workspace'))[0].details,null);
 await f.login(ids.customer);await f.urgent('confirm_visit',{id:r.id,consent:true});await f.urgent('confirm_visit',{id:r.id,consent:true});assert.equal((await f.rpc('notification_inbox')).items.filter(n=>n.title==='방문 일정이 확정됐어요.').length,1);
 await f.login(ids.planner);rows=await f.urgent('workspace');assert.equal(rows[0].details.place,'격리 검증 장소');assert.equal(rows[0].details.phone,undefined);assert.equal(rows[0].exchange.phone,'01000000001');for(const state of ['DEPARTED','ARRIVED','COMPLETED'])await f.urgent('trip',{id:r.id,state});assert.equal((await f.urgent('workspace'))[0].details,null);assert.equal((await f.urgent('workspace'))[0].exchange.phone,null);
 await f.login(ids.customer);const titles=(await f.rpc('notification_inbox')).items.map(n=>n.title);for(const title of ['방문상담 요청이 접수됐어요.','방문 일정이 확정됐어요.','전문가가 출발했어요.','전문가가 도착했어요.','상담이 완료됐어요.'])assert.ok(titles.includes(title));
 }finally{await f.db.close();}});
test('changed schedules require fresh contact confirmation and changed verified phone requires renewed disclosure consent',async()=>{const f=await setupContact();try{
 await f.login(ids.customer);const r=await f.cmd('request',booking());await f.login(ids.planner);let row=await f.row(r.id,'partner');await f.cmd('accept',{id:r.id,revision:row.revision});row=await f.row(r.id,'partner');let args={id:r.id,revision:row.revision};await f.cmd('share_contact',{...args,consent:true});await f.login(ids.customer);await f.cmd('share_contact',{...args,consent:true});await f.cmd('contacted',{...args,confirmed:true});await f.login(ids.planner);await f.cmd('contacted',{...args,confirmed:true});
 await f.cmd('propose',{...args,preferred_at:day()+'T11:00:00+09:00'});row=await f.row(r.id,'partner');await f.cmd('accept',{id:r.id,revision:row.revision});row=await f.row(r.id,'partner');assert.equal(row.exchange.myContacted,false);assert.equal(row.exchange.otherContacted,false);
 await f.db.exec('reset role');await f.db.query("update auth.users set phone='+821011111111' where id=$1",[ids.customer]);await f.login(ids.planner);assert.equal((await f.row(r.id,'partner')).exchange.phone,null);await f.login(ids.customer);assert.equal((await f.row(r.id)).exchange.myConsent,false);
 }finally{await f.db.close();}});
test('office assignment uses the same consent flow; rollback preserves evidence and refuses a privacy downgrade',async()=>{const f=await setupContact();try{
 await f.db.exec("insert into private.office_locations(id,name,region,status,address,latitude,longitude,weekdays) values('consent-office','검증 보험소','경기 분당','active','격리 장소',37.38,127.12,array[0,1,2,3,4,5,6])");
 await f.login(ids.customer);const r=await f.cmd('request',{...booking(),planner_id:null,office_id:'consent-office',office_assignment:true,method:'scheduled',preferred_at:day()+'T18:00:00+09:00'});let row=await f.row(r.id);assert.equal(row.duration_minutes,60);assert.equal(row.exchange,null);
 await f.login(ids.admin);await f.cmd('office_assign',{id:r.id,revision:row.revision,planner_id:ids.planner});
 await f.login(ids.planner);row=await f.row(r.id,'partner');await f.cmd('accept',{id:r.id,revision:row.revision});row=await f.row(r.id,'partner');const args={id:r.id,revision:row.revision};await f.cmd('share_contact',{...args,consent:true});
 await f.login(ids.customer);await f.cmd('share_contact',{...args,consent:true});await f.cmd('contacted',{...args,confirmed:true});await f.login(ids.planner);await f.cmd('contacted',{...args,confirmed:true});
 await f.login(ids.customer);await f.cmd('office_confirm',{...args,name:'격리 고객',confirmed:true});assert.equal((await f.row(r.id)).state,'scheduled');
 await f.login(ids.admin);row=await f.row(r.id,'admin');assert.equal(row.exchange,null);assert.equal(row.contact,undefined);assert.equal(row.planner_phone,undefined);
 await f.db.exec('reset role');await assert.rejects(f.db.exec(await readFile('supabase/rollback_contact_first.sql','utf8')),/contact_flow_records_exist/);await f.db.exec('rollback');assert.equal((await f.db.query('select count(*)::int n from private.contact_permissions')).rows[0].n,2);
 }finally{await f.db.close();}});
test('empty migration rollback restores the original function and expiration alerts both without disclosure',async()=>{const f=await setupContact();try{
 await f.db.exec(await readFile('supabase/rollback_contact_first.sql','utf8'));assert.equal((await f.db.query("select position('contact_first_required' in pg_get_functiondef('public.consultation_command(text,jsonb)'::regprocedure))::int n")).rows[0].n,0);
 // Reapply preserves the original backup and restores the access grant.
 await f.db.exec(await readFile('supabase/049_contact_first.sql','utf8'));await f.login(ids.customer);const r=await f.urgent('request',visit());await f.db.exec('reset role');await f.db.query("update private.urgent_requests set expires_at=now()-interval '1 second' where id=$1",[r.id]);await f.login(ids.customer);const row=(await f.urgent('workspace'))[0];assert.equal(row.state,'EXPIRED');assert.equal(row.exchange,null);assert.ok((await f.rpc('notification_inbox')).items.some(n=>n.title==='요청이 종료됐어요.'));
 await f.login(ids.planner);assert.ok((await f.rpc('notification_inbox')).items.some(n=>n.title==='요청이 종료됐어요.'));
 }finally{await f.db.close();}});
