import test from 'node:test';import assert from 'node:assert/strict';import handler from '../netlify/functions/expert-documents.mts';
test('Document endpoint is disabled by default, validates origin/auth, stores privately and gates download',async()=>{
 const env={APP_ORIGIN:'http://localhost:3190',SUPABASE_URL:'https://fake.example.test',SUPABASE_SERVICE_ROLE_KEY:'fake-test-only',EXPERT_DOCUMENTS_ENABLED:'false'};globalThis.Netlify={env:{get:k=>env[k]}};
 const native=globalThis.fetch,seen=[];let denied=false;const doc={id:'doc',object_path:'user/private.pdf',mime:'application/pdf',filename:'test.pdf'};
 globalThis.fetch=async(input,init={})=>{const url=String(input);seen.push(url);if(url.includes('/auth/v1/user'))return Response.json({id:'user',aud:'authenticated'});if(url.includes('/rest/v1/rpc/expert_document_service')){const body=JSON.parse(init.body);if(denied)return Response.json({message:'request_forbidden',code:'P0001'},{status:400});return Response.json(body.operation==='save'?{document:doc,previous_path:null}:doc);}if(url.includes('/storage/v1/object/'))return init.method==='POST'?Response.json({Key:'private'}):new Response('%PDF-1.7 fake',{headers:{'content-type':'application/pdf'}});throw Error('Unexpected network '+url);};
 const json=(origin='http://localhost:3190',auth=true)=>new Request('http://localhost:3190/api/expert-documents',{method:'POST',headers:{Origin:origin,...auth?{Authorization:'Bearer fake-token'}:{},'Content-Type':'application/json'},body:JSON.stringify({action:'read',id:'doc'})});
 try{assert.equal((await handler(json())).status,503);assert.equal(seen.length,0);env.EXPERT_DOCUMENTS_ENABLED='true';assert.equal((await handler(json('https://wrong.test'))).status,403);assert.equal((await handler(json(undefined,false))).status,401);
  const read=await handler(json());assert.equal(read.status,200);assert.equal(read.headers.get('cache-control'),'no-store');assert.match(read.headers.get('content-disposition'),/attachment/);assert.equal(await read.text(),'%PDF-1.7 fake');
  denied=true;const before=seen.filter(u=>u.includes('/storage/')).length;assert.equal((await handler(json())).status,400);assert.equal(seen.filter(u=>u.includes('/storage/')).length,before);denied=false;
  const form=new FormData();form.set('file',new File(['<script>not pdf</script>'],'fake.pdf',{type:'application/pdf'}));form.set('kind','identity');form.set('profession','planner');form.set('redacted','true');form.set('consent','true');const req=new Request('http://localhost:3190/api/expert-documents',{method:'POST',headers:{Origin:env.APP_ORIGIN,Authorization:'Bearer fake-token'},body:form});assert.equal((await handler(req)).status,400);assert.equal(seen.filter(u=>u.includes('/storage/')).length,before);
  form.set('file',new File(['%PDF-1.7 fake test document'],'test.pdf',{type:'application/pdf'}));const upload=await handler(new Request('http://localhost:3190/api/expert-documents',{method:'POST',headers:{Origin:env.APP_ORIGIN,Authorization:'Bearer fake-token'},body:form}));assert.equal(upload.status,200);assert.equal((await upload.json()).id,'doc');
 }finally{globalThis.fetch=native;delete globalThis.Netlify;}
});
