import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {fixture,ids} from './commerce-fixture.mjs';import {documentType,safeFilename} from '../netlify/functions/_shared/expert-documents.mjs';import {validRegistration,koreanPhone,AGREEMENT_VERSION} from '../src/expert-shared.js';import {sortedProfiles} from '../src/consultation-ui.js';
const application={profession:'planner',full_name:'가상 신청자',phone:'+821000000000',region:'서울 마포구',organization:'가상 소속',registration_number:'TEST-123',agreement_version:AGREEMENT_VERSION,agreements:[true,true,true],document_consent:true};
async function setup(){const f=await fixture();await f.db.exec('reset role;alter table auth.users add column phone text,add column phone_confirmed_at timestamptz;');await f.db.exec(await readFile('supabase/011_expert_onboarding.sql','utf8'));return f;}
async function documents(f,id,profession='planner'){await f.login(id,'service_role');for(const kind of ['identity','qualification'])await f.rpc('expert_document_service',[id,'save',{kind,profession,path:id+'/'+kind+'.pdf',filename:kind+'.pdf',mime:'application/pdf',bytes:100}]);await f.db.exec('reset role');await f.db.query('update auth.users set phone=$1,phone_confirmed_at=now() where id=$2',[application.phone,id]);await f.login(id);}
test('New onboarding enforces phone, private documents, consent and stale revisions',async()=>{const f=await setup();try{
 await f.login(ids.customer);await assert.rejects(()=>f.rpc('expert_submit',[application,0]),/phone_verification_required/);
 await documents(f,ids.customer);await assert.rejects(()=>f.rpc('expert_submit',[{...application,agreements:[true,false,true]},0]),/consent_required/);await assert.rejects(()=>f.rpc('expert_submit',[{...application,profession:'lawyer'},0]),/documents_required/);
 await f.rpc('expert_submit',[application,0]);const w=await f.rpc('expert_workspace');assert.equal(w.application.status,'pending');assert.equal(w.application.agreement_version,AGREEMENT_VERSION);assert.ok(w.application.agreed_at);assert.ok(!('object_path' in w.documents[0]));await assert.rejects(()=>f.rpc('expert_submit',[application,0]),/stale_application/);
 await assert.rejects(()=>f.db.query('select * from private.expert_documents'));await assert.rejects(()=>f.rpc('expert_document_service',[ids.customer,'read',{id:w.documents[0].id}]));
 await assert.rejects(()=>f.rpc('submit_partner_application',[{},0]),/permission denied/);
 await f.login(ids.other);assert.equal((await f.rpc('expert_workspace')).application,null);await assert.rejects(()=>f.rpc('expert_admin_list'),/admin_required/);
 await f.login(ids.other,'service_role');await assert.rejects(()=>f.rpc('expert_document_service',[ids.other,'read',{id:w.documents[0].id}]),/request_forbidden/);
 await f.login(ids.admin);await assert.rejects(()=>f.rpc('expert_review',[ids.customer,'approved','가상 자료 확인 근거',1,{}]),/verification_required/);await f.rpc('expert_review',[ids.customer,'needs_changes','서류를 보완해 주세요',1,{}]);
 await f.login(ids.customer);await f.rpc('expert_submit',[application,2]);await f.login(ids.admin);await f.rpc('expert_review',[ids.customer,'approved','가상 자료 확인 테스트',3,{identity:true,qualification:true,registry:true}]);assert.equal((await f.rpc('expert_admin_list'))[0].status,'approved');
 }finally{await f.db.close();}});
test('Sanctions withdraw badge, block exposure and cannot be downgraded via warning',async()=>{const f=await setup();try{
 await documents(f,ids.planner);await f.rpc('expert_submit',[application,0]);await f.login(ids.admin);await f.rpc('expert_review',[ids.planner,'approved','테스트 자료 세 가지 확인',1,{identity:true,qualification:true,registry:true}]);
 assert.ok((await f.rpc('planner_catalog',['',''])).planners.find(p=>p.id===ids.planner).protection_pledge);
 await f.rpc('expert_review',[ids.planner,'warning','소비자 신고 확인 경고',2,{}]);assert.equal((await f.rpc('planner_catalog',['',''])).planners.find(p=>p.id===ids.planner).protection_pledge,null);
 await f.rpc('expert_review',[ids.planner,'suspended','반복 신고로 기간 정지',3,{},new Date(Date.now()+86400000).toISOString()]);assert.ok(!(await f.rpc('planner_catalog',['',''])).planners.some(p=>p.id===ids.planner));
 await assert.rejects(()=>f.rpc('expert_review',[ids.planner,'warning','정지 우회 불가능 확인',4,{}]),/invalid_transition/);
 await f.rpc('expert_review',[ids.planner,'banned','계속된 위반으로 제명',4,{}]);await f.login(ids.planner);await assert.rejects(()=>f.rpc('expert_submit',[application,5]),/application_locked/);
 }finally{await f.db.close();}});
test('Deletion reservation prevents concurrent approval and preserves retry metadata',async()=>{const f=await setup();try{
 await documents(f,ids.customer);await f.rpc('expert_submit',[application,0]);const d=(await f.rpc('expert_workspace')).documents[0];await f.login(ids.customer,'service_role');const reserved=await f.rpc('expert_document_service',[ids.customer,'delete',{id:d.id}]);await f.login(ids.admin);await assert.rejects(()=>f.rpc('expert_review',[ids.customer,'approved','삭제 중 승인 방지 확인',2,{identity:true,qualification:true,registry:true}]),/verification_required/);
 await f.login(ids.customer,'service_role');await f.rpc('expert_document_service',[ids.customer,'confirm_delete',{id:d.id,path:reserved.object_path}]);await f.login(ids.customer);assert.equal((await f.rpc('expert_workspace')).documents.length,1);
 }finally{await f.db.close();}});
test('Document bytes and registration formats reject spoofed and sensitive input',()=>{assert.equal(documentType(new Uint8Array([37,80,68,70,45,49,46,55])),'application/pdf');assert.throws(()=>documentType(new Uint8Array([60,115,99,114,105,112,116,62])));assert.equal(validRegistration('900101-1234567'),false);assert.equal(validRegistration('TEST-123'),true);assert.equal(koreanPhone('010-1234-5678'),'+821012345678');assert.ok(!safeFilename('../x<script>.pdf').includes('/'));});
test('Directory ordering ignores pledge and documents, uses distance rating specialty',()=>{const profiles=[{id:'a',name:'A',rating:3,specialties:['claim'],protection_pledge:true},{id:'b',name:'B',rating:5,specialties:['other']},{id:'c',name:'C',rating:5,specialties:['claim']}];assert.deepEqual(sortedProfiles(profiles,null,'claim').map(p=>p.id),['c','b','a']);});

test('All professions and self-review are enforced, old applications stay visible',async()=>{const f=await setup();try{
 await documents(f,ids.customer,'lawyer');await f.rpc('expert_submit',[{...application,profession:'lawyer'},0]);await f.login(ids.admin);await assert.rejects(()=>f.rpc('expert_review',[ids.admin,'approved','본인 승인 시도 테스트',0,{}]),/self_review_forbidden/);await f.rpc('expert_review',[ids.customer,'approved','가상 변호사 등록 확인 테스트',1,{identity:true,qualification:true,registry:true}]);
 const rows=await f.rpc('expert_admin_list');assert.ok(rows.some(r=>r.legacy&&r.user_id===ids.planner));const card=(await f.rpc('planner_catalog',['','claim'])).planners.find(r=>r.id===ids.customer);assert.equal(card.profession,'lawyer');assert.equal(card.is_sample,true);assert.ok(card.protection_pledge);assert.ok(!JSON.stringify(card).includes('TEST-123'));
 await f.rpc('expert_review',[ids.customer,'warning','가상 신고 경고 테스트',2,{}]);await f.rpc('expert_review',[ids.customer,'suspended','가상 노출 정지 테스트',3,{},new Date(Date.now()+86400000).toISOString()]);assert.ok(!(await f.rpc('planner_catalog',['',''])).planners.some(r=>r.id===ids.customer));
 }finally{await f.db.close();}});

test('Storage restriction overrides broad existing authenticated policies',async()=>{const f=await fixture();try{
 await f.db.exec("reset role;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id integer,bucket_id text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant all on storage.objects to authenticated;create policy overly_broad on storage.objects for all to authenticated using(true) with check(true);insert into storage.objects values(1,'expert-documents'),(2,'other');");await f.db.exec(await readFile('supabase/expert_storage_setup.sql','utf8'));await f.login(ids.customer);assert.deepEqual((await f.db.query('select id from storage.objects')).rows,[{id:2}]);await assert.rejects(()=>f.db.query("insert into storage.objects values(3,'expert-documents')"));
 }finally{await f.db.close();}});
