import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {setupUrgent} from './urgent-fixture.mjs';import {ids} from './commerce-fixture.mjs';
import {setupVisits as setup} from './expert-visits-fixture.mjs';
const payload=()=>({request_key:crypto.randomUUID(),planner_id:ids.planner,area:'경기 분당',latitude:37.383,longitude:127.119,purpose:'claim',meeting_kind:'address',place:'격리 테스트 실제 방문주소',phone:'01000000000',note:'비공개 상담내용',preferred_at:new Date(Date.now()+3600000).toISOString(),consent:true});
test('single expert request, separate search location, acceptance then customer confirmation, privacy and strict ownership',async()=>{const f=await setup();try{
 await f.login(ids.customer);const p=payload();const r=await f.urgent('request',p);assert.equal((await f.urgent('request',p)).id,r.id);await assert.rejects(f.urgent('request',{...p,planner_id:ids.next}),/request_key_conflict/);
 await f.db.exec('reset role');assert.equal((await f.db.query('select count(*)::int n from private.urgent_offers where request_id=$1',[r.id])).rows[0].n,1);const raw=(await f.db.query('select latitude,longitude,place from private.urgent_requests where id=$1',[r.id])).rows[0];assert.equal(raw.latitude,null);assert.equal(raw.longitude,null);assert.equal(raw.place,p.place);
 await f.login(ids.next);assert.deepEqual(await f.urgent('workspace'),[]);await assert.rejects(f.urgent('accept',{id:r.id}),/offer_unavailable/);
 await f.login(ids.planner);let w=await f.urgent('workspace');assert.equal(w[0].details,null);assert.ok(!JSON.stringify(w).includes(p.note));await f.urgent('accept',{id:r.id});assert.equal((await f.urgent('workspace'))[0].details,null);await assert.rejects(f.urgent('trip',{id:r.id,state:'DEPARTED'}),/customer_confirmation_required/);await assert.rejects(f.urgent('confirm_visit',{id:r.id,consent:true}),/request_forbidden/);
 await f.login(ids.customer);assert.equal((await f.urgent('workspace'))[0].state,'ACCEPTED');await assert.rejects(f.urgent('confirm_visit',{id:r.id,consent:false}),/contact_consent_required/);await f.urgent('confirm_visit',{id:r.id,consent:true});await f.urgent('confirm_visit',{id:r.id,consent:true});
 await f.login(ids.planner);w=await f.urgent('workspace');assert.equal(w[0].details.place,p.place);assert.equal(w[0].confirmed,true);assert.equal(w[0].timeline.filter(x=>x.state==='CONFIRMED').length,1);await f.urgent('stop');assert.equal((await f.urgent('workspace'))[0].confirmed,true);for(const state of ['DEPARTED','ARRIVED','COMPLETED'])await f.urgent('trip',{id:r.id,state});
 await f.login(ids.other);assert.deepEqual(await f.urgent('workspace'),[]);await assert.rejects(f.urgent('cancel',{id:r.id}),/request_forbidden/);await assert.rejects(f.db.query('select * from private.instant_availability'),/permission denied/);
 }finally{await f.db.close();}});
test('public server-distance catalog, freshness, default OFF, consent, manual refresh does not extend expiry, rejection',async()=>{const f=await setup();try{
 await f.db.query('update private.instant_availability set latitude=37.5 where user_id=$1',[ids.next]);await f.login(null,'anon');const q={area:'경기 분당',latitude:37.383,longitude:127.119};let rows=await f.rpc('visit_catalog',[q]);assert.equal(rows[0].id,ids.planner);assert.ok(!JSON.stringify(rows).match(/latitude|longitude|accuracy|phone|consent_at/));assert.equal(rows[0].registrationVerified,true);assert.equal(rows[0].organizationVerified,false);await assert.rejects(f.urgent('settings'),/permission denied/);
 await f.db.exec("reset role;update private.instant_availability set updated_at=now()-interval '11 minutes'");await f.login(null,'anon');assert.ok((await f.rpc('visit_catalog',[q])).every(x=>x.stale));await f.db.exec("reset role;update private.instant_availability set updated_at=now()-interval '30 minutes'");await f.login(null,'anon');assert.deepEqual(await f.rpc('visit_catalog',[q]),[]);
 await f.login(ids.planner);const expiry=(await f.urgent('settings')).instant.expires_at;await f.urgent('refresh_location',{latitude:37.383,longitude:127.119,accuracy:30});assert.equal((await f.urgent('settings')).instant.expires_at,expiry);await f.urgent('stop');await assert.rejects(f.urgent('refresh_location',{latitude:37.383,longitude:127.119,accuracy:30}),/availability_expired/);await assert.rejects(f.urgent('start',{duration:240,latitude:37.383,longitude:127.119,accuracy:30}),/location_consent_required/);await assert.rejects(f.urgent('start',{consent:true,latitude:37.383,longitude:127.119,accuracy:9999}),/invalid_location/);await f.urgent('start',{consent:true,latitude:37.383,longitude:127.119,accuracy:30});assert.ok(new Date((await f.urgent('settings')).instant.expires_at)-Date.now()>239*60000);
 await f.login(ids.customer);assert.equal((await f.urgent('settings')).instant,null);const r=await f.urgent('request',payload());await f.login(ids.planner);await f.urgent('pass',{id:r.id});await f.login(ids.customer);assert.equal((await f.urgent('workspace'))[0].rejected,true);
 }finally{await f.db.close();}});
test('branch booking stays 60 minutes with 18:00 start; planned and duplicate reservations remain blocked',async()=>{const f=await setup();try{
 await f.db.exec("insert into private.office_locations(id,name,region,status,address,latitude,longitude,weekdays) values('visit-test-office','격리 테스트 보험소','경기 분당','active','격리 테스트 주소',37.38,127.12,array[0,1,2,3,4,5,6]),('visit-planned','격리 예정 보험소','경기 분당','planned',null,null,null,array[0,1,2,3,4,5,6]);");
 const day=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date(Date.now()+2*86400000));await f.login(ids.customer);const slots=await f.rpc('reservation_slots',['visit-test-office',null,day]);assert.ok(slots.includes('18:00'));const p={purpose:'claim',region:'경기 분당',method:'scheduled',preferred_at:day+'T18:00:00+09:00',request_key:crypto.randomUUID(),office_id:'visit-test-office',office_assignment:true};const r=await f.cmd('request',p);await f.db.exec('reset role');assert.equal((await f.db.query('select duration_minutes from private.consultations where id=$1',[r.id])).rows[0].duration_minutes,60);await f.login(ids.other);await assert.rejects(f.cmd('request',{...p,request_key:crypto.randomUUID()}),/slot_unavailable/);await assert.rejects(f.cmd('request',{...p,office_id:'visit-planned',request_key:crypto.randomUUID()}),/office_not_active/);
 }finally{await f.db.close();}});
test('expert visit overlaps are blocked against existing bookings; rollback preserves data and refuses unsafe privacy downgrade',async()=>{const f=await setup();try{
 await f.login(ids.customer);const p=payload(),r=await f.urgent('request',p);await f.db.exec('reset role');
 await f.db.query("insert into private.consultations(customer_id,planner_id,purpose,region,method,preferred_at,state,request_key,duration_minutes) values($1,$2,'claim','경기 분당','scheduled',$3,'scheduled',$4,60)",[ids.other,ids.planner,p.preferred_at,crypto.randomUUID()]);
 await f.login(ids.planner);await assert.rejects(f.urgent('accept',{id:r.id}),/slot_unavailable/);
 await f.db.exec("reset role;update private.consultations set state='cancelled'");await f.login(ids.planner);await f.urgent('accept',{id:r.id});
 await f.db.exec('reset role');const members=(await f.db.query('select * from public.member_profiles order by user_id')).rows;
 await assert.rejects(f.db.exec(await readFile('supabase/rollback_expert_visits.sql','utf8')),/visit_requests_exist_keep_privacy_wrapper_and_fix_forward/);await f.db.exec('rollback');assert.deepEqual((await f.db.query('select * from public.member_profiles order by user_id')).rows,members);
 assert.equal((await f.db.query('select count(*)::int n from private.expert_visit_migration_backup')).rows[0].n,1);
 }finally{await f.db.close();}});
