import {chromium,expect} from '@playwright/test';import {startExpertPreview} from '../scripts/expert-preview.mjs';
const server=await startExpertPreview(0);let browser;const errors=[];
try{browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:360,height:800}});page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port;
 for(const profession of ['설계사','손해사정사','변호사']){
  await page.goto(base,{waitUntil:'domcontentloaded'});await expect(page.locator('#expertNext')).toBeDisabled();await page.getByRole('button',{name:profession,exact:false}).click();if(profession==='설계사')await page.screenshot({path:'artifacts/expert-step1-mobile.png',fullPage:true});await page.locator('#expertNext').click();
  await page.getByLabel('이름',{exact:true}).fill('가상 신청자');await page.getByLabel('휴대폰',{exact:true}).fill('01000000000');await expect(page.locator('#expertNext')).toBeDisabled();
  if(profession==='설계사'){await page.evaluate(()=>window.expertDemo.smsFailure=true);await page.getByRole('button',{name:'인증번호 받기'}).click();await expect(page.getByRole('alert').filter({hasText:'문자를 보내지 못했습니다'})).toBeVisible();await page.evaluate(()=>window.expertDemo.smsFailure=false);}
  await page.getByRole('button',{name:'인증번호 받기'}).click();await page.getByLabel('인증번호',{exact:true}).fill('123456');await page.getByRole('button',{name:'인증번호 확인'}).click();await expect(page.locator('#expertNext')).toBeEnabled();await page.locator('#expertNext').click();await page.getByLabel('활동 지역').fill('서울 마포구');await page.getByLabel('소속 회사').fill('테스트 소속');await page.locator('#expertNext').click();await expect(page.locator('#expertNext')).toBeDisabled();
  await page.getByLabel('불필요한 개인정보를 가린').check();await page.getByLabel('자격 심사를 위한 비공개').check();
  const files=page.locator('input[type=file]:not([capture])');for(let i=0;i<2;i++){const file=profession==='설계사'&&i===0?{name:'가상서류.png',mimeType:'image/png',buffer:Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=128;c.height=80;c.getContext('2d').fillText('SAMPLE ONLY',10,40);return c.toDataURL().split(',')[1];}),'base64')}:{name:'가상서류.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 fictional test document')};await files.nth(i).setInputFiles(file);await expect(page.locator('.document-complete')).toHaveCount(i+1);if(profession==='설계사'&&i===0)await expect(page.locator('.document-thumbnail')).toBeVisible();}
  await page.locator('[name=registration_number]').fill('900101-1234567');await expect(page.locator('#expertNext')).toBeDisabled();await page.locator('[name=registration_number]').fill('TEST-123');await expect(page.locator('#expertNext')).toBeEnabled();
  if(profession==='설계사'){await page.screenshot({path:'artifacts/expert-documents-mobile.png',fullPage:true});await page.getByRole('button',{name:'신분증 (불필요한 정보 가림) 삭제',exact:true}).click();await expect(page.locator('#expertNext')).toBeDisabled();await files.nth(0).setInputFiles({name:'가상서류.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 test')});await expect(page.locator('#expertNext')).toBeEnabled();}
  await page.locator('#expertNext').click();await expect(page.locator('#expertNext')).toBeDisabled();await page.getByLabel('소비자보호 서약 전체 동의').check();await expect(page.locator('#expertNext')).toBeEnabled();await page.getByLabel('플랫폼 외부로').uncheck();await expect(page.locator('#expertNext')).toBeDisabled();await page.getByLabel('플랫폼 외부로').check();
  if(profession==='설계사')await page.screenshot({path:'artifacts/expert-pledge-mobile.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile overflow');await page.locator('#expertNext').click();await expect(page.getByRole('heading',{name:'심사 신청 완료, 검토 후 안내드립니다'})).toBeVisible();
 }
 await page.goto(base+'/?view=admin');await page.getByText('서류·신고·심사 상세 보기').click();await expect(page.getByText('가상 신고:',{exact:false})).toBeVisible();await page.getByRole('button',{name:'승인',exact:true}).click();await expect(page.getByRole('status')).toContainText('5자');await page.getByLabel('심사·제재 사유').fill('가상 자료 확인 테스트');await page.getByRole('button',{name:'승인',exact:true}).click();await expect(page.getByRole('status')).toContainText('모두 완료');for(const box of await page.locator('input[type=checkbox]').all())await box.check();
 await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'artifacts/expert-admin-desktop.png',fullPage:true});await page.getByRole('button',{name:'승인',exact:true}).click();await expect(page.getByText('심사 결과와 담당자·시각을 기록했습니다.')).toBeVisible();
 await page.goto(base+'/?view=badge');await page.getByRole('button',{name:'소비자보호 서약'}).click();await expect(page.locator('dialog li')).toHaveCount(3);await page.getByRole('button',{name:'닫기'}).click();await expect(page.locator('dialog')).toHaveCount(0);
 if(errors.length)throw Error(errors.join('\n'));console.log('PASS: all professions, mobile, SMS failure, documents/delete, pledge, admin, badge. Local mocks only.');
}finally{await browser?.close();await new Promise(r=>server.close(r));}
