import {chromium,expect} from '@playwright/test';import {startProPreview} from '../scripts/pro-preview.mjs';
const {server}=await startProPreview(0);let browser;const errors=[];
try{browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:360,height:850}});const planner=await context.newPage();planner.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port;await planner.goto(base+'/pro');await planner.getByLabel('상담에서 병원서류').check();await planner.locator('#customer').selectOption('sample-a');await planner.locator('#hospital').selectOption('sample-hospital-a');await planner.getByLabel('진료비 영수증',{exact:true}).check();await planner.getByText('위임장·동의서 후속 작업',{exact:true}).click();await planner.locator('#mandate').selectOption('required');await planner.locator('#consent').selectOption('required');await planner.getByRole('button',{name:'고객에게 서류 준비 요청'}).click();await expect(planner.getByText('가상 링크를 준비했습니다.',{exact:false})).toBeVisible();const link=await planner.getByRole('link',{name:'고객 화면 열기 (가상)'}).getAttribute('href');
 const customer=await context.newPage();customer.on('pageerror',e=>errors.push(e.message));let uploaded=0;customer.on('request',r=>{if(r.url().endsWith('/api/customer/copy'))uploaded++;});await customer.goto(link);await expect(customer.locator('#hospitalName')).toHaveText('가상 ○○병원');await expect(customer.locator('input[type=text],select,textarea')).toHaveCount(0);await customer.getByRole('button',{name:'가상 신분증으로 체험'}).click();await expect(customer.locator('#maskCanvas')).toBeVisible();await expect(customer.locator('#complete')).toBeDisabled();if(uploaded!==0)throw Error('Original image unexpectedly uploaded');
 const masked=await customer.locator('#maskCanvas').evaluate(c=>Array.from(c.getContext('2d').getImageData(30,300,1,1).data));if(masked.join(',')!=='0,0,0,255')throw Error('Mask not opaque');await customer.getByLabel('가림 결과를 확인했습니다').check();await customer.screenshot({path:'artifacts/pro-customer-mask-mobile.png',fullPage:true});await customer.locator('#complete').click();await expect(customer.locator('#done')).toBeVisible();await expect(planner.locator('.pro-status')).toContainText('신분증 사본 준비 (고객 확인)');await expect(planner.getByText('위임장: ⚠ 자필서명 필요',{exact:true})).toBeVisible();await expect(planner.getByText('동의서: ⚠ 자필서명 필요',{exact:true})).toBeVisible();if(uploaded!==1)throw Error('Unexpected upload count');
 for(const page of [planner,customer])if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');await planner.screenshot({path:'artifacts/pro-planner-mobile.png',fullPage:true});await planner.setViewportSize({width:1280,height:900});await planner.screenshot({path:'artifacts/pro-planner-desktop.png',fullPage:true});
 const imageUrl=await planner.getByRole('link',{name:'보호처리한 가상 사본 내려받기'}).getAttribute('href');const image=await context.request.get(base+imageUrl);if(image.status()!==200||image.headers()['cache-control']!=='no-store')throw Error('Private image response');const outsider=await browser.newContext();if((await outsider.request.get(base+imageUrl)).status()!==401)throw Error('Anonymous image access');await outsider.request.get(base+'/pro');if((await outsider.request.get(base+imageUrl)).status()!==404)throw Error('Other owner image access');await outsider.close();
 await planner.getByRole('button',{name:'가상 사본 삭제'}).click();await expect(planner.locator('.pro-status')).toContainText('삭제');await planner.getByRole('button',{name:'링크 다시 만들기'}).click();const expired=await context.newPage();await expired.goto(link);await expect(expired.locator('#customerMessage')).toContainText('유효하지 않은 링크');await expect(expired.locator('#customerPanel')).toBeHidden();await expired.close();await planner.getByRole('button',{name:'요청 취소',exact:true}).click();await expect(planner.locator('.pro-status')).toHaveText('요청 취소');
 if(errors.length)throw Error(errors.join('\n'));console.log('PASS PRO: masking before upload, real-time owner update, signatures independent, minimal customer fields, private copy/delete, token rotation, cancellation, mobile/desktop. Local synthetic data only.');
}finally{await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
