import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {setupUrgent} from './urgent-fixture.mjs';import {ids} from './commerce-fixture.mjs';
import {normalizePhone,maskPhone,otpHash,createPhoneHandler,phoneEnabled} from '../netlify/functions/_shared/phone-otp.mjs';
const number='+821000000001',hash='a'.repeat(64),bad='b'.repeat(64),ip='c'.repeat(64);
async function setup(){const f=await setupUrgent(false);await f.db.exec('reset role');for(const name of ['026_release_controls.sql','027_private_rls.sql','030_public_early_access.sql','031_expert_early_access.sql','032_expert_verification.sql','033_reservation_integrity.sql','034_organization_roster.sql','035_operational_metrics.sql','036_member_rights_admin.sql','037_solapi_phone_otp.sql','037_solapi_phone_otp.sql'])await f.db.exec(await readFile('supabase/'+name,'utf8'));f.otp=async(operation,payload={},user=ids.customer)=>{await f.login(null,'service_role');return f.rpc('phone_otp_service',[user,operation,payload]);};f.reserve=()=>f.otp('reserve',{phone:number,hash,ip_hash:ip});f.age=async seconds=>{await f.db.exec('reset role');await f.db.query("update private.phone_otp_challenges set created_at=created_at-$1*interval '1 second'",[seconds]);};return f;}
test('OTP DB: transaction rerun, 30-second resend, three/10min, old invalidation, consume, contact/auth separation, RLS',async()=>{const f=await setup();try{
 const first=await f.reserve();assert.ok(first.id);await f.otp('sent',{id:first.id});assert.equal((await f.reserve()).error,'otp_cooldown');await f.age(20);assert.equal((await f.reserve()).error,'otp_cooldown');await f.age(11);
 const second=await f.otp('reserve',{phone:number,hash:bad,ip_hash:ip});await f.otp('sent',{id:second.id});assert.equal((await f.otp('verify',{phone:number,hash})).error,'invalid_otp');assert.equal((await f.otp('verify',{phone:number,hash:bad})).verified,true);assert.equal((await f.otp('verify',{phone:number,hash:bad})).error,'otp_expired');
 await f.login(ids.customer);assert.equal((await f.rpc('my_phone_status')).verified,true);assert.equal((await f.rpc('release_status')).phoneVerified,true);await assert.rejects(f.rpc('phone_otp_service',[ids.customer,'status',{}]),/permission denied/);await assert.rejects(f.db.exec('select * from private.phone_otp_challenges'),/permission denied/);await assert.rejects(f.db.exec('select * from private.phone_contacts'),/permission denied/);
 await f.login(ids.other);assert.equal((await f.rpc('my_phone_status')).verified,false);await f.db.exec('reset role');assert.equal((await f.db.query('select phone from auth.users where id=$1',[ids.customer])).rows[0].phone,null);assert.equal((await f.db.query('select count(*)::int n from private.phone_otp_challenges where otp_hash is not null')).rows[0].n,0);
 await f.age(31);const third=await f.reserve();assert.ok(third.id);await f.age(31);assert.equal((await f.reserve()).error,'otp_rate_limit');
 await f.login(null,'anon');await assert.rejects(f.rpc('my_phone_status'),/permission denied/);
 }finally{await f.db.close();}});
test('OTP DB: five bad attempts lock sixth; exact expiry; failed delivery not verifiable; phone change requires verification',async()=>{const f=await setup();try{
 const r=await f.reserve();await f.otp('sent',{id:r.id});for(let i=0;i<5;i++)assert.equal((await f.otp('verify',{phone:number,hash:bad})).error,i===4?'otp_locked':'invalid_otp');assert.equal((await f.otp('verify',{phone:number,hash})).error,'otp_locked');await f.age(601);
 const expired=await f.reserve();await f.otp('sent',{id:expired.id});await f.db.exec("reset role;update private.phone_otp_challenges set expires_at=clock_timestamp()-interval '1 second'");assert.equal((await f.otp('verify',{phone:number,hash})).error,'otp_expired');await f.age(601);
 const unsent=await f.reserve();assert.equal((await f.otp('verify',{phone:number,hash})).error,'sms_unavailable');await f.otp('cancel',{id:unsent.id});assert.equal((await f.otp('verify',{phone:number,hash})).error,'otp_expired');await f.age(601);
 const good=await f.reserve();await f.otp('sent',{id:good.id});await f.otp('verify',{phone:number,hash});await f.age(31);await f.otp('reserve',{phone:'+821000000002',hash,ip_hash:ip});assert.equal((await f.otp('status')).verified,false);
 }finally{await f.db.close();}});
test('SOLAPI server: strict production off; allowlist; login; provider failure; HMAC-only stored; no OTP/key in response',async()=>{
 const values={CONTEXT:'deploy-preview',PHONE_VERIFICATION_ENABLED:'false',PHONE_VERIFICATION_MODE:'test',SMS_PROVIDER:'solapi',APP_ORIGIN:'https://preview.invalid',SUPABASE_URL:'https://db.invalid',SUPABASE_SERVICE_ROLE_KEY:'test-server',SOLAPI_API_KEY:'test-key',SOLAPI_API_SECRET:'test-secret',SOLAPI_SENDER_NUMBER:'01000000000',SMS_ALLOWLIST:number};const env=k=>values[k];assert.equal(phoneEnabled(env),true);assert.equal(phoneEnabled(k=>k==='CONTEXT'?'production':env(k)),false);
 let sent=0,down=false,reserved;const client={auth:{getUser:async()=>({data:{user:{id:ids.customer}}})},rpc:async(name,{operation,payload})=>{if(operation==='reserve')reserved=payload;return {data:operation==='reserve'?{id:'test-id'}:{saved:true}};}};
 const handler=createPhoneHandler({env,makeClient:()=>client,generate:()=> '123456',fetcher:async(url,request)=>{sent++;assert.equal(url,'https://api.solapi.com/messages/v4/send-many/detail');assert.match(request.headers.Authorization,/HMAC-SHA256/);assert.equal(JSON.parse(request.body).messages[0].type,'SMS');if(down)throw Error('provider-private-data');return Response.json({groupInfo:{count:{registeredSuccess:1}}});}});
 const request=(phone,token='test')=>new Request('https://preview.invalid/api/phone/send-otp',{method:'POST',headers:{origin:values.APP_ORIGIN,...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify({phone})});
 assert.equal((await handler(request(number,''),{ip:'127.0.0.1'})).status,401);assert.equal((await handler(request('+821000000099'),{ip:'127.0.0.1'})).status,403);assert.equal(sent,0);
 const response=await handler(request(number),{ip:'127.0.0.1'});assert.equal(response.status,200);assert.equal(reserved.hash,otpHash(values.SOLAPI_API_SECRET,ids.customer,number,'123456'));const body=await response.text();assert.ok(!/123456|test-key|test-secret/.test(body));assert.equal(reserved.otp,undefined);down=true;assert.equal((await (await handler(request(number),{ip:'127.0.0.1'})).json()).error,'sms_unavailable');
 assert.equal(normalizePhone('010-0000-0001'),number);assert.equal(maskPhone(number),'010-00**-0001');assert.throws(()=>normalizePhone('010abc00000001'));
});
