import {el,kst} from '../consultation-ui.js';
export function contactConsent(name,branch=false){return new Promise(resolve=>{const d=el('dialog',undefined,document.body);d.className='card flow-dialog';d.setAttribute('aria-label','연락처 공개 동의');el('h2','연락처 공개 동의',d);el('p',branch?'선택하신 '+name+'에서 배정된 소속 전문가 1인에게만 연락처가 공개됩니다.':'선택하신 '+name+' 님에게만 연락처가 공개됩니다.',d);el('p','다른 전문가에게는 공개되지 않으며, 영업 목적 사용은 금지됩니다. 동의하고 상담을 신청하시겠어요?',d);el('p','비공개 테스트: 실제 번호 대신 010-0000-0000 형식의 예시 번호만 입력하세요.',d);const label=el('label','예시 연락처',d),input=el('input',undefined,label);input.type='tel';input.value='010-0000-0000';input.maxLength=13;const error=el('p',undefined,d);error.setAttribute('role','alert');const yes=el('button','동의하고 신청',d);yes.className='btn';yes.onclick=()=>{const phone=input.value.replace(/[^0-9]/g,'');if(!/^0100000[0-9]{4}$/.test(phone)){error.textContent='예시 번호만 입력해 주세요.';return;}resolve({contact_phone:phone,contact_consent:true,contact_version:'single-recipient-2026-09-28'});d.close();};const no=el('button','취소',d);no.className='btn ghost';no.onclick=()=>d.close();d.onclose=()=>{resolve(null);d.remove();};d.showModal();});}
export async function mountContact(parent,{command,actor}){
 const root=el('section',undefined,parent);root.className='contact-panel';el('h2','연락·사후관리',root);el('p','선택·배정된 전문가 1인만 연락처를 열람합니다. 목적 외 사용·재판매는 금지됩니다.',root);const status=el('p',undefined,root);status.setAttribute('role','status');const content=el('div',undefined,root);let working=false,dirty=false;
 root.addEventListener('input',()=>dirty=true);const button=(parent,text,fn)=>{const b=el('button',text,parent);b.className='btn ghost';b.type='button';b.onclick=async()=>{if(working)return;working=true;b.disabled=true;try{await fn();status.textContent='처리했습니다.';}catch(e){status.textContent=e.message;}finally{working=false;b.disabled=false;}};return b;};
 const field=(parent,text,multi=false)=>{const l=el('label',text,parent);l.className='field';const i=el(multi?'textarea':'input',undefined,l);i.maxLength=1000;return i;};const select=(parent,text,items)=>{const l=el('label',text,parent);l.className='field';const s=el('select',undefined,l);s.setAttribute('aria-label',text);for(const [v,t]of Object.entries(items)){const o=el('option',t,s);o.value=v;}return s;};
 async function draw(){const items=await command('contact_list');if(!root.isConnected)return;content.replaceChildren();for(const c of items){for(const old of parent.querySelectorAll('[data-request-id="'+c.id+'"],[data-booking-id="'+c.id+'"]')){for(const b of old.querySelectorAll('button'))if(b.textContent==='상태 저장')b.hidden=true;for(const l of old.querySelectorAll('label'))if(l.textContent.includes('상담 진행 상태')||l.textContent.includes('예약 상태'))l.hidden=true;}const card=el('article',undefined,content);card.className='card';card.dataset.contactId=c.id;el('h3',c.expert_name||'거점 담당자 배정 대기',card);el('p',({new:'신규 · 연락 대기',contacted:'연락함',completed:'상담완료'}[c.state])+' · '+kst(c.created_at),card);el('small',c.id,card);if(c.overdue)el('p','⚠ 24시간 미연락 · 담당자 확인 필요',card);if(actor.role==='expert'&&c.expert===actor.id){const number=el('p','선택받은 상담 알림 · 고객 연락처 확인 가능',card);button(card,'연락처 보기',async()=>{const r=await command('contact_view',{id:c.id});number.textContent=r.phone?'예시 연락처: '+r.phone:'연락처가 파기되었습니다.';});if(c.state!=='completed')button(card,c.state==='new'?'연락함으로 변경':'상담완료 처리',async()=>{await command('contact_state',{id:c.id,revision:c.revision,state:c.state==='new'?'contacted':'completed'});await draw();});}
 if(actor.role==='customer'&&c.customer===actor.id){if(c.state==='completed'&&!c.review){const form=el('details',undefined,card);el('summary','상담 후 평가하기',form);const stars=select(form,'별점',{'':'선택','5':'5점','4':'4점','3':'3점','2':'2점','1':'1점'});const opts={'':'선택',yes:'예',no:'아니오'};const sales=select(form,'영업 전화나 원치 않는 보험 가입 권유를 받으셨나요?',opts),money=select(form,'부당하거나 사전 안내 없는 금전을 요구받으셨나요?',opts),helpful=select(form,'전문가가 친절하고 도움이 되었나요?',opts),body=field(form,'자유 후기 (선택 · 민감정보 제외)',true);button(form,'평가 제출',async()=>{if(!stars.value||!sales.value||!money.value||!helpful.value)throw Error('별점과 세 가지 확인을 모두 선택해 주세요.');await command('contact_survey',{id:c.id,stars:Number(stars.value),sales:sales.value==='yes',money:money.value==='yes',helpful:helpful.value==='yes',body:body.value});dirty=false;await draw();});}if(c.review)el('p','평가 완료 · '+c.review.stars+'점',card);const report=el('details',undefined,card);el('summary','위반 신고',report);const reason=field(report,'신고 내용 (5자 이상 · 민감정보 제외)',true);button(report,'신고 접수',async()=>{await command('contact_report',{id:c.id,reason:reason.value});dirty=false;await draw();});}
 if((actor.role==='customer'||actor.role==='admin')&&!c.erased_at)button(card,'연락처 파기',async()=>{await command('contact_erase',{id:c.id});await draw();});}
 if(!items.length)el('p','연락처 공개에 동의한 상담이 아직 없습니다.',content);
 if(actor.role==='admin'){const data=await command('contact_admin');el('h3','위반 의심 · 관리자 확인',content);for(const r of data.reports){const card=el('details',undefined,content);el('summary',(r.expert_name||'미배정')+' · '+(r.decision||'미확인'),card);el('p',r.reason,card);if(!r.decision){const reason=field(card,'판정 사유 (5자 이상)');for(const [decision,label]of [['confirmed','위반 확인'],['dismissed','혐의 없음']])button(card,label,async()=>{await command('contact_report_review',{id:r.id,decision,reason:reason.value});dirty=false;await draw();});}if(r.expert)button(card,'전문가 제재 화면',()=>{const target=document.querySelector('.review-card[data-expert-id="'+r.expert+'"]');if(target){target.querySelector('details').open=true;target.scrollIntoView();}});}
 el('h3','반복 신고·낮은 평점 검토 플래그',content);el('p','신고 2건 이상 또는 후기 3건 이상·평균 3점 미만. 자동 제재하지 않으며 관리자 확인 후 경고 → 노출정지 → 제명합니다.',content);for(const f of data.flags)el('p',f.name+' · 평점 '+(f.rating??'없음')+' · 신고 '+f.suspected_reports+'건',content);el('h3','평점·후기',content);for(const r of data.reviews)el('p',r.stars+'점 · '+r.body+' · '+kst(r.created_at),content);const logs=el('details',undefined,content);el('summary','번호 열람·처리 이력 '+data.logs.length+'건',logs);for(const l of data.logs)el('p',kst(l.at)+' · '+l.actor+' · '+l.action+' · '+l.reason,logs);}
 }
 button(root,'연락·사후관리 새로고침',async()=>{dirty=false;await draw();});await draw();const timer=setInterval(async()=>{if(!root.isConnected){clearInterval(timer);return;}if(document.hidden||working||dirty||root.querySelector('details[open],input:focus,textarea:focus,select:focus'))return;try{await draw();}catch{}},5000);
}
