export function mountSignup(x){
 const {host,isExpert,el,btn,labelInput,select,check,documents,command,readDraft,saveDraft,render,go,switchActor,VERSION,PLEDGES,CENTERS}=x;
 if(!x.social?.identity){host.classList.add('signup-mode');const logo=el('img',undefined,host);logo.src='/brand/logo-stacked.svg';logo.alt='우리곁에 보험소';logo.className='brand-stacked';el('h1','간편하게 시작하세요',host);if(new URLSearchParams(location.search).has('auth_error'))el('p','로그인이 취소되었거나 실패했습니다. 다시 시도하세요.',host);for(const [provider,label]of [['google','구글로 시작'],['kakao','카카오 · 준비중']]){const b=btn(host,label,async()=>{if(provider==='google'&&!x.social?.providers?.google){location.assign('https://bohumso.netlify.app/login.html');return;}const result=await command('social_start',{provider});location.assign(result.url);},true);b.disabled=provider==='kakao';if(b.disabled)b.title='카카오 로그인 준비중';}if(!Object.values(x.social?.providers||{}).some(Boolean)){el('p','구글은 기존 서비스 로그인 화면으로 연결됩니다.',host);btn(host,'테스트 체험 시작',async()=>{await command('social_demo');go('/claim?step=1');});}return;}
 const key=isExpert?'simple-expert':'simple-customer';const d={step:1,phone:'',name:x.social.identity.name||'',region:'',profession:'',agreements:[false,false,false],...readDraft(key)};const total=isExpert?5:3;const save=()=>saveDraft(key,d);host.classList.add('signup-mode');
 el('p',`${d.step} / ${total}`,host);const progress=el('progress',undefined,host);progress.max=total;progress.value=d.step;progress.setAttribute('aria-label','가입 진행');
 const phoneStep=isExpert?2:1,nameStep=isExpert?3:2;el('h1',isExpert?['','직군 선택','연락받을 번호','이름과 활동지역','자격서류','소비자와의 약속'][d.step]:['','연락받을 번호','이름','지역 (선택)'][d.step],host);const form=el('section',undefined,host);form.className='card';let next;const valid=()=>d.step===phoneStep?/^010\d{8}$/.test(d.phone):d.step===nameStep?d.name.trim().length>=2&&d.name.length<=60&&(!isExpert||!!d.region):isExpert&&d.step===1?!!d.profession:isExpert&&d.step===5?d.agreements.every(Boolean):true;const update=()=>{save();if(next)next.disabled=!valid();};
 if(isExpert&&d.step===1){for(const [v,label]of [['adjuster','⚖ 손해사정사'],['planner','▤ 설계사']]){const b=btn(form,label,()=>{d.profession=v;update();render();});b.className='btn '+(d.profession===v?'':'ghost');b.setAttribute('aria-pressed',d.profession===v);}}
 if(d.step===phoneStep){const phone=labelInput(form,'연락받을 번호','phone',d.phone,'tel');phone.placeholder='010-0000-0000';phone.maxLength=13;phone.autocomplete='tel';phone.oninput=()=>{d.phone=phone.value.replace(/[\s-]/g,'');update();};el('small','문자 인증 없이 연락처로만 사용합니다.',form);}

 if(d.step===nameStep){const name=labelInput(form,'이름','name',d.name);name.placeholder='홍길동';name.maxLength=60;name.oninput=()=>{d.name=name.value;update();};}
 if((isExpert&&d.step===3)||(!isExpert&&d.step===3)){const region=select(form,isExpert?'활동지역':'지역',{'':'선택 안 함',...Object.fromEntries(Object.keys(CENTERS).map(k=>[k,k]))},d.region);region.value=d.region;region.onchange=()=>{d.region=region.value;update();};if(!isExpert){const status=el('p','',form);btn(form,'내 위치 사용',()=>{status.textContent='위치 확인 중';navigator.geolocation?.getCurrentPosition(p=>{const nearest=Object.entries(CENTERS).sort((a,b)=>((a[1].lat-p.coords.latitude)**2+(a[1].lng-p.coords.longitude)**2)-((b[1].lat-p.coords.latitude)**2+(b[1].lng-p.coords.longitude)**2))[0];const km=Math.hypot(nearest[1].lat-p.coords.latitude,nearest[1].lng-p.coords.longitude)*111;if(km>20){status.textContent='지역을 직접 선택해 주세요.';return;}d.region=nearest[0];region.value=d.region;status.textContent='가까운 테스트 지역 · 변경 가능';update();},()=>status.textContent='지역을 선택하거나 건너뛰세요.',{timeout:5000,maximumAge:60000});});navigator.permissions?.query({name:'geolocation'}).then(p=>{if(p.state==='granted')form.querySelector('button')?.click();}).catch(()=>{});}}
 if(isExpert&&d.step===4){el('p','나중에 올리면 심사 후 노출됩니다.',form);const details=el('details',undefined,form);el('summary','서류 첨부 (선택)',details);documents(details,d,save);const registration=labelInput(details,'등록번호','registration',d.registration||'');registration.oninput=()=>{d.registration=registration.value;save();};}
 if(isExpert&&d.step===5){check(form,'전체 동의',d.agreements.every(Boolean),v=>{d.agreements=[v,v,v];save();render();});['부당한 금전 요구 금지','원치 않는 가입 권유 금지','외부 유인으로 규정 회피 금지'].forEach((text,i)=>{check(form,text,d.agreements[i],v=>{d.agreements[i]=v;update();});const details=el('details',undefined,form);el('summary','더보기',details);el('p',PLEDGES[i],details);});}
 const footer=el('div',undefined,host);footer.className='wizard-footer';if(d.step>1)btn(footer,'이전',()=>{d.step--;save();render();});next=btn(footer,d.step===total?'가입 완료':'다음',async()=>{if(!valid())return;if(d.step<total){d.step++;save();render();return;}await command(isExpert?'signup_expert':'signup_customer',{...d,organization:'미입력',specialties:[],agreement_version:VERSION});saveDraft(key,{});if(isExpert){host.replaceChildren();el('h1','가입 완료',host);el('p','미인증 · 서류 제출 후 심사',host);btn(host,'내 프로필',()=>render(),true);}else{if(d.region)saveDraft('claim',{...readDraft('claim'),region:d.region});go('/claim?step=1');}},true);next.id='signupNext';update();if(!isExpert&&d.step===1)btn(form,'전문가로 가입',()=>switchActor('new_expert','/expert'));
}
