import {randomBytes} from 'node:crypto';
const providers={google:{auth:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',user:'https://openidconnect.googleapis.com/v1/userinfo'},kakao:{auth:'https://kauth.kakao.com/oauth/authorize',token:'https://kauth.kakao.com/oauth/token',user:'https://kapi.kakao.com/v2/user/me'}};
export function createSocialLogin(env={},request=fetch){const pending=new Map(),identities=new Map();const enabled=p=>env.SOCIAL_TEST_ENABLED==='true'&&!!env[p.toUpperCase()+'_CLIENT_ID']&&!!env[p.toUpperCase()+'_CLIENT_SECRET'];return{
 status(sid){return{providers:Object.fromEntries(Object.keys(providers).map(p=>[p,enabled(p)])),identity:identities.get(sid)||null,phoneSource:'manual',kakaoSync:false};},
 demo(sid){const user={provider:'demo',id:'demo',name:'가상고객',email:'demo@example.test',test:true};identities.set(sid,user);return user;},
 start(sid,provider,origin){if(!providers[provider]||!enabled(provider))throw Error('소셜 로그인 키 설정이 필요합니다.');const state=randomBytes(32).toString('hex');pending.set(sid,{state,provider,origin,created:Date.now()});const url=new URL(providers[provider].auth);url.search=new URLSearchParams({client_id:env[provider.toUpperCase()+'_CLIENT_ID'],redirect_uri:origin+'/auth/callback',response_type:'code',state,scope:provider==='google'?'openid email profile':env.KAKAO_EMAIL_ENABLED==='true'?'profile_nickname,account_email':'profile_nickname'});return url.href;},
 async finish(sid,params){const flow=pending.get(sid);pending.delete(sid);if(!flow||Date.now()-flow.created>600000||params.get('state')!==flow.state||!params.get('code')||params.has('error'))throw Error('로그인이 취소되었거나 만료됐습니다. 다시 시작하세요.');const p=providers[flow.provider];const r=await request(p.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:env[flow.provider.toUpperCase()+'_CLIENT_ID'],client_secret:env[flow.provider.toUpperCase()+'_CLIENT_SECRET'],code:params.get('code'),redirect_uri:flow.origin+'/auth/callback'}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('로그인 승인 실패');const token=await r.json();if(!token.access_token)throw Error('로그인 승인 실패');const info=await request(p.user,{headers:{Authorization:'Bearer '+token.access_token},signal:AbortSignal.timeout(10000)});if(!info.ok)throw Error('프로필 조회 실패');const data=await info.json();const id=flow.provider==='google'?data.sub:data.id;if(!id)throw Error('사용자 확인 실패');const user={provider:flow.provider,id:String(id),name:String(flow.provider==='google'?data.name||'':data.kakao_account?.profile?.nickname||''),email:flow.provider==='google'?(data.email_verified?data.email:null):(data.kakao_account?.is_email_verified?data.kakao_account.email:null),test:false};identities.set(sid,user);return user;}
};}
export const normalizeContact=value=>String(value||'').replace(/[\s-]/g,'');
export const validContact=value=>/^010\d{8}$/.test(normalizeContact(value));
