import {el,kst} from '../consultation-ui.js';
import {GUIDANCE,SUPPORT_SITUATIONS,matchFAQ,classifySituation} from './support-rules.mjs';
export function createSupport({command,navigate}){
 let actor=null,faqs=[],inquiries=[],messages=[],generation=0,working=false,formKey=crypto.randomUUID();
 const launcher=el('button','문의하기',document.body);launcher.type='button';launcher.className='support-launcher';launcher.setAttribute('aria-controls','supportChat');launcher.setAttribute('aria-expanded','false');
 const panel=el('section',undefined,document.body);panel.id='supportChat';panel.className='support-panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-label','우리곁에 보험소 고객센터');
 const header=el('header',undefined,panel);el('strong','우리곁에 보험소 고객센터',header);const close=el('button','닫기',header);close.type='button';close.onclick=()=>{panel.hidden=true;launcher.setAttribute('aria-expanded','false');launcher.focus();};panel.addEventListener('keydown',e=>{if(e.key==='Escape')close.click();});
 const body=el('div',undefined,panel);body.className='support-body';const intro=el('div',undefined,body);intro.className='support-intro';el('p','무엇을 도와드릴까요? 아래에서 고르거나 입력창에 질문을 적어 주세요.',intro);el('small','규칙 기반 자동안내 · AI 아님 · 예시 데이터만 입력',intro);
 const quick=el('div',undefined,body);quick.className='support-quick';el('small','자주 묻는 질문',quick);const choices=el('div',undefined,quick);choices.className='support-chips';el('small','상황별 전문가 연결',quick);const situations=el('div',undefined,quick);situations.className='support-chips';
 const transcript=el('div',undefined,body);transcript.className='support-transcript';transcript.setAttribute('role','log');transcript.setAttribute('aria-live','polite');
 const saved=el('div',undefined,body);saved.className='support-saved';saved.setAttribute('aria-live','polite');
 const fallback=el('details',undefined,body);el('summary','상담 신청 남기기',fallback);el('p','자동안내로 해결되지 않았나요? 관리자에게 문의를 남겨 주세요. 답변은 이 채팅에서 확인할 수 있어요.',fallback);el('small','건강정보·보험증권·주민등록번호 등 민감정보는 적지 마세요. 가상 내용만 입력하세요.',fallback);
 const label=el('label','관리자에게 남길 문의',fallback),question=el('textarea',undefined,label);question.maxLength=1000;question.rows=3;question.placeholder='예: 예약 화면 이용이 어려워요';const consentLabel=el('label',undefined,fallback);consentLabel.className='check-row';const consent=el('input',undefined,consentLabel);consent.type='checkbox';consentLabel.append(document.createTextNode('문의 확인·답변을 위해 이 내용을 관리자에게 전달하는 데 동의합니다.'));
 const submit=el('button','문의 접수',fallback);submit.type='button';submit.className='btn';submit.disabled=true;const valid=()=>submit.disabled=!consent.checked||question.value.trim().length<2||working;consent.onchange=valid;question.oninput=valid;
 const footer=el('form',undefined,panel);footer.className='support-input';const input=el('input',undefined,footer);input.setAttribute('aria-label','고객센터 질문');input.maxLength=500;input.placeholder='질문 또는 키워드 입력';const send=el('button','보내기',footer);send.type='submit';const status=el('p',undefined,panel);status.className='support-status';status.setAttribute('role','status');
 function action(parent,text,callback){const b=el('button',text,parent);b.type='button';b.onclick=callback;return b;}
 function jump(kind,situation){panel.hidden=true;launcher.setAttribute('aria-expanded','false');navigate(kind,situation);}
 for(const [key,text]of Object.entries(SUPPORT_SITUATIONS))action(situations,text,()=>{add('auto',GUIDANCE,'situation',key);});
 function add(role,text,kind='none',situation){messages.push({role,text,kind,situation});drawMessages();transcript.lastElementChild?.scrollIntoView({block:'nearest'});}
 function drawMessages(){transcript.replaceChildren();for(const m of messages){const bubble=el('article',undefined,transcript);bubble.className='support-bubble '+m.role;el('small',m.role==='user'?'나':'자동안내',bubble);el('p',m.text,bubble);if(m.kind!=='none')action(bubble,m.kind==='map'?'지도 보기':m.kind==='reserve'?'예약하기':m.situation?'이 상황으로 전문가 찾기':'상황 선택',()=>jump(m.kind,m.situation));}}
 function answer(f){add('user',f.question);add('auto',f.answer,f.action);}
 function drawFAQs(){choices.replaceChildren();faqs.forEach(f=>action(choices,f.question,()=>answer(f)));}
 function drawInquiries(){saved.replaceChildren();for(const item of inquiries){const card=el('article',undefined,saved);card.className='support-bubble';card.dataset.inquiryId=item.id;el('small',kst(item.created_at)+' · '+(item.answer?'답변 완료':'관리자 답변 대기'),card);el('p',item.question,card);if(item.answer){el('strong','관리자 답변',card);el('p',item.answer,card);el('small',kst(item.answered_at),card);}}}
 async function refresh(){const ticket=generation;try{const [nextFaq,nextInquiries]=await Promise.all([command('support_faq'),command('support_mine')]);if(ticket!==generation)return;if(JSON.stringify(faqs)!==JSON.stringify(nextFaq)){faqs=nextFaq;drawFAQs();}if(JSON.stringify(inquiries)!==JSON.stringify(nextInquiries)){inquiries=nextInquiries;drawInquiries();}}catch(e){if(ticket===generation)status.textContent=e.message;}}
 launcher.onclick=async()=>{panel.hidden=false;launcher.setAttribute('aria-expanded','true');await refresh();close.focus();};
 footer.onsubmit=e=>{e.preventDefault();const text=input.value.trim();if(!text)return;input.value='';add('user',text);const f=matchFAQ(text,faqs);if(f){add('auto',f.answer,f.action);return;}const situation=classifySituation(text);add('auto',GUIDANCE,situation?'situation':'none',situation);if(!situation){fallback.open=true;question.focus();}};
 submit.onclick=async()=>{if(working||submit.disabled)return;working=true;valid();const ticket=generation;try{const item=await command('support_submit',{question:question.value.trim(),consent:consent.checked,request_key:formKey});if(ticket!==generation)return;status.textContent='문의가 접수됐어요. 관리자가 확인하면 여기에 답변이 표시됩니다.';question.value='';consent.checked=false;formKey=crypto.randomUUID();fallback.open=false;await refresh();saved.querySelector('[data-inquiry-id="'+item.id+'"]')?.scrollIntoView({block:'nearest'});}catch(e){if(ticket===generation)status.textContent=e.message;}finally{working=false;valid();}};
 setInterval(()=>{if(!panel.hidden&&!document.hidden&&!working)refresh();},2000);
 return {syncActor(next){if(actor===next.id)return;actor=next.id;generation++;messages=[];faqs=[];inquiries=[];question.value='';consent.checked=false;input.value='';status.textContent='';fallback.open=false;formKey=crypto.randomUUID();valid();drawMessages();drawFAQs();drawInquiries();if(!panel.hidden)refresh();}};
}
export async function mountSupportAdmin(parent,{command}){
 const root=el('section',undefined,parent);root.className='support-admin';el('h2','고객센터 문의·FAQ',root);el('p','이용 안내와 전문가 연결만 답변하세요. 청구 방법·보험 판단은 전문가 상담으로 안내합니다.',root);const status=el('p',undefined,root);status.setAttribute('role','status');const refreshButton=el('button','고객센터 새로고침',root);refreshButton.type='button';refreshButton.className='btn ghost';const content=el('div',undefined,root);let dirty=false,working=false;
 root.addEventListener('input',()=>dirty=true);
 const button=(parent,text,fn)=>{const b=el('button',text,parent);b.type='button';b.className='btn';b.onclick=async()=>{if(working)return;working=true;b.disabled=true;try{await fn();dirty=false;await draw();status.textContent='저장했습니다.';}catch(e){status.textContent=e.message;}finally{working=false;b.disabled=false;}};return b;};
 function field(parent,label,value='',multiline=false){const wrap=el('label',label,parent);wrap.className='field';const input=el(multiline?'textarea':'input',undefined,wrap);input.value=value;if(multiline){input.rows=3;input.maxLength=1200;}else input.maxLength=120;return input;}
 function faqForm(parent,f){const details=el('details',undefined,parent);el('summary',f?f.question:'새 FAQ 추가',details);const q=field(details,'FAQ 질문',f?.question||''),a=field(details,'FAQ 답변',f?.answer||'',true),keys=field(details,'키워드 (쉼표로 구분)',f?.keywords.join(', ')||'');keys.maxLength=800;const label=el('label','연결 버튼',details),sel=el('select',undefined,label);sel.setAttribute('aria-label','연결 버튼');for(const [value,text]of Object.entries({none:'없음',reserve:'예약하기',map:'지도 보기',situation:'상황 선택'})){const o=el('option',text,sel);o.value=value;}sel.value=f?.action||'none';button(details,f?'FAQ 수정 저장':'FAQ 추가',()=>command('support_faq_save',{id:f?.id,revision:f?.revision,question:q.value.trim(),answer:a.value.trim(),keywords:keys.value.split(',').map(x=>x.trim()).filter(Boolean),action:sel.value}));if(f)button(details,'FAQ 삭제',()=>command('support_faq_delete',{id:f.id,revision:f.revision}));}
 async function draw(){const [items,faqs]=await Promise.all([command('support_admin'),command('support_faq')]);if(!root.isConnected)return;content.replaceChildren();el('h3','문의함 · 미답변 '+items.filter(x=>!x.answer).length+'건',content);if(!items.length)el('p','아직 접수된 문의가 없습니다.',content);for(const item of items){const card=el('article',undefined,content);card.className='card support-ticket';card.dataset.inquiryId=item.id;el('h4',item.answer?'답변 완료':'미답변',card);el('p',item.question,card);el('small',kst(item.created_at),card);const response=field(card,'관리자 답변',item.answer||'',true);button(card,'답변 저장',()=>command('support_reply',{id:item.id,revision:item.revision,answer:response.value.trim()}));}el('h3','FAQ 관리',content);faqForm(content,null);faqs.forEach(f=>faqForm(content,f));}
 refreshButton.onclick=async()=>{try{await draw();dirty=false;status.textContent='최신 목록입니다.';}catch(e){status.textContent=e.message;}};
 const timer=setInterval(async()=>{if(!root.isConnected){clearInterval(timer);return;}if(document.hidden||dirty||working||root.querySelector('details[open],input:focus,textarea:focus,select:focus'))return;try{await draw();}catch(e){status.textContent=e.message;}},3000);
 try{await draw();}catch(e){status.textContent=e.message;}
}
