import {createSupport,mountSupportAdmin} from './support.js';
import {AREAS} from './areas.js';
import {mountDirectoryMap} from './map.js';
import {el,kst,sortedProfiles} from '../consultation-ui.js';import {prepareDocument} from '../expert-shared.js';
const branchName=area=>{const parts=String(area||'').trim().split(/\s+/);return (parts.findLast(x=>x.endsWith('구'))||parts.at(-1)||'지역').replace(/[구시군]$/,'')+' 보험소';};
const $=id=>document.getElementById(id),host=$('app');
const VERSION='consumer-protection-2026-09-26-v2';const PLEDGES=['청구·상담 지원 과정에서 소비자에게 부당하거나 사전 고지되지 않은 금전을 요구하지 않는다. (자격자가 사전에 서면 고지한 정당한 보수는 허용)','소비자가 먼저 요청하지 않는 한, 신규 보험 가입을 먼저 권유하지 않는다.','플랫폼 외부로 소비자를 유인해 위 규정을 회피하지 않는다.'];
const SITUATIONS={death:'사망·상속',cancer:'암·중대질병',denial:'청구 거절·삭감',disability:'후유장해',other:'기타'};const JOBS={adjuster:'손해사정사',planner:'설계사'};const STATUS={unverified:'미인증',pending:'심사중',needs_changes:'보완 요청',rejected:'거절',verified:'인증완료'};const METHODS={office:'보험소로 방문',visit:'전문가가 와주세요',remote:'전화·메시지'};const RECEIPTS={new:'신규',delivered:'전달함',completed:'완료'};
const CENTERS={'마포구':{lat:37.555,lng:126.93},'송파구':{lat:37.514,lng:127.106},'분당구':{lat:37.382,lng:127.119}};
const CONSUMER_CENTERS={...CENTERS,'수정구':{lat:37.450,lng:127.145}};
const SLOTS={'오전 (9-12시)':'오전 (9-12시)','오후 (13-17시)':'오후 (13-17시)','저녁 (18-20시)':'저녁 (18-20시)'};const BOOKING_STATE={new:'신규 접수',assigned:'전문가 배정완료',completed:'상담 완료'};const EXPERT_STATES={new:'신규 접수',delivered:'상담 진행중',completed:'상담 완료'};
function dist(a,b){if(!a||!b)return null;const R=6371,rad=x=>x*Math.PI/180;const dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng);const s=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(s));}
let adminFingerprint="";const fingerprint=data=>JSON.stringify([data.experts.map(e=>[e.id,e.revision]),data.requests.map(r=>[r.id,r.revision]),(data.bookings||[]).map(b=>[b.id,b.revision])]);
let state,workspace,catalog=[],position=null,busy=false,renderId=0;const urls=[];const mapCleanups=[];
const routeName=()=>{const p=location.pathname;return ['/','/index.html'].includes(p)?'home':/branch/.test(p)?'branch':/admin/.test(p)?'admin':/expert|partner|signup|login|account/.test(p)?'expert':/requests|dashboard/.test(p)?'requests':'claim';};
const draftKey=kind=>'flow-'+kind+'-'+workspace.actor.id;const readDraft=kind=>{try{return JSON.parse(sessionStorage.getItem(draftKey(kind)))||{};}catch{return {};}};const saveDraft=(kind,value)=>sessionStorage.setItem(draftKey(kind),JSON.stringify(value));
async function command(operation,payload={}){const response=await fetch('/api/test-flow/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,payload})});if(operation==='document'&&response.ok)return response.blob();const data=await response.json();if(!response.ok)throw Error(data.error);if(operation==='branch_catalog')return data.map(b=>({...b,name:branchName(b.district)}));if(operation==='branch_detail'&&data)data.name=branchName(data.district);return data;}
async function updateState(){const r=await fetch('/api/test-flow/state',{cache:'no-store'});if(!r.ok)throw Error('비공개 테스트 서버에서 실행해 주세요.');state=await r.json();workspace=state.workspace;$('backendState').textContent=state.backend==='supabase-test'?'Supabase 테스트 DB 연결':'로컬 PostgreSQL 저장 · Supabase 원격 미연결';$('actorName').textContent=workspace.actor.name+' · '+({customer:'소비자',expert:'전문가',admin:'관리자',branch:'보험소 거점 운영자'}[workspace.actor.role]);}
function go(path){history.pushState(null,'',path);render();}
async function switchActor(actor,target){const r=await fetch('/api/test-flow/switch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor})});if(!r.ok)throw Error('계정 전환 실패');await updateState();go(target);}
function btn(parent,text,fn,primary=false){const b=el('button',text,parent);b.type='button';b.className='btn '+(primary?'':'ghost');b.onclick=()=>run(()=>fn(b));return b;}
async function run(fn){if(busy)return;busy=true;$('globalMessage').textContent='';try{await fn();}catch(e){$('globalMessage').textContent=e.message;}finally{busy=false;}}
function labelInput(parent,label,name,value='',type='text'){const l=el('label',label,parent);l.className='field';const input=el('input',undefined,l);input.name=name;input.type=type;input.value=value;input.maxLength=120;return input;}
function select(parent,label,items,value){const l=el('label',label,parent);l.className='field';const s=el('select',undefined,l);s.setAttribute('aria-label',label);for(const [key,text]of Object.entries(items)){const o=el('option',text,s);o.value=key;}s.value=value||Object.keys(items)[0];return s;}
function check(parent,label,value,fn){const l=el('label',undefined,parent);l.className='check-row';const c=el('input',undefined,l);c.type='checkbox';c.checked=!!value;l.append(document.createTextNode(label));c.onchange=()=>fn(c.checked);return c;}
function title(kicker,text,description){el('p',kicker,host).className='eyebrow';el('h1',text,host);if(description)el('p',description,host).className='subcopy';}
function dialog(titleText,body){const d=el('dialog',undefined,document.body);d.className='card flow-dialog';el('h2',titleText,d);body(d);btn(d,'닫기',()=>d.close());d.onclose=()=>d.remove();d.showModal();}
function pledge(parent){const b=btn(parent,'소비자보호 서약',()=>dialog('소비자보호 서약',d=>{const list=el('ol',undefined,d);PLEDGES.forEach(x=>el('li',x,list));el('p','동의 사실의 표시이며 실제 자격·결과를 보증하지 않습니다. 가상 전문가입니다.',d);}));b.className='pledge-badge';}
function chooseAccounts(){dialog('가상 계정으로 전환',d=>{el('p','실제 로그인·권한 승인이 아닙니다. 테스트 역할을 선택하세요.',d);for(const [role,label,target]of [['customer','소비자','/'],['expert','내 가상 전문가','/expert'],['new_expert','새 가상 전문가 만들기','/expert'],['branch','보험소 거점 운영자','/branch.html'],['admin','테스트 관리자','/admin']])btn(d,label,async()=>{d.close();await switchActor(role,target);});});}
function roleNavigation(){const nav=$('roleNavigation');nav.replaceChildren();const role=workspace.actor.role;const items=role==='customer'?[['/','홈'],['/#nearbyExperts','전문가 찾기'],['/requests.html','내 신청'],['/signup.html','회원가입']]:role==='expert'?[['/','홈'],['/expert','내 프로필']]:role==='branch'?[['/','홈'],['/branch.html','거점 업무']]:[['/','홈'],['/admin','심사·접수']];for(const [href,label]of items){const a=el('a',label,nav);a.href=href;}}
async function home(ticket){const hero=el('section',undefined,host);hero.className='home-intro';const copy=el('div',undefined,hero);copy.className='intro-copy';const heading=el('h1',undefined,copy);el('span','보험금 청구가 막막할 때,',heading);el('span','가까운 전문가를 만나세요.',heading);el('p','청구 준비부터 보장 점검까지, 함께.',copy).className='intro-description';btn(copy,'보험금 청구 도움받기',async()=>{if(workspace.actor.role!=='customer')await switchActor('customer','/claim?step=1');else go('/claim?step=1');},true);el('p','소비자 이용 무료 · 보험 가입 의무 없음',copy).className='intro-footnote';hero.append($('homeArtwork').content.cloneNode(true));
 const nearby=el('section',undefined,host);nearby.id='nearbyExperts';const headingRow=el('div',undefined,nearby);headingRow.className='nearby-heading';el('h2','우리 동네 전문가 지도',headingRow);el('p','예시 전문가 · 직접 선택하고 상담을 요청하세요.',headingRow);const draft={region:'마포구',situation:'other',...readDraft('claim')};saveDraft('claim',draft);await directory(nearby,ticket,draft,true);if(!locationAttempted){locationAttempted=true;locate();}if(location.hash==='#nearbyExperts')nearby.scrollIntoView();
}
async function booking(ticket){const draft={region:'마포구',situation:'other',method:'office',...readDraft('claim')};const keep=()=>saveDraft('claim',draft);
 if(!draft.branch){title('보험소 예약','예약할 보험소를 먼저 선택해 주세요.');btn(host,'지도로 이동',()=>go('/'),true);return;}
 let branch;try{branch=await command('branch_detail',{id:draft.branch});}catch{}if(ticket!==renderId)return;
 if(!branch){title('보험소 예약','선택한 보험소를 찾을 수 없습니다.');btn(host,'지도로 이동',()=>{draft.branch=null;keep();go('/');},true);return;}
 if(draft.bookingReceipt&&draft.bookingReceipt.branch===branch.id){const r=draft.bookingReceipt;title('예약 접수 완료','보험소 예약이 접수됐습니다.',branch.name+' · 거점이 확인 후 담당 전문가를 배정합니다. 자동 발송·정보 판매는 없습니다.');const box=el('section',undefined,host);box.className='card';el('p',branch.name+' · '+METHODS[r.method],box);el('p',SITUATIONS[r.situation]+(r.preferred_date?' · '+r.preferred_date+' '+(r.preferred_slot||''):''),box);el('p','예약번호 '+r.id,box);el('p','상태: '+BOOKING_STATE[r.state],box);btn(host,'다른 보험소·전문가 보기',()=>{draft.bookingReceipt=null;draft.branch=null;keep();go('/');},true);btn(host,'홈으로',()=>{draft.bookingReceipt=null;keep();go('/');});return;}
 title('보험소 예약',branch.name,branch.address+' · 소속 전문가 '+branch.expert_count+'명');const badges=el('div',undefined,host);badges.className='branch-badges';el('span','영업 전화 없음',badges).className='chip';el('span','소비자보호 서약',badges).className='chip';
 const form=el('section',undefined,host);form.className='card';const situation=select(form,'상담 상황',SITUATIONS,draft.situation);situation.onchange=()=>{draft.situation=situation.value;keep();};const method=select(form,'예약 방식 (①보험소 방문 ②전문가 방문 ③전화·메시지)',METHODS,draft.method);method.onchange=()=>{draft.method=method.value;keep();};const date=labelInput(form,'희망 날짜','preferred_date',draft.preferred_date||'','date');date.oninput=()=>{draft.preferred_date=date.value;keep();};const slot=select(form,'희망 시간대',SLOTS,draft.preferred_slot||Object.keys(SLOTS)[0]);slot.onchange=()=>{draft.preferred_slot=slot.value;keep();};const name=labelInput(form,'이름','name',draft.name||'');name.oninput=()=>{draft.name=name.value;keep();};const phone=labelInput(form,'연락처','phone',draft.phone||'','tel');phone.oninput=()=>{draft.phone=phone.value;keep();};
 let consent=!!draft.bookingConsent;const send=btn(host,'보험소 예약 완료',async b=>{b.disabled=true;try{if(!consent)throw Error('예약 접수 동의를 확인해 주세요.');if(!(name.value||'').trim()||!(phone.value||'').trim())throw Error('이름과 연락처를 입력해 주세요.');draft.bookingKey ||= crypto.randomUUID();keep();const r=await command('book',{branch:branch.id,situation:draft.situation,method:draft.method,preferred_date:draft.preferred_date||'',preferred_slot:draft.preferred_slot||'',name:name.value.trim(),phone:phone.value.trim(),consent:true,request_key:draft.bookingKey});draft.bookingReceipt=r;draft.bookingKey=null;keep();render();}finally{b.disabled=false;}},true);
 const row=check(host,'선택한 보험소로 예약을 접수합니다. 거점이 수기로 확인하며 자동 발송·정보 판매는 없습니다.',consent,v=>{consent=v;draft.bookingConsent=v;keep();send.disabled=!v;});host.insertBefore(row.parentElement,send);send.disabled=!consent;el('p','소비자 이용 무료 · 건강정보 상세를 적지 마세요.',host);btn(host,'이전 · 지도',()=>go('/'));
}
async function claim(ticket){if(workspace.actor.role!=='customer'){title('소비자 상담','소비자 테스트 계정으로 체험하세요');btn(host,'소비자로 전환',()=>switchActor('customer','/claim?step=1'),true);return;}if(new URLSearchParams(location.search).get('target')==='branch')return booking(ticket);const draft={region:'마포구',...readDraft('claim')};let step=Number(new URLSearchParams(location.search).get('step')||1);if(step>1&&!draft.situation)step=1;if(step===3&&!draft.expert)step=2;const progress=el('p',['','1 / 4 · 상황 선택','2 / 4 · 전문가 선택','3 / 4 · 상담 방식','4 / 4 · 접수 완료'][step]||'',host);progress.className='step-progress';const keep=()=>saveDraft('claim',draft);
 if(step===1){title('상담 시작','어떤 도움이 필요하세요?','상세한 병력이나 민감정보를 적을 필요가 없습니다.');const grid=el('div',undefined,host);grid.className='choice-grid';for(const [key,text]of Object.entries(SITUATIONS)){const b=btn(grid,text,()=>{draft.situation=key;draft.requestKey=crypto.randomUUID();keep();go('/claim?step=2');});b.className='card choice'+(draft.situation===key?' selected':'');}btn(host,'이전 · 홈',()=>go('/'));return;}
 if(step===2){title(SITUATIONS[draft.situation],'가까운 전문가를 직접 선택하세요','인증완료 가상 전문가만 표시됩니다.');await directory(host,ticket,draft,false);return;}
 if(step===3){const experts=await command('catalog',{});if(ticket!==renderId)return;const expert=experts.find(p=>p.id===draft.expert);if(!expert){el('p','선택한 전문가가 현재 노출되지 않습니다. 다른 전문가를 선택해 주세요.',host);btn(host,'지도에서 다시 선택',()=>go('/claim?step=2'));return;}title('상담 방식','어떤 방식이 편하세요?',expert.name+' · '+SITUATIONS[draft.situation]);const grid=el('div',undefined,host);grid.className='choice-grid';for(const [key,text]of Object.entries(METHODS)){const b=btn(grid,text,()=>{draft.method=key;draft.requestKey=crypto.randomUUID();keep();render();});b.className='card choice'+(draft.method===key?' selected':'');b.setAttribute('aria-pressed',String(draft.method===key));}let consent=!!draft.consent;const send=btn(host,'상담 신청 완료',async b=>{b.disabled=true;try{if(!consent||!draft.method)throw Error('방식과 접수 동의를 확인해 주세요.');draft.requestKey ||= crypto.randomUUID();keep();const r=await command('request',{expert:draft.expert,situation:draft.situation,method:draft.method,consent:true,request_key:draft.requestKey});draft.receipt=r.id;keep();go('/claim?step=4');}finally{b.disabled=false;}},true);const row=check(host,'선택한 전문가 상담을 위해 관리자에게 접수합니다. 대표가 수기로 전달하며 자동 발송하지 않습니다.',consent,v=>{consent=v;draft.consent=v;keep();send.disabled=!v||!draft.method;});host.insertBefore(row.parentElement,send);send.disabled=!consent||!draft.method;el('p','소비자 이용 무료 · 보험 가입 의무 없음 · 건강정보를 입력하지 마세요.',host);btn(host,'이전 · 전문가 선택',()=>go('/claim?step=2'));return;}
 await updateState();if(ticket!==renderId)return;const receipt=workspace.requests.find(r=>r.id===draft.receipt);if(!receipt){go('/requests.html');return;}title('접수 완료','상담 신청이 접수됐습니다.','관리자가 확인 후 선택한 전문가에게 수기로 전달합니다.');const box=el('section',undefined,host);box.className='card';el('p',receipt.expert_name+' · '+METHODS[receipt.method],box);el('p','접수번호 '+receipt.id,box);el('p','상태: '+RECEIPTS[receipt.state],box);btn(host,'내 신청 확인',()=>go('/requests.html'),true);btn(host,'홈으로',()=>go('/'));
}
let locationAttempted=false;
let locating=false,locationMessage='';
function locationFeedback(text){locationMessage=text;document.querySelectorAll('.location-status').forEach(n=>n.textContent=text);document.querySelectorAll('[data-locate]').forEach(b=>{b.disabled=locating;b.textContent=locating?'위치 확인 중…':'내 위치 사용';});}
async function locate(){if(locating)return;if(!navigator.geolocation||!window.isSecureContext){locationFeedback('이 브라우저에서는 위치 확인을 사용할 수 없습니다. 지역을 직접 선택해 주세요.');return;}locating=true;locationFeedback('현재 위치를 확인하고 있어요. 위치 접근 요청이 뜨면 허용해 주세요.');
 const get=high=>new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:high,timeout:high?15000:10000,maximumAge:0}));
 try{let p;try{p=await get(false);}catch(e){if(e.code===1)throw e;p=await get(true);}position={lat:p.coords.latitude,lng:p.coords.longitude};const d=readDraft('claim');const nearest=[...AREAS].sort((a,b)=>dist(position,a)-dist(position,b))[0];d.area=nearest.region+' '+nearest.name;d.region=nearest.name.split(' ').at(-1);d.expert=null;d.branch=null;saveDraft('claim',d);locating=false;locationMessage='내 위치를 기준으로 지도를 이동했어요. 표시 지역은 가까운 지역 기준점입니다.';await render();}
 catch(e){locating=false;locationFeedback(e.code===1?'위치 접근이 차단되어 있어요. 브라우저의 사이트 권한과 기기의 위치 설정을 허용한 뒤 다시 눌러 주세요. 지역을 직접 선택할 수도 있어요.':e.code===3?'위치 확인 시간이 초과됐어요. 기기의 위치 서비스를 켜고 다시 시도하거나 지역을 선택해 주세요.':'기기에서 현재 위치를 가져오지 못했어요. 위치 서비스를 확인하거나 지역을 직접 선택해 주세요.');}}
async function directory(host,ticket,draft,onHome){const keep=()=>saveDraft('claim',draft);draft.mapView=draft.mapView||'all';
 const toggle=el('div',undefined,host);toggle.className='map-view-toggle';toggle.setAttribute('role','group');toggle.setAttribute('aria-label','지도 표시 범위');for(const [key,label]of [['all','전체'],['branch','보험소 거점만'],['expert','개인 전문가만']]){const t=el('button',label,toggle);t.type='button';t.className='view-tab'+(draft.mapView===key?' active':'');t.setAttribute('aria-pressed',String(draft.mapView===key));t.onclick=()=>{draft.mapView=key;keep();render();};}
 const area=AREAS.find(a=>a.region+' '+a.name===draft.area)||AREAS.find(a=>a.name===draft.region||a.name.endsWith(' '+draft.region))||AREAS[0];const toolbar=el('div',undefined,host);toolbar.className='map-toolbar';const region=select(toolbar,'활동 지역',Object.fromEntries(AREAS.map(a=>[a.region+' '+a.name,a.region+' '+a.name])),area.region+' '+area.name);region.onchange=()=>{const selected=AREAS.find(a=>a.region+' '+a.name===region.value);draft.area=region.value;draft.region=selected.name.split(' ').at(-1);draft.expert=null;draft.branch=null;position=null;locationMessage='';locationAttempted=true;keep();render();};const locateButton=btn(toolbar,locating?'위치 확인 중…':'내 위치 사용',()=>{locationAttempted=true;locate();});locateButton.dataset.locate='';locateButton.disabled=locating;const locationStatus=el('p',locationMessage,host);locationStatus.className='location-status quiet';locationStatus.setAttribute('role','status');
  const profession=select(toolbar,'직군',{'':'전체 직군',...JOBS},draft.professionFilter||'');profession.onchange=()=>{draft.professionFilter=profession.value;draft.expert=null;keep();render();};const field=select(toolbar,'전문분야',{'':'전체 분야',...SITUATIONS},draft.specialtyFilter||'');field.onchange=()=>{draft.specialtyFilter=field.value;draft.expert=null;keep();render();};const center=position||{lat:area.lat,lng:area.lng};
  const all=await command('catalog',position?{}:{region:draft.region});const list=all.filter(p=>(!draft.professionFilter||p.profession===draft.professionFilter)&&(!draft.specialtyFilter||p.specialties.includes(draft.specialtyFilter)));if(ticket!==renderId)return;catalog=sortedProfiles(list,center,draft.situation);
  let branches=[];try{branches=await command('branch_catalog',{});}catch{}if(ticket!==renderId)return;branches=[...branches,...AREAS.filter(a=>!branches.some(b=>(b.district===a.name||a.name.endsWith(' '+b.district))&&dist({lat:a.lat,lng:a.lng},{lat:b.latitude,lng:b.longitude})<15)).map(a=>({id:'planned:'+a.region+':'+a.name,name:branchName(a.name),district:a.region+' '+a.name,latitude:a.lat,longitude:a.lng,planned:true,expert_count:0}))];branches=branches.map(b=>({...b,kind:'branch',distance:dist(center,{lat:b.latitude,lng:b.longitude})})).sort((a,b)=>(a.distance??9e9)-(b.distance??9e9));
  const points=[...(draft.mapView!=='expert'?branches:[]),...(draft.mapView!=='branch'?catalog.map(p=>({...p,kind:'expert'})):[])];
  const notice=el('p','예시 위치 · 지도 불러오는 중',host);notice.className='map-notice';const map=el('section',undefined,host);map.className='test-map';map.setAttribute('aria-label','우리 동네 보험소·전문가 지도');el('span',position?'내 위치 주변':area.region+' '+area.name+' 주변',map).className='map-label';const markerHost=el('div',undefined,map);markerHost.className='markers';let zoom=1;
  const pick=p=>{if(p.kind==='branch'){draft.branch=p.id;keep();showBranch(p);}else{draft.expert=p.id;draft.requestKey=crypto.randomUUID();keep();showProfile(p);}};
  const drawMarkers=()=>{markerHost.replaceChildren();points.forEach((p,index)=>{const isB=p.kind==='branch';const b=btn(markerHost,isB?'🏠 '+p.name:(p.profession==='adjuster'?'손해':'설계')+' · '+p.name,()=>pick(p));b.className='map-marker'+(isB?' branch-marker':'');b.dataset[isB?'branchId':'expertId']=p.id;if(p.planned){b.classList.add('planned-marker');b.textContent+=' · 예정';}b.style.left=Math.max(12,Math.min(72,40+(p.longitude-center.lng)*1000*zoom+(index%3)*7))+'%';b.style.top=Math.max(16,Math.min(50,25-(p.latitude-center.lat)*800*zoom+(index%2)*12))+'%';});};const controls=el('div',undefined,map);controls.className='map-controls';let liveMap=null;btn(controls,'＋ 확대',()=>{if(liveMap){liveMap.zoomIn();return;}zoom=Math.min(3,zoom+.5);drawMarkers();});btn(controls,'− 축소',()=>{if(liveMap){liveMap.zoomOut();return;}zoom=Math.max(.5,zoom-.5);drawMarkers();});drawMarkers();mapCleanups.push(mountDirectoryMap(map,points,center,{keepCenter:true,showLocation:!!position,select:pick,ready:instance=>{liveMap=instance;markerHost.remove();notice.textContent='지도 © OpenStreetMap 기여자 · 예시 거점/전문가 · 개설 예정 위치는 지역 기준점';},failed:()=>{notice.textContent='지도 연결이 원활하지 않습니다. 임시 좌표·목록으로 선택할 수 있습니다.';}}));
  function showProfile(p){map.querySelector('.expert-sheet')?.remove();const sheet=el('article',undefined,map);sheet.className='card expert-sheet';sheet.dataset.expertId=p.id;btn(sheet,'카드 닫기',()=>sheet.remove()).className='sheet-close';el('small','개인 전문가 · 가상 인증완료 상태',sheet);el('h2',p.name,sheet);el('p',JOBS[p.profession]+' · '+p.organization,sheet);el('p',p.region+' · '+(p.distance==null?'거리 미확인':p.distance.toFixed(1)+'km')+' · '+(p.rating?'가상 평점 '+p.rating:'평점 없음'),sheet);el('p',p.specialties.map(x=>SITUATIONS[x]).join(' · ')||'기타 문의',sheet);if(p.pledge)pledge(sheet);btn(sheet,'이 전문가에게 상담 신청',()=>go('/claim?step=3'),true);}
  function showBranch(b){if(b.planned){map.querySelector('.expert-sheet')?.remove();const card=el('article',undefined,map);card.className='card expert-sheet';el('h2',b.name+' · 개설 예정',card);el('p',b.district+' 지역 기준 위치입니다. 실제 사무실 주소가 아니며 아직 예약할 수 없습니다.',card);btn(card,'카드 닫기',()=>card.remove());return;}map.querySelector('.expert-sheet')?.remove();const sheet=el('article',undefined,map);sheet.className='card expert-sheet branch-sheet';sheet.dataset.branchId=b.id;btn(sheet,'카드 닫기',()=>sheet.remove()).className='sheet-close';el('small','보험소 거점 · 가상 데이터',sheet);el('h2',b.name,sheet);el('p',b.address||b.district,sheet);el('p',b.district+' · '+(b.distance==null?'거리 미확인':b.distance.toFixed(1)+'km')+' · 소속 전문가 '+b.expert_count+'명',sheet);const badges=el('div',undefined,sheet);badges.className='branch-badges';el('span','영업 전화 없음',badges).className='chip';el('span','소비자보호 서약',badges).className='chip';btn(sheet,b.expert_count?'이 보험소 예약하기':'예약하기 · 전문가 배정 예정',()=>{draft.branch=b.id;keep();go('/claim?target=branch');},true);}
  if(!points.length)el('p',draft.mapView==='branch'?'이 지역은 보험소 거점 준비중입니다. ‘개인 전문가’ 또는 다른 지역을 선택해 보세요.':draft.mapView==='expert'?'이 지역에 노출 중인 개인 전문가가 없습니다. ‘보험소 거점’을 확인해 보세요.':'가까운 보험소·전문가가 아직 없습니다. 다른 지역을 선택해 주세요.',map).className='empty-map';
  else if(draft.branch&&branches.some(b=>b.id===draft.branch)&&draft.mapView!=='expert')showBranch(branches.find(b=>b.id===draft.branch));else if(draft.expert&&catalog.some(p=>p.id===draft.expert)&&draft.mapView!=='branch')showProfile(catalog.find(p=>p.id===draft.expert));
  const details=el('details',undefined,host);el('summary','지도 대신 목록으로 선택',details);if(draft.mapView!=='expert')branches.forEach(b=>btn(details,'🏠 '+b.name+(b.planned?' · 개설 예정':' · 전문가 '+b.expert_count+'명'),()=>{pick(b);map.scrollIntoView();}));if(draft.mapView!=='branch')catalog.forEach(p=>btn(details,p.name+' · '+JOBS[p.profession],()=>{pick(p);map.scrollIntoView();}));if(!onHome)btn(host,'이전 · 상황 선택',()=>go('/claim?step=1'));
}

async function sampleDocument(){const c=document.createElement('canvas');c.width=420;c.height=240;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='black';ctx.font='20px sans-serif';ctx.fillText('SAMPLE ONLY - NOT A REAL ID',15,50);ctx.fillText('FICTIONAL VERIFICATION DOCUMENT',15,95);ctx.fillRect(15,140,390,70);return new Promise(resolve=>c.toBlob(resolve,'image/png'));}
async function upload(kind,file,consent,masked){if(!consent||!masked)throw Error('수집·이용 동의와 개인정보 가림 확인이 필요합니다.');let processed=file;if(file.type!=='application/pdf')processed=await prepareDocument(new File([file],file.name||'sample.png',{type:file.type}));if(processed.size>4*1024*1024)throw Error('파일을 4MB 이하로 줄여 주세요.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>resolve(r.result.split(',')[1]);r.readAsDataURL(processed);});await command('upload',{kind,filename:processed.name||'sample.png',mime:processed.type,data,consent,masked});await updateState();}
function documents(parent,draft,save){el('p','서류 없이도 가입할 수 있습니다. 서류 제출 후 심사 승인이 되어야 지도에 노출됩니다.',parent);check(parent,'자격 검증 목적의 서류 수집·이용에 동의합니다.',draft.documentConsent,v=>{draft.documentConsent=v;save();});check(parent,'가상 자료이며 주민등록번호 뒷자리 등 불필요한 개인정보를 가렸습니다.',draft.masked,v=>{draft.masked=v;save();});el('small','실서류 업로드 금지 · JPG/PNG/PDF · 원본 10MB, 전송 4MB 이하 · 관리자만 열람',parent);
 for(const [kind,label]of [['identity','신분증 (마스킹)'],['qualification',draft.profession==='adjuster'?'손해사정사 자격증':'위촉증명서']]){const card=el('section',undefined,parent);card.className='card document-card';const doc=workspace.documents.find(d=>d.kind===kind);el('h3',(doc?'✓ ':'')+label,card);if(doc){el('p',doc.filename,card);btn(card,label+' 삭제',async()=>{await command('delete_document',{id:doc.id});await updateState();render();});}const input=labelInput(card,label+' 파일 첨부',kind,'','file');input.accept='image/png,image/jpeg,application/pdf';input.onchange=()=>run(async()=>{if(input.files[0]){await upload(kind,input.files[0],draft.documentConsent,draft.masked);render();}});btn(card,label+' 가상 서류 첨부',async()=>{await upload(kind,await sampleDocument(),draft.documentConsent,draft.masked);render();});}}
function profileFields(parent,draft,save){const role=select(parent,'직군',JOBS,draft.profession);role.onchange=()=>{draft.profession=role.value;save();};for(const [label,name]of [['이름','name'],['소속','organization'],['등록번호 (선택, 심사 시 필요)','registration']]){const input=labelInput(parent,label,name,draft[name]||'');input.oninput=()=>{draft[name]=input.value;save();};}const region=select(parent,'활동지역',Object.fromEntries(Object.keys(CENTERS).map(x=>[x,x])),draft.region||'마포구');region.onchange=()=>{draft.region=region.value;save();};const bio=labelInput(parent,'자기소개 (가상 내용만)','bio',draft.bio||'');bio.oninput=()=>{draft.bio=bio.value;save();};const group=el('fieldset',undefined,parent);el('legend','전문분야',group);for(const [key,text]of Object.entries(SITUATIONS))check(group,text,draft.specialties?.includes(key),v=>{draft.specialties=(draft.specialties||[]).filter(x=>x!==key);if(v)draft.specialties.push(key);save();});}
async function expert(){if(workspace.actor.role!=='expert'){title('전문가 테스트','가입부터 심사까지 체험하세요','손해사정사·설계사만 가입할 수 있습니다. 변호사는 초기 대상에서 제외됩니다.');btn(host,'새 가상 전문가 가입',()=>switchActor('new_expert','/expert'),true);btn(host,'내 가상 전문가로 전환',()=>switchActor('expert','/expert'));return;}
 const e=workspace.expert;if(e){title('내 전문가 프로필',e.name,STATUS[e.status]+' · 가상 테스트 계정');const stateCard=el('section',undefined,host);stateCard.className='card';stateCard.dataset.expertStatus=e.status;el('h2',STATUS[e.status],stateCard);el('p',e.status==='verified'?'인증완료 테스트 상태입니다. 제재가 없으면 소비자 지도에 노출됩니다.':'서류 올리면 노출됩니다. 제출 후 관리자 심사 승인이 필요합니다.',stateCard);if(e.reason)el('p','안내: '+e.reason,stateCard);if(e.sanction)el('p','제재: '+({warning:'경고',suspended:'노출정지',banned:'제명'}[e.sanction]),stateCard);
 const incoming=workspace.incoming||[];const inbox=el('section',undefined,host);el('h2','내게 들어온 상담 신청 · '+incoming.length+'건',inbox);el('p','소비자가 나를 직접 선택해 신청한 건입니다. 상태는 내가 직접 기록하며 자동 발송·정보 판매는 없습니다.',inbox).className='subcopy';if(!incoming.length)el('p',e.status==='verified'?'아직 신청이 없습니다. 소비자가 나를 선택하면 여기에 표시됩니다.':'인증완료 후 지도에 노출되면 신청을 받을 수 있습니다.',inbox);for(const r of incoming){const card=el('article',undefined,inbox);card.className='card intake-card';card.dataset.requestId=r.id;el('h3',SITUATIONS[r.situation]+' · '+METHODS[r.method],card);el('p','접수번호 '+r.id,card);el('p',kst(r.created_at)+' · 현재 상태: '+EXPERT_STATES[r.state],card);const status=select(card,'상담 진행 상태',EXPERT_STATES,r.state);btn(card,'상태 저장',async()=>{await command('request_state',{id:r.id,revision:r.revision,state:status.value});await updateState();render();},true);}
 const edit=el('details',undefined,host);el('summary','프로필 편집',edit);const draft={...e,specialties:[...e.specialties]};profileFields(edit,draft,()=>{});btn(edit,'프로필 저장',async()=>{await command('profile',{...draft,revision:e.revision});await updateState();render();},true);const docs=el('details',undefined,host);docs.open=e.status!=='verified';el('summary','자격 서류 제출·삭제',docs);const docDraft={...e,...readDraft('documents')};documents(docs,docDraft,()=>saveDraft('documents',docDraft));if(e.status!=='verified'&&e.status!=='pending')btn(host,'서류 심사 요청',async()=>{await command('submit_review',{revision:e.revision});await updateState();render();},true);if(e.status==='pending')el('p','심사중 · 승인 전에는 소비자 지도에 노출되지 않습니다.',host);const history=el('details',undefined,host);el('summary','심사·제재 이력',history);workspace.history.forEach(x=>el('p',kst(x.at)+' · '+x.action+(x.reason?' · '+x.reason:''),history));return;}
 const draft={step:1,profession:'',region:'마포구',specialties:[],agreements:[false,false,false],...readDraft('signup')};const save=()=>saveDraft('signup',draft);title(draft.step+' / 4 · 전문가 가입',['','직군을 선택해 주세요','본인 정보를 알려주세요','서류는 나중에 제출해도 됩니다','소비자와의 약속'][draft.step]);const form=el('section',undefined,host);form.className='card';
 if(draft.step===1){const group=el('div',undefined,form);group.className='choice-grid';for(const [key,label]of Object.entries(JOBS)){const b=btn(group,label,()=>{draft.profession=key;save();render();});b.className='card choice'+(draft.profession===key?' selected':'');}}
 if(draft.step===2){for(const [label,name]of [['이름','name'],['소속','organization']]){const input=labelInput(form,label,name,draft[name]||'');input.oninput=()=>{draft[name]=input.value;save();};}const phone=labelInput(form,'휴대폰 (문자 인증 OFF · 가상 번호)','phone','01000000000','tel');phone.readOnly=true;const region=select(form,'활동지역',Object.fromEntries(Object.keys(CENTERS).map(x=>[x,x])),draft.region);region.onchange=()=>{draft.region=region.value;save();};}
 if(draft.step===3){documents(form,draft,save);const input=labelInput(form,'등록번호 (없으면 나중에 입력)','registration',draft.registration||'');input.oninput=()=>{draft.registration=input.value;save();};}
 if(draft.step===4){let all;all=check(form,'소비자보호 서약 전체 동의',draft.agreements.every(Boolean),v=>{draft.agreements=[v,v,v];save();render();});PLEDGES.forEach((text,i)=>check(form,text,draft.agreements[i],v=>{draft.agreements[i]=v;save();all.checked=draft.agreements.every(Boolean);$('signupNext').disabled=!draft.agreements.every(Boolean);}));el('p','동의 시각·버전은 DB에 기록합니다. '+VERSION,form);}
 const footer=el('div',undefined,host);footer.className='wizard-footer';if(draft.step>1)btn(footer,'이전',()=>{draft.step--;save();render();});const next=btn(footer,draft.step===4?'가입 완료':draft.step===3?'서류 없이도 다음':'다음',async()=>{if(draft.step===1&&!draft.profession)throw Error('직군을 선택해 주세요.');if(draft.step===2&&((draft.name||'').trim().length<2||(draft.organization||'').trim().length<2))throw Error('이름과 소속을 2자 이상 입력해 주세요.');if(draft.step<4){draft.step++;save();render();return;}await command('register',{...draft,agreement_version:VERSION});await updateState();sessionStorage.removeItem(draftKey('signup'));host.replaceChildren();title('가입 완료','가입이 완료됐습니다.','현재 상태: 미인증 · 서류 올리면 노출됩니다. 관리자 승인 전에는 지도에 표시되지 않습니다.');btn(host,'내 상태·프로필 보기',()=>render(),true);},true);next.id='signupNext';next.disabled=draft.step===4&&!draft.agreements.every(Boolean);}
async function admin(ticket){if(workspace.actor.role!=='admin'){title('관리자','테스트 관리자 계정이 필요합니다');btn(host,'관리자 테스트 계정으로 전환',()=>switchActor('admin','/admin'),true);return;}title('관리자 업무','심사와 상담 접수','가상 자료만 처리합니다. ‘전달함’은 수기 기록이며 자동 발송하지 않습니다.');const data=await command('admin_list');if(ticket!==renderId)return;adminFingerprint=fingerprint(data);const menu=el('div',undefined,host);menu.className='admin-tabs';btn(menu,'전문가 심사',()=>$('expertReviews').scrollIntoView());btn(menu,'상담 접수',()=>$('intakeList').scrollIntoView());btn(menu,'목록 새로고침',()=>render());const reviews=el('section',undefined,host);reviews.id='expertReviews';el('h2','전문가 심사 · '+data.experts.length+'명',reviews);
 for(const e of data.experts){const card=el('article',undefined,reviews);card.className='card review-card';card.dataset.expertId=e.id;el('h3',e.name+' · '+JOBS[e.profession],card);el('p',e.region+' · '+kst(e.created_at)+' · '+STATUS[e.status],card);if(e.reason)el('p',e.reason,card);if(e.sanction)el('p','제재 '+({warning:'경고',suspended:'노출정지',banned:'제명'}[e.sanction]),card);const details=el('details',undefined,card);el('summary','서류·심사 상세',details);el('p','등록번호: '+(e.registration||'미입력')+' · '+e.organization,details);el('p','서약: '+e.pledge_version+' · '+kst(e.agreed_at),details);for(const doc of e.documents){const group=el('div',undefined,details);el('p',(doc.kind==='identity'?'신분증':'자격 서류')+' · '+doc.filename,group);btn(group,'서류 열람',async()=>{const blob=await command('document',{id:doc.id});const url=URL.createObjectURL(blob);urls.push(url);if(doc.mime.startsWith('image/')){group.querySelector('img')?.remove();const img=el('img',undefined,group);img.src=url;img.alt='가상 심사 서류';img.className='document-image';}else{const a=el('a','PDF 내려받기',group);a.href=url;a.download=doc.filename;}});}let verified=false;check(details,'가상 서류·등록정보를 확인했습니다. 실제 운영 승인이 아닙니다.',false,v=>verified=v);const reason=labelInput(details,'심사·제재 사유 (5자 이상)','reason','');
  if(e.status==='pending')for(const [decision,label]of [['verified','승인'],['needs_changes','보완 요청'],['rejected','거절']])btn(details,label,async()=>{await command('review',{id:e.id,revision:e.revision,decision,reason:reason.value,checked:verified});render();},decision==='verified');
  if(e.status==='verified'&&e.sanction!=='banned'){const decision=e.sanction==='suspended'?'banned':e.sanction==='warning'?'suspended':'warning';let until;if(decision==='suspended')until=labelInput(details,'노출정지 종료 (한국 시간)','until','','datetime-local');btn(details,{warning:'경고',suspended:'노출정지',banned:'제명'}[decision],async()=>{await command('sanction',{id:e.id,revision:e.revision,decision,reason:reason.value,until:until?.value?new Date(until.value+':00+09:00').toISOString():null});render();});}
  const history=el('details',undefined,details);el('summary','변경 이력',history);e.history.forEach(x=>el('p',kst(x.at)+' · '+x.action+' · '+x.reason,history));}
 const intake=el('section',undefined,host);intake.id='intakeList';el('h2','상담 접수 · '+data.requests.length+'건',intake);if(!data.requests.length)el('p','소비자 신청이 들어오면 여기에 표시됩니다.',intake);for(const r of data.requests){const card=el('article',undefined,intake);card.className='card intake-card';card.dataset.requestId=r.id;el('h3',r.expert_name+' · '+SITUATIONS[r.situation],card);el('p',METHODS[r.method]+' · '+kst(r.created_at),card);el('p','접수번호 '+r.id,card);const status=select(card,'접수 상태',RECEIPTS,r.state);btn(card,'접수 상태 저장',async()=>{await command('intake',{id:r.id,revision:r.revision,state:status.value});render();},true);}
 const branchSection=el('section',undefined,host);el('h2','보험소 거점 · '+(data.branches?.length||0)+'개소',branchSection);(data.branches||[]).forEach(b=>el('p','🏠 '+b.name+' · '+b.district+' · 소속 전문가 '+b.expert_count+'명',branchSection));
 const bookingSection=el('section',undefined,host);bookingSection.id='bookingList';el('h2','거점 예약 현황 · '+(data.bookings?.length||0)+'건',bookingSection);el('p','거점이 직접 처리합니다. 관리자는 현황만 확인합니다.',bookingSection).className='subcopy';if(!data.bookings?.length)el('p','거점 예약이 들어오면 여기에 표시됩니다.',bookingSection);for(const b of (data.bookings||[])){const card=el('article',undefined,bookingSection);card.className='card intake-card';card.dataset.bookingId=b.id;el('h3',(b.branch_name||'거점')+' · '+SITUATIONS[b.situation],card);el('p',METHODS[b.method]+' · '+kst(b.created_at),card);el('p','예약번호 '+b.id,card);el('p','상태: '+BOOKING_STATE[b.state]+(b.assigned_expert_name?' · 담당 '+b.assigned_expert_name:' · 배정 대기'),card);} await mountSupportAdmin(host,{command});
}
async function branchConsole(ticket){if(workspace.actor.role!=='branch'){title('보험소 거점','거점 운영자 테스트 계정이 필요합니다');btn(host,'거점 운영자로 전환',()=>switchActor('branch','/branch.html'),true);return;}
 const data=await command('branch_workspace');if(ticket!==renderId)return;title('보험소 거점 업무',data.branch.name,data.branch.district+' · 예약 '+data.bookings.length+'건 · 소속 전문가 '+data.experts.length+'명 · 자동 발송·정보 판매 없음');
 const verified=data.experts.filter(e=>e.status==='verified');const list=el('section',undefined,host);el('h2','예약 접수 · '+data.bookings.length+'건',list);if(!data.bookings.length)el('p','소비자 예약이 들어오면 여기에 표시됩니다.',list);
 for(const b of data.bookings){const card=el('article',undefined,list);card.className='card intake-card';card.dataset.bookingId=b.id;el('h3',SITUATIONS[b.situation]+' · '+METHODS[b.method],card);el('p',(b.name||'이름 미상')+' · '+(b.phone||'연락처 미상'),card);el('p',(b.preferred_date||'날짜 미정')+' '+(b.preferred_slot||'')+' · '+kst(b.created_at),card);el('p','예약번호 '+b.id,card);el('p','상태: '+BOOKING_STATE[b.state]+(b.assigned_expert_name?' · 담당 '+b.assigned_expert_name:''),card);
  if(b.state!=='completed'){const assign=select(card,'전문가 배정',Object.fromEntries([['','전문가 선택'],...verified.map(e=>[e.id,e.name+' · '+JOBS[e.profession]])]),b.assigned_expert||'');btn(card,'이 전문가 배정',async()=>{if(!assign.value)throw Error('배정할 전문가를 선택해 주세요.');await command('assign_expert',{id:b.id,revision:b.revision,expert:assign.value});render();},true);}
  const status=select(card,'예약 상태',BOOKING_STATE,b.state);btn(card,'상태 저장',async()=>{await command('booking_state',{id:b.id,revision:b.revision,state:status.value});render();});}
 const roster=el('details',undefined,host);el('summary','소속 전문가 ('+data.experts.length+'명)',roster);if(!data.experts.length)el('p','아직 등록된 전문가가 없습니다. 아래에서 소속 전문가를 등록하세요.',roster);data.experts.forEach(e=>el('p',e.name+' · '+JOBS[e.profession]+' · '+STATUS[e.status],roster));
 const reg=el('details',undefined,host);el('summary','소속 전문가 등록',reg);el('p','우리 거점 소속 전문가를 등록합니다. 등록 즉시 인증완료로 소비자 지도·배정에 노출됩니다. 가상 정보만 입력하세요.',reg).className='subcopy';const rd=readDraft('branchExpert');const form=el('section',undefined,reg);form.className='card';const prof=select(form,'직군',JOBS,rd.profession);prof.onchange=()=>{rd.profession=prof.value;saveDraft('branchExpert',rd);};const nm=labelInput(form,'이름','name',rd.name||'');nm.oninput=()=>{rd.name=nm.value;saveDraft('branchExpert',rd);};const org=labelInput(form,'소속 (비우면 거점명)','organization',rd.organization||'');org.oninput=()=>{rd.organization=org.value;saveDraft('branchExpert',rd);};const regno=labelInput(form,'등록번호 (선택)','registration',rd.registration||'');regno.oninput=()=>{rd.registration=regno.value;saveDraft('branchExpert',rd);};const specs=new Set(rd.specialties||[]);const group=el('fieldset',undefined,form);el('legend','전문분야',group);for(const [k,text]of Object.entries(SITUATIONS))check(group,text,specs.has(k),v=>{if(v)specs.add(k);else specs.delete(k);rd.specialties=[...specs];saveDraft('branchExpert',rd);});btn(reg,'전문가 등록',async()=>{if((nm.value||'').trim().length<2)throw Error('이름을 2자 이상 입력해 주세요.');await command('branch_register_expert',{profession:prof.value,name:nm.value,organization:org.value,registration:regno.value,specialties:[...specs]});sessionStorage.removeItem(draftKey('branchExpert'));render();},true);
}
function myRequests(){title('내 신청','상담 접수 현황','실제 연락은 관리자 수기 확인 이후 진행합니다.');if(!workspace.requests.length&&!(workspace.bookings||[]).length)el('p','신청 내역이 없습니다.',host);for(const b of workspace.bookings||[]){const card=el('article',undefined,host);card.className='card';card.dataset.bookingId=b.id;el('h2',b.branch_name+' · 거점 예약',card);el('p',SITUATIONS[b.situation]+' · '+METHODS[b.method],card);el('p','희망 일정: '+(b.preferred_date||'미정')+' '+b.preferred_slot,card);el('p','상태: '+BOOKING_STATE[b.state],card);el('p',b.assigned_expert_name?'담당 전문가: '+b.assigned_expert_name:'담당 전문가 배정 대기',card);el('p',kst(b.created_at)+' · '+b.id,card);}for(const r of workspace.requests){const card=el('article',undefined,host);card.className='card';card.dataset.requestId=r.id;el('h2',r.expert_name,card);el('p',SITUATIONS[r.situation]+' · '+METHODS[r.method],card);el('p','상태: '+RECEIPTS[r.state],card);el('p',kst(r.created_at)+' · '+r.id,card);}btn(host,'보험금 청구 도움받기',()=>go('/claim?step=1'),true);}
async function render(){const ticket=++renderId;mapCleanups.splice(0).forEach(cleanup=>cleanup());urls.splice(0).forEach(URL.revokeObjectURL);host.replaceChildren();$('globalMessage').textContent='';host.classList.toggle('map-mode',routeName()==='claim');host.classList.toggle('home-mode',routeName()==='home');try{await updateState();if(ticket!==renderId)return;support.syncActor(workspace.actor);roleNavigation();const name=routeName();if(name==='home')await home(ticket);else if(name==='claim')await claim(ticket);else if(name==='expert')await expert();else if(name==='branch')await branchConsole(ticket);else if(name==='admin')await admin(ticket);else myRequests();}catch(e){$('globalMessage').textContent=e.message;}}
const support=createSupport({command,navigate(kind,situation){if(kind==='map'){go('/#nearbyExperts');return;}if(situation){const d=readDraft('claim');d.situation=situation;d.expert=null;d.branch=null;d.receipt=null;d.professionFilter='';d.specialtyFilter='';d.requestKey=crypto.randomUUID();saveDraft('claim',d);go('/claim?step=2');}else go('/claim?step=1');}});
$('switchAccount').onclick=chooseAccounts;document.addEventListener('click',e=>{const a=e.target.closest('.flow-header a,.development-panel a');if(!a)return;e.preventDefault();if(a.getAttribute('href')==='/#nearbyExperts'&&routeName()==='home'){$('nearbyExperts').scrollIntoView({behavior:'smooth'});return;}go(a.getAttribute('href'));});window.onpopstate=()=>render();await render();
setInterval(async()=>{if(document.hidden||busy)return;const name=routeName();try{if(name==='home'||name==='claim'&&Number(new URLSearchParams(location.search).get('step'))===2){const draft=readDraft('claim'),newList=(await command('catalog',position?{}:{region:draft.region||'마포구'})).filter(p=>(!draft.professionFilter||p.profession===draft.professionFilter)&&(!draft.specialtyFilter||p.specialties.includes(draft.specialtyFilter)));if(JSON.stringify(newList.map(p=>[p.id,p.name,p.pledge]))!==JSON.stringify(catalog.map(p=>[p.id,p.name,p.pledge]).sort((a,b)=>a[1].localeCompare(b[1])))){const oldIds=catalog.map(p=>p.id+String(p.pledge)+p.name).sort().join(),newIds=newList.map(p=>p.id+String(p.pledge)+p.name).sort().join();if(oldIds!==newIds)render();}}else if(name==='admin'&&workspace.actor.role==='admin'&&!host.querySelector('details[open],input:focus,textarea:focus,select:focus')){const fresh=await command('admin_list');if(fingerprint(fresh)!==adminFingerprint)render();}else if(name==='requests'){const prev=JSON.stringify([workspace.requests,workspace.bookings]);await updateState();if(prev!==JSON.stringify([workspace.requests,workspace.bookings]))render();}else if(name==='expert'&&workspace.expert&&!host.querySelector('input:focus,select:focus')){const sig=w=>w.expert.revision+':'+JSON.stringify((w.incoming||[]).map(r=>[r.id,r.revision]));const before=sig(workspace);await updateState();if(before!==sig(workspace))render();}}catch{}},2000);
