import {el,kst,sortedProfiles} from '../consultation-ui.js';import {prepareDocument} from '../expert-shared.js';
const $=id=>document.getElementById(id),host=$('app');
const VERSION='consumer-protection-2026-09-26-v2';const PLEDGES=['청구·상담 지원 과정에서 소비자에게 부당하거나 사전 고지되지 않은 금전을 요구하지 않는다. (자격자가 사전에 서면 고지한 정당한 보수는 허용)','소비자가 먼저 요청하지 않는 한, 신규 보험 가입을 먼저 권유하지 않는다.','플랫폼 외부로 소비자를 유인해 위 규정을 회피하지 않는다.'];
const SITUATIONS={death:'사망·상속',cancer:'암·중대질병',denial:'청구 거절·삭감',disability:'후유장해',other:'기타'};const JOBS={adjuster:'손해사정사',planner:'설계사'};const STATUS={unverified:'미인증',pending:'심사중',needs_changes:'보완 요청',rejected:'거절',verified:'인증완료'};const METHODS={office:'보험소로 방문',visit:'전문가가 와주세요',remote:'전화·메시지'};const RECEIPTS={new:'신규',delivered:'전달함',completed:'완료'};
const CENTERS={'마포구':{lat:37.555,lng:126.93},'송파구':{lat:37.514,lng:127.106},'분당구':{lat:37.382,lng:127.119}};
let state,workspace,catalog=[],position=null,busy=false,renderId=0;const urls=[];
const routeName=()=>{const p=location.pathname;return ['/','/index.html'].includes(p)?'home':/admin/.test(p)?'admin':/expert|partner|signup|login|account/.test(p)?'expert':/requests|dashboard/.test(p)?'requests':'claim';};
const draftKey=kind=>'flow-'+kind+'-'+workspace.actor.id;const readDraft=kind=>{try{return JSON.parse(sessionStorage.getItem(draftKey(kind)))||{};}catch{return {};}};const saveDraft=(kind,value)=>sessionStorage.setItem(draftKey(kind),JSON.stringify(value));
async function command(operation,payload={}){const response=await fetch('/api/test-flow/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,payload})});if(operation==='document'&&response.ok)return response.blob();const data=await response.json();if(!response.ok)throw Error(data.error);return data;}
async function updateState(){const r=await fetch('/api/test-flow/state',{cache:'no-store'});if(!r.ok)throw Error('비공개 테스트 서버에서 실행해 주세요.');state=await r.json();workspace=state.workspace;$('backendState').textContent=state.backend==='supabase-test'?'Supabase 테스트 DB 연결':'로컬 PostgreSQL 저장 · Supabase 원격 미연결';$('actorName').textContent=workspace.actor.name+' · '+({customer:'소비자',expert:'전문가',admin:'관리자'}[workspace.actor.role]);}
function go(path){history.pushState(null,'',path);render();}
async function switchActor(actor,target){const r=await fetch('/api/test-flow/switch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor})});if(!r.ok)throw Error('계정 전환 실패');await updateState();go(target);}
function btn(parent,text,fn,primary=false){const b=el('button',text,parent);b.type='button';b.className='btn '+(primary?'':'ghost');b.onclick=()=>run(()=>fn(b));return b;}
async function run(fn){if(busy)return;busy=true;$('globalMessage').textContent='';try{await fn();}catch(e){$('globalMessage').textContent=e.message;}finally{busy=false;}}
function labelInput(parent,label,name,value='',type='text'){const l=el('label',label,parent);l.className='field';const input=el('input',undefined,l);input.name=name;input.type=type;input.value=value;input.maxLength=120;return input;}
function select(parent,label,items,value){const l=el('label',label,parent);l.className='field';const s=el('select',undefined,l);for(const [key,text]of Object.entries(items)){const o=el('option',text,s);o.value=key;}s.value=value||Object.keys(items)[0];return s;}
function check(parent,label,value,fn){const l=el('label',undefined,parent);l.className='check-row';const c=el('input',undefined,l);c.type='checkbox';c.checked=!!value;l.append(document.createTextNode(label));c.onchange=()=>fn(c.checked);return c;}
function title(kicker,text,description){el('p',kicker,host).className='eyebrow';el('h1',text,host);if(description)el('p',description,host).className='subcopy';}
function dialog(titleText,body){const d=el('dialog',undefined,document.body);d.className='card flow-dialog';el('h2',titleText,d);body(d);btn(d,'닫기',()=>d.close());d.onclose=()=>d.remove();d.showModal();}
function pledge(parent){const b=btn(parent,'소비자보호 서약',()=>dialog('소비자보호 서약',d=>{const list=el('ol',undefined,d);PLEDGES.forEach(x=>el('li',x,list));el('p','동의 사실의 표시이며 실제 자격·결과를 보증하지 않습니다. 가상 전문가입니다.',d);}));b.className='pledge-badge';}
function chooseAccounts(){dialog('가상 계정으로 전환',d=>{el('p','실제 로그인·권한 승인이 아닙니다. 테스트 역할을 선택하세요.',d);for(const [role,label,target]of [['customer','소비자','/'],['expert','내 가상 전문가','/expert'],['new_expert','새 가상 전문가 만들기','/expert'],['admin','테스트 관리자','/admin']])btn(d,label,async()=>{d.close();await switchActor(role,target);});});}
function home(){title('우리곁에 보험소','예방은 보건소에서, 보험금 청구는 보험소에서.','보험이 막막할 때, 가까운 전문가가 바로 곁에.');const hero=el('section',undefined,host);hero.className='card home-hero';el('h2','정보보다 사람이 필요한 순간',hero);el('p','보험소로 오셔도, 전문가가 찾아가도 됩니다.',hero);btn(hero,'보험금 청구 도움받기',async()=>{if(workspace.actor.role!=='customer')await switchActor('customer','/claim?step=1');else go('/claim?step=1');},true);el('p','소비자 이용 무료 · 보험 가입 의무 없음',hero);const links=el('div',undefined,host);links.className='home-grid';btn(links,'전문가 가입·내 프로필',()=>go('/expert'));btn(links,'관리자 심사·접수',()=>go('/admin'));btn(links,'내 상담 신청 확인',()=>go('/requests.html'));btn(links,'보장분석 받기',()=>{const d=readDraft('claim');d.situation='other';d.analysis=true;saveDraft('claim',d);go('/claim?step=2');});el('p','보장분석은 전문가 상담으로 진행합니다. AI 자동 분석·상품 추천 기능은 제공하지 않습니다.',host).className='quiet';}
async function claim(ticket){if(workspace.actor.role!=='customer'){title('소비자 상담','소비자 테스트 계정으로 체험하세요');btn(host,'소비자로 전환',()=>switchActor('customer','/claim?step=1'),true);return;}const draft={region:'마포구',...readDraft('claim')};let step=Number(new URLSearchParams(location.search).get('step')||1);if(step>1&&!draft.situation)step=1;if(step===3&&!draft.expert)step=2;const progress=el('p',['','1 / 4 · 상황 선택','2 / 4 · 전문가 선택','3 / 4 · 상담 방식','4 / 4 · 접수 완료'][step]||'',host);progress.className='step-progress';const keep=()=>saveDraft('claim',draft);
 if(step===1){title('상담 시작','어떤 도움이 필요하세요?','상세한 병력이나 민감정보를 적을 필요가 없습니다.');const grid=el('div',undefined,host);grid.className='choice-grid';for(const [key,text]of Object.entries(SITUATIONS)){const b=btn(grid,text,()=>{draft.situation=key;draft.requestKey=crypto.randomUUID();keep();go('/claim?step=2');});b.className='card choice'+(draft.situation===key?' selected':'');}btn(host,'이전 · 홈',()=>go('/'));return;}
 if(step===2){title(SITUATIONS[draft.situation],'가까운 전문가를 직접 선택하세요','인증완료 가상 전문가만 표시됩니다.');const toolbar=el('div',undefined,host);toolbar.className='map-toolbar';const region=select(toolbar,'활동 지역',Object.fromEntries(Object.keys(CENTERS).map(x=>[x,x])),draft.region);region.onchange=()=>{draft.region=region.value;draft.expert=null;position=null;keep();render();};btn(toolbar,'내 위치 사용',async()=>{if(!navigator.geolocation)throw Error('지역을 직접 선택해 주세요.');navigator.geolocation.getCurrentPosition(p=>{position={lat:p.coords.latitude,lng:p.coords.longitude};render();},()=>{$('globalMessage').textContent='위치를 사용하지 않고 선택한 지역으로 계속할 수 있습니다.';},{timeout:8000});});
  const list=await command('catalog',{region:draft.region});if(ticket!==renderId)return;catalog=sortedProfiles(list,position||CENTERS[draft.region],draft.situation);const notice=el('p','카카오맵 키 미연결 · 임시 좌표 지도입니다. 실제 도로·길찾기를 제공하지 않습니다.',host);notice.className='map-notice';const map=el('section',undefined,host);map.className='test-map';map.setAttribute('aria-label','임시 지도');el('span',draft.region+' · 가상 기준 위치',map).className='map-label';const markerHost=el('div',undefined,map);markerHost.className='markers';let zoom=1;
  const drawMarkers=()=>{markerHost.replaceChildren();catalog.forEach((p,index)=>{const b=btn(markerHost,(p.profession==='adjuster'?'손해':'설계')+' · '+p.name,()=>{draft.expert=p.id;draft.requestKey=crypto.randomUUID();keep();showProfile(p);});b.className='map-marker';b.dataset.expertId=p.id;const center=CENTERS[draft.region];b.style.left=Math.max(15,Math.min(70,40+(p.longitude-center.lng)*1000*zoom+(index%3)*7))+'%';b.style.top=Math.max(18,Math.min(48,25-(p.latitude-center.lat)*800*zoom+(index%2)*12))+'%';});};const controls=el('div',undefined,map);controls.className='map-controls';btn(controls,'＋ 확대',()=>{zoom=Math.min(3,zoom+.5);drawMarkers();});btn(controls,'− 축소',()=>{zoom=Math.max(.5,zoom-.5);drawMarkers();});drawMarkers();
  function showProfile(p){map.querySelector('.expert-sheet')?.remove();const sheet=el('article',undefined,map);sheet.className='card expert-sheet';sheet.dataset.expertId=p.id;btn(sheet,'카드 닫기',()=>sheet.remove()).className='sheet-close';el('small','가상 데이터 · 인증완료 테스트 상태',sheet);el('h2',p.name,sheet);el('p',JOBS[p.profession]+' · '+p.organization,sheet);el('p',p.region+' · '+(p.distance===null?'거리 미확인':p.distance.toFixed(1)+'km')+' · '+(p.rating?'가상 평점 '+p.rating:'평점 없음'),sheet);el('p',p.specialties.map(x=>SITUATIONS[x]).join(' · ')||'기타 문의',sheet);if(p.pledge)pledge(sheet);btn(sheet,'이 전문가 선택 · 다음',()=>go('/claim?step=3'),true);}
  if(!catalog.length)el('p','개설 예정 · 인증완료 전문가가 없습니다.',map).className='empty-map';else if(draft.expert&&catalog.some(p=>p.id===draft.expert))showProfile(catalog.find(p=>p.id===draft.expert));const details=el('details',undefined,host);el('summary','지도 대신 목록으로 선택',details);catalog.forEach(p=>btn(details,p.name+' · '+JOBS[p.profession],()=>{draft.expert=p.id;keep();showProfile(p);map.scrollIntoView();}));btn(host,'이전 · 상황 선택',()=>go('/claim?step=1'));return;
 }
 if(step===3){const experts=await command('catalog',{});if(ticket!==renderId)return;const expert=experts.find(p=>p.id===draft.expert);if(!expert){el('p','선택한 전문가가 현재 노출되지 않습니다. 다른 전문가를 선택해 주세요.',host);btn(host,'지도에서 다시 선택',()=>go('/claim?step=2'));return;}title('상담 방식','어떤 방식이 편하세요?',expert.name+' · '+SITUATIONS[draft.situation]);const grid=el('div',undefined,host);grid.className='choice-grid';for(const [key,text]of Object.entries(METHODS)){const b=btn(grid,text,()=>{draft.method=key;draft.requestKey=crypto.randomUUID();keep();render();});b.className='card choice'+(draft.method===key?' selected':'');b.setAttribute('aria-pressed',String(draft.method===key));}let consent=!!draft.consent;const send=btn(host,'상담 신청 완료',async b=>{b.disabled=true;try{if(!consent||!draft.method)throw Error('방식과 접수 동의를 확인해 주세요.');draft.requestKey ||= crypto.randomUUID();keep();const r=await command('request',{expert:draft.expert,situation:draft.situation,method:draft.method,consent:true,request_key:draft.requestKey});draft.receipt=r.id;keep();go('/claim?step=4');}finally{b.disabled=false;}},true);const row=check(host,'선택한 전문가 상담을 위해 관리자에게 접수합니다. 대표가 수기로 전달하며 자동 발송하지 않습니다.',consent,v=>{consent=v;draft.consent=v;keep();send.disabled=!v||!draft.method;});host.insertBefore(row.parentElement,send);send.disabled=!consent||!draft.method;el('p','소비자 이용 무료 · 보험 가입 의무 없음 · 건강정보를 입력하지 마세요.',host);btn(host,'이전 · 전문가 선택',()=>go('/claim?step=2'));return;}
 await updateState();if(ticket!==renderId)return;const receipt=workspace.requests.find(r=>r.id===draft.receipt);if(!receipt){go('/requests.html');return;}title('접수 완료','상담 신청이 접수됐습니다.','관리자가 확인 후 선택한 전문가에게 수기로 전달합니다.');const box=el('section',undefined,host);box.className='card';el('p',receipt.expert_name+' · '+METHODS[receipt.method],box);el('p','접수번호 '+receipt.id,box);el('p','상태: '+RECEIPTS[receipt.state],box);btn(host,'내 신청 확인',()=>go('/requests.html'),true);btn(host,'홈으로',()=>go('/'));
}
async function sampleDocument(){const c=document.createElement('canvas');c.width=420;c.height=240;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='black';ctx.font='20px sans-serif';ctx.fillText('SAMPLE ONLY - NOT A REAL ID',15,50);ctx.fillText('FICTIONAL VERIFICATION DOCUMENT',15,95);ctx.fillRect(15,140,390,70);return new Promise(resolve=>c.toBlob(resolve,'image/png'));}
async function upload(kind,file,consent,masked){if(!consent||!masked)throw Error('수집·이용 동의와 개인정보 가림 확인이 필요합니다.');let processed=file;if(file.type!=='application/pdf')processed=await prepareDocument(new File([file],file.name||'sample.png',{type:file.type}));if(processed.size>4*1024*1024)throw Error('파일을 4MB 이하로 줄여 주세요.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>resolve(r.result.split(',')[1]);r.readAsDataURL(processed);});await command('upload',{kind,filename:processed.name||'sample.png',mime:processed.type,data,consent,masked});await updateState();}
function documents(parent,draft,save){el('p','서류 없이도 가입할 수 있습니다. 서류 제출 후 심사 승인이 되어야 지도에 노출됩니다.',parent);check(parent,'자격 검증 목적의 서류 수집·이용에 동의합니다.',draft.documentConsent,v=>{draft.documentConsent=v;save();});check(parent,'가상 자료이며 주민등록번호 뒷자리 등 불필요한 개인정보를 가렸습니다.',draft.masked,v=>{draft.masked=v;save();});el('small','실서류 업로드 금지 · JPG/PNG/PDF · 원본 10MB, 전송 4MB 이하 · 관리자만 열람',parent);
 for(const [kind,label]of [['identity','신분증 (마스킹)'],['qualification',draft.profession==='adjuster'?'손해사정사 자격증':'위촉증명서']]){const card=el('section',undefined,parent);card.className='card document-card';const doc=workspace.documents.find(d=>d.kind===kind);el('h3',(doc?'✓ ':'')+label,card);if(doc){el('p',doc.filename,card);btn(card,label+' 삭제',async()=>{await command('delete_document',{id:doc.id});await updateState();render();});}const input=labelInput(card,label+' 파일 첨부',kind,'','file');input.accept='image/png,image/jpeg,application/pdf';input.onchange=()=>run(async()=>{if(input.files[0]){await upload(kind,input.files[0],draft.documentConsent,draft.masked);render();}});btn(card,label+' 가상 서류 첨부',async()=>{await upload(kind,await sampleDocument(),draft.documentConsent,draft.masked);render();});}}
function profileFields(parent,draft,save){const role=select(parent,'직군',JOBS,draft.profession);role.onchange=()=>{draft.profession=role.value;save();};for(const [label,name]of [['이름','name'],['소속','organization'],['등록번호 (선택, 심사 시 필요)','registration']]){const input=labelInput(parent,label,name,draft[name]||'');input.oninput=()=>{draft[name]=input.value;save();};}const region=select(parent,'활동지역',Object.fromEntries(Object.keys(CENTERS).map(x=>[x,x])),draft.region||'마포구');region.onchange=()=>{draft.region=region.value;save();};const bio=labelInput(parent,'자기소개 (가상 내용만)','bio',draft.bio||'');bio.oninput=()=>{draft.bio=bio.value;save();};const group=el('fieldset',undefined,parent);el('legend','전문분야',group);for(const [key,text]of Object.entries(SITUATIONS))check(group,text,draft.specialties?.includes(key),v=>{draft.specialties=(draft.specialties||[]).filter(x=>x!==key);if(v)draft.specialties.push(key);save();});}
async function expert(){if(workspace.actor.role!=='expert'){title('전문가 테스트','가입부터 심사까지 체험하세요','손해사정사·설계사만 가입할 수 있습니다. 변호사는 초기 대상에서 제외됩니다.');btn(host,'새 가상 전문가 가입',()=>switchActor('new_expert','/expert'),true);btn(host,'내 가상 전문가로 전환',()=>switchActor('expert','/expert'));return;}
 const e=workspace.expert;if(e){title('내 전문가 프로필',e.name,STATUS[e.status]+' · 가상 테스트 계정');const stateCard=el('section',undefined,host);stateCard.className='card';stateCard.dataset.expertStatus=e.status;el('h2',STATUS[e.status],stateCard);el('p',e.status==='verified'?'인증완료 테스트 상태입니다. 제재가 없으면 소비자 지도에 노출됩니다.':'서류 올리면 노출됩니다. 제출 후 관리자 심사 승인이 필요합니다.',stateCard);if(e.reason)el('p','안내: '+e.reason,stateCard);if(e.sanction)el('p','제재: '+({warning:'경고',suspended:'노출정지',banned:'제명'}[e.sanction]),stateCard);const edit=el('details',undefined,host);el('summary','프로필 편집',edit);const draft={...e,specialties:[...e.specialties]};profileFields(edit,draft,()=>{});btn(edit,'프로필 저장',async()=>{await command('profile',{...draft,revision:e.revision});await updateState();render();},true);const docs=el('details',undefined,host);docs.open=e.status!=='verified';el('summary','자격 서류 제출·삭제',docs);const docDraft={...e,...readDraft('documents')};documents(docs,docDraft,()=>saveDraft('documents',docDraft));if(e.status!=='verified'&&e.status!=='pending')btn(host,'서류 심사 요청',async()=>{await command('submit_review',{revision:e.revision});await updateState();render();},true);if(e.status==='pending')el('p','심사중 · 승인 전에는 소비자 지도에 노출되지 않습니다.',host);const history=el('details',undefined,host);el('summary','심사·제재 이력',history);workspace.history.forEach(x=>el('p',kst(x.at)+' · '+x.action+(x.reason?' · '+x.reason:''),history));return;}
 const draft={step:1,profession:'',region:'마포구',specialties:[],agreements:[false,false,false],...readDraft('signup')};const save=()=>saveDraft('signup',draft);title(draft.step+' / 4 · 전문가 가입',['','직군을 선택해 주세요','본인 정보를 알려주세요','서류는 나중에 제출해도 됩니다','소비자와의 약속'][draft.step]);const form=el('section',undefined,host);form.className='card';
 if(draft.step===1){const group=el('div',undefined,form);group.className='choice-grid';for(const [key,label]of Object.entries(JOBS)){const b=btn(group,label,()=>{draft.profession=key;save();render();});b.className='card choice'+(draft.profession===key?' selected':'');}}
 if(draft.step===2){for(const [label,name]of [['이름','name'],['소속','organization']]){const input=labelInput(form,label,name,draft[name]||'');input.oninput=()=>{draft[name]=input.value;save();};}const phone=labelInput(form,'휴대폰 (문자 인증 OFF · 가상 번호)','phone','01000000000','tel');phone.readOnly=true;const region=select(form,'활동지역',Object.fromEntries(Object.keys(CENTERS).map(x=>[x,x])),draft.region);region.onchange=()=>{draft.region=region.value;save();};}
 if(draft.step===3){documents(form,draft,save);const input=labelInput(form,'등록번호 (없으면 나중에 입력)','registration',draft.registration||'');input.oninput=()=>{draft.registration=input.value;save();};}
 if(draft.step===4){let all;all=check(form,'소비자보호 서약 전체 동의',draft.agreements.every(Boolean),v=>{draft.agreements=[v,v,v];save();render();});PLEDGES.forEach((text,i)=>check(form,text,draft.agreements[i],v=>{draft.agreements[i]=v;save();all.checked=draft.agreements.every(Boolean);$('signupNext').disabled=!draft.agreements.every(Boolean);}));el('p','동의 시각·버전은 DB에 기록합니다. '+VERSION,form);}
 const footer=el('div',undefined,host);footer.className='wizard-footer';if(draft.step>1)btn(footer,'이전',()=>{draft.step--;save();render();});const next=btn(footer,draft.step===4?'가입 완료':draft.step===3?'서류 없이도 다음':'다음',async()=>{if(draft.step===1&&!draft.profession)throw Error('직군을 선택해 주세요.');if(draft.step===2&&((draft.name||'').trim().length<2||(draft.organization||'').trim().length<2))throw Error('이름과 소속을 2자 이상 입력해 주세요.');if(draft.step<4){draft.step++;save();render();return;}await command('register',{...draft,agreement_version:VERSION});await updateState();sessionStorage.removeItem(draftKey('signup'));host.replaceChildren();title('가입 완료','가입이 완료됐습니다.','현재 상태: 미인증 · 서류 올리면 노출됩니다. 관리자 승인 전에는 지도에 표시되지 않습니다.');btn(host,'내 상태·프로필 보기',()=>render(),true);},true);next.id='signupNext';next.disabled=draft.step===4&&!draft.agreements.every(Boolean);}
async function admin(ticket){if(workspace.actor.role!=='admin'){title('관리자','테스트 관리자 계정이 필요합니다');btn(host,'관리자 테스트 계정으로 전환',()=>switchActor('admin','/admin'),true);return;}title('관리자 업무','심사와 상담 접수','가상 자료만 처리합니다. ‘전달함’은 수기 기록이며 자동 발송하지 않습니다.');const data=await command('admin_list');if(ticket!==renderId)return;const menu=el('div',undefined,host);menu.className='admin-tabs';btn(menu,'전문가 심사',()=>$('expertReviews').scrollIntoView());btn(menu,'상담 접수',()=>$('intakeList').scrollIntoView());btn(menu,'목록 새로고침',()=>render());const reviews=el('section',undefined,host);reviews.id='expertReviews';el('h2','전문가 심사 · '+data.experts.length+'명',reviews);
 for(const e of data.experts){const card=el('article',undefined,reviews);card.className='card review-card';card.dataset.expertId=e.id;el('h3',e.name+' · '+JOBS[e.profession],card);el('p',e.region+' · '+kst(e.created_at)+' · '+STATUS[e.status],card);if(e.reason)el('p',e.reason,card);if(e.sanction)el('p','제재 '+({warning:'경고',suspended:'노출정지',banned:'제명'}[e.sanction]),card);const details=el('details',undefined,card);el('summary','서류·심사 상세',details);el('p','등록번호: '+(e.registration||'미입력')+' · '+e.organization,details);el('p','서약: '+e.pledge_version+' · '+kst(e.agreed_at),details);for(const doc of e.documents){const group=el('div',undefined,details);el('p',(doc.kind==='identity'?'신분증':'자격 서류')+' · '+doc.filename,group);btn(group,'서류 열람',async()=>{const blob=await command('document',{id:doc.id});const url=URL.createObjectURL(blob);urls.push(url);if(doc.mime.startsWith('image/')){group.querySelector('img')?.remove();const img=el('img',undefined,group);img.src=url;img.alt='가상 심사 서류';img.className='document-image';}else{const a=el('a','PDF 내려받기',group);a.href=url;a.download=doc.filename;}});}let verified=false;check(details,'가상 서류·등록정보를 확인했습니다. 실제 운영 승인이 아닙니다.',false,v=>verified=v);const reason=labelInput(details,'심사·제재 사유 (5자 이상)','reason','');
  if(e.status==='pending')for(const [decision,label]of [['verified','승인'],['needs_changes','보완 요청'],['rejected','거절']])btn(details,label,async()=>{await command('review',{id:e.id,revision:e.revision,decision,reason:reason.value,checked:verified});render();},decision==='verified');
  if(e.status==='verified'&&e.sanction!=='banned'){const decision=e.sanction==='suspended'?'banned':e.sanction==='warning'?'suspended':'warning';let until;if(decision==='suspended')until=labelInput(details,'노출정지 종료 (한국 시간)','until','','datetime-local');btn(details,{warning:'경고',suspended:'노출정지',banned:'제명'}[decision],async()=>{await command('sanction',{id:e.id,revision:e.revision,decision,reason:reason.value,until:until?.value?new Date(until.value+':00+09:00').toISOString():null});render();});}
  const history=el('details',undefined,details);el('summary','변경 이력',history);e.history.forEach(x=>el('p',kst(x.at)+' · '+x.action+' · '+x.reason,history));}
 const intake=el('section',undefined,host);intake.id='intakeList';el('h2','상담 접수 · '+data.requests.length+'건',intake);if(!data.requests.length)el('p','소비자 신청이 들어오면 여기에 표시됩니다.',intake);for(const r of data.requests){const card=el('article',undefined,intake);card.className='card intake-card';card.dataset.requestId=r.id;el('h3',r.expert_name+' · '+SITUATIONS[r.situation],card);el('p',METHODS[r.method]+' · '+kst(r.created_at),card);el('p','접수번호 '+r.id,card);const status=select(card,'접수 상태',RECEIPTS,r.state);btn(card,'접수 상태 저장',async()=>{await command('intake',{id:r.id,revision:r.revision,state:status.value});render();},true);}}
function myRequests(){title('내 신청','상담 접수 현황','실제 연락은 관리자 수기 확인 이후 진행합니다.');if(!workspace.requests.length)el('p','신청 내역이 없습니다.',host);for(const r of workspace.requests){const card=el('article',undefined,host);card.className='card';card.dataset.requestId=r.id;el('h2',r.expert_name,card);el('p',SITUATIONS[r.situation]+' · '+METHODS[r.method],card);el('p','상태: '+RECEIPTS[r.state],card);el('p',kst(r.created_at)+' · '+r.id,card);}btn(host,'보험금 청구 도움받기',()=>go('/claim?step=1'),true);}
async function render(){const ticket=++renderId;urls.splice(0).forEach(URL.revokeObjectURL);host.replaceChildren();$('globalMessage').textContent='';host.classList.toggle('map-mode',routeName()==='claim');try{await updateState();if(ticket!==renderId)return;const name=routeName();if(name==='home')home();else if(name==='claim')await claim(ticket);else if(name==='expert')await expert();else if(name==='admin')await admin(ticket);else myRequests();}catch(e){$('globalMessage').textContent=e.message;}}
$('switchAccount').onclick=chooseAccounts;document.querySelectorAll('.flow-header a').forEach(a=>a.onclick=e=>{e.preventDefault();go(a.getAttribute('href'));});window.onpopstate=()=>render();await render();
setInterval(async()=>{if(document.hidden||busy)return;const name=routeName();try{if(name==='claim'&&Number(new URLSearchParams(location.search).get('step'))===2){const draft=readDraft('claim'),newList=await command('catalog',{region:draft.region||'마포구'});if(JSON.stringify(newList.map(p=>[p.id,p.name,p.pledge]))!==JSON.stringify(catalog.map(p=>[p.id,p.name,p.pledge]).sort((a,b)=>a[1].localeCompare(b[1])))){const oldIds=catalog.map(p=>p.id+String(p.pledge)+p.name).sort().join(),newIds=newList.map(p=>p.id+String(p.pledge)+p.name).sort().join();if(oldIds!==newIds)render();}}else if(name==='requests'){const prev=JSON.stringify(workspace.requests);await updateState();if(prev!==JSON.stringify(workspace.requests))render();}else if(name==='expert'&&workspace.expert&&!host.querySelector('details[open] input:focus')){const before=workspace.expert.revision;await updateState();if(before!==workspace.expert.revision)render();}}catch{}},2000);
