import {el,kst} from '../consultation-ui.js';
const $=id=>document.getElementById(id);
async function api(path,{method='GET',body,token,confirmed}={}){const headers={};if(token)headers['X-Request-Token']=token;if(confirmed)headers['X-Mask-Confirmed']='true';if(body&&!(body instanceof Blob))headers['Content-Type']='application/json';const r=await fetch(path,{method,headers,body:body instanceof Blob?body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'처리하지 못했습니다.');return data;}
const signature={unknown:'⚠ 필요 여부 확인 중',required:'⚠ 자필서명 필요',original_required:'⚠ 종이 원본 확인 필요',confirmed:'✓ 후속 확인 완료',not_required:'해당 없음'};
const identity={requested:'신분증 사본 준비 요청',prepared:'✓ 신분증 사본 준비 (고객 확인)',deleted:'신분증 사본 삭제 · 재준비 필요'};
function button(host,label,fn){const b=el('button',label,host);b.type='button';b.className='btn ghost';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){let n=host.querySelector('[role=alert]');if(!n){n=el('p','',host);n.setAttribute('role','alert');}n.textContent=e.message;}finally{b.disabled=false;}};return b;}
async function planner(){let links=new Map(),key=crypto.randomUUID(),busy=false;const initial=await api('/api/pro/requests');for(const [id,rows]of [['customer',initial.customers],['hospital',initial.hospitals]]){const select=$(id);const empty=el('option','선택해 주세요',select);empty.value='';for(const row of rows){const o=el('option',row.name,select);o.value=row.id;}}for(const doc of initial.documents){const label=el('label',undefined,$('documents'));const check=el('input',undefined,label);check.type='checkbox';check.value=doc;label.append(document.createTextNode(doc));}
 function linkResult(data){if(data.token)links.set(data.request.id,location.origin+'/customer#'+data.token);}
 let previousRows='';function render(rows){const snapshot=JSON.stringify(rows);if(snapshot===previousRows)return;previousRows=snapshot;$('requests').replaceChildren();const active=rows.filter(r=>!r.cancelled&&!r.expired);if($('requestTotal')){$('requestTotal').textContent=rows.length+'건';$('waitingCount').textContent=active.filter(r=>r.identity!=='prepared').length;$('readyCount').textContent=active.filter(r=>r.identity==='prepared').length;$('followupCount').textContent=active.filter(r=>[r.mandate,r.consent].some(s=>!['confirmed','not_required'].includes(s))).length;}if(!rows.length){const empty=el('div',undefined,$('requests'));empty.className='card pro-empty';el('div','▤',empty).className='empty-icon';el('h3','첫 준비 요청을 시작해 보세요',empty);el('p','고객이 준비를 마치면 이곳에서\n바로 확인할 수 있습니다.',empty);}for(const r of rows){const card=el('article',undefined,$('requests'));card.className='card';card.dataset.requestId=r.id;el('h2',r.customer.name+' · '+r.hospital.name,card);el('p',r.documents.join(' · '),card);el('p',r.situation,card);el('p',r.cancelled?'요청 취소':r.expired?'링크 만료':identity[r.identity],card).className='pro-status';el('p','위임장: '+signature[r.mandate],card).className='pro-followup';el('p','동의서: '+signature[r.consent],card).className='pro-followup';el('p','문자 미발송 · 가상 링크만 생성 · 만료 '+kst(r.expiresAt),card);
  if(links.has(r.id)&&!r.cancelled&&!r.expired){const a=el('a','고객 화면 열기 (가상)',card);a.href=links.get(r.id);a.target='_blank';a.rel='noopener noreferrer';a.className='pro-link';}
  const change=async body=>{const result=await api('/api/pro/requests/'+r.id,{method:'POST',body:{...body,revision:r.revision}});linkResult(result);await refresh();};
  if(!r.cancelled){button(card,'링크 다시 만들기',()=>change({action:'renew'}));button(card,'요청 취소',()=>change({action:'cancel'}));if(r.identity==='prepared'&&!r.expired){const a=el('a','보호처리한 가상 사본 내려받기',card);a.href='/api/pro/requests/'+r.id+'/image';a.download='masked-copy.png';button(card,'가상 사본 삭제',()=>change({action:'delete_copy'}));}
   const details=el('details',undefined,card);el('summary','자필서명·종이 원본 후속 작업',details);el('p','전자위임장 인정 여부는 미확인입니다. 신분증 준비와 별도로 확인하세요.',details);
   for(const kind of ['mandate','consent']){const label=el('label',kind==='mandate'?'위임장 상태':'동의서 상태',details);const select=el('select',undefined,label);for(const [value,title]of Object.entries(signature)){const opt=el('option',title,select);opt.value=value;}select.value=r[kind];const reasonLabel=el('label','확인 근거 (가상 내용만, 5자 이상)',details);const reason=el('textarea',undefined,reasonLabel);reason.maxLength=300;button(details,(kind==='mandate'?'위임장':'동의서')+' 상태 저장',()=>change({action:'followup',kind,state:select.value,reason:reason.value}));}}
  const audit=el('details',undefined,card);el('summary','처리 이력',audit);const events={request_created:'준비 요청',copy_prepared:'고객 사본 준비 완료',request_cancelled:'요청 취소',link_renewed:'링크 재발급',copy_deleted:'사본 삭제',copy_expired:'보관시간 종료로 사본 삭제'};for(const e of r.history)el('p',kst(e.at)+' · '+(events[e.action]||e.action)+' · '+e.actor+(e.reason?' · '+e.reason:''),audit);
 }}
 async function refresh(){const result=await api('/api/pro/requests');render(result.requests);}
 $('requestForm').oninput=()=>{key=crypto.randomUUID();};$('requestForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('send').disabled=true;$('formMessage').textContent='';try{const result=await api('/api/pro/requests',{method:'POST',body:{customer:$('customer').value,hospital:$('hospital').value,documents:[...$('documents').querySelectorAll('input:checked')].map(c=>c.value),situation:$('situation').value,needConfirmed:$('needConfirmed').checked,mandate:$('mandate').value,consent:$('consent').value,requestKey:key}});linkResult(result);await refresh();$('formMessage').textContent='가상 링크를 준비했습니다. 아래 고객 화면을 열어 체험해 주세요. 실제 문자는 보내지 않았습니다.';$('requests').scrollIntoView({behavior:'smooth'});}catch(e){$('formMessage').textContent=e.message;}finally{busy=false;$('send').disabled=false;}};
 render(initial.requests);const events=new EventSource('/api/pro/events');events.onopen=()=>$('syncMessage').textContent='고객 준비 상태를 실시간으로 확인 중';events.onmessage=()=>refresh().catch(e=>$('syncMessage').textContent=e.message);events.onerror=()=>$('syncMessage').textContent='실시간 연결 재시도 중 · 상태를 주기적으로 다시 확인합니다.';const interval=setInterval(()=>refresh().catch(()=>{}),10000);window.addEventListener('pagehide',()=>{events.close();clearInterval(interval);});
}
async function customer(){let token=location.hash.slice(1);if(token){sessionStorage.setItem('pro-customer-token',token);history.replaceState(null,'',location.pathname);}else token=sessionStorage.getItem('pro-customer-token');let bitmap=null,masks=[],start=null,busy=false;
 const canvas=$('maskCanvas'),ctx=canvas.getContext('2d');const update=()=>{$('complete').disabled=busy||!bitmap||!masks.length||!$('maskConfirmed').checked;};
 function paint(extra){ctx.clearRect(0,0,canvas.width,canvas.height);if(bitmap)ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);ctx.fillStyle='#000';for(const r of [...masks,...(extra?[extra]:[])])ctx.fillRect(r.x,r.y,r.w,r.h);}
 function changed(){ $('maskConfirmed').checked=false;paint();update();}
 async function load(file,sample=false){if(busy)return;busy=true;update();try{if(file.size>10*1024*1024||!['image/png','image/jpeg'].includes(file.type))throw Error('10MB 이하 JPG·PNG 가상 이미지를 선택해 주세요.');const next=await createImageBitmap(file);if(next.width*next.height>40000000){next.close();throw Error('이미지 크기를 줄여 주세요.');}bitmap?.close();bitmap=next;const scale=Math.min(1,1600/Math.max(next.width,next.height));canvas.width=Math.round(next.width*scale);canvas.height=Math.round(next.height*scale);masks=sample?[{x:0,y:canvas.height*.45,w:canvas.width,h:canvas.height*.55}]:[];$('maskPanel').hidden=false;changed();$('maskPanel').scrollIntoView({behavior:'smooth'});}finally{busy=false;update();}}
 const point=e=>{const b=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-b.left)*canvas.width/b.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-b.top)*canvas.height/b.height))};};const rect=(a,b)=>({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)});
 canvas.onpointerdown=e=>{if(busy)return;start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(start)paint(rect(start,point(e)));};canvas.onpointerup=e=>{if(!start)return;const r=rect(start,point(e));start=null;if(r.w>=8&&r.h>=8)masks.push(r);changed();};canvas.onpointercancel=()=>{start=null;paint();};
 $('capture').onchange=async()=>{try{if($('capture').files[0])await load($('capture').files[0]);}catch(e){$('customerMessage').textContent=e.message;}};
 $('sample').onclick=async()=>{try{const c=document.createElement('canvas');c.width=640;c.height=400;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(0,0,640,400);g.fillStyle='black';g.font='26px sans-serif';g.fillText('SAMPLE ONLY - NOT A REAL ID',20,60);g.fillText('NAME: DEMO CUSTOMER',20,130);g.fillText('NUMBER: FICTIONAL DATA',20,240);g.fillText('ADDRESS: FICTIONAL DATA',20,320);await load(await new Promise(resolve=>c.toBlob(resolve,'image/png')),true);}catch(e){$('customerMessage').textContent=e.message;}};
 $('maskAll').onclick=()=>{masks=[{x:0,y:0,w:canvas.width,h:canvas.height}];changed();};$('resetMask').onclick=()=>{masks=[];changed();};$('maskConfirmed').onchange=update;
 function done(){bitmap?.close();bitmap=null;canvas.width=0;canvas.height=0;$('capture').value='';$('capturePanel').hidden=true;$('done').hidden=false;}
 $('complete').onclick=async()=>{if($('complete').disabled)return;busy=true;update();$('capture').disabled=$('sample').disabled=$('resetMask').disabled=$('maskAll').disabled=true;try{paint();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('이미지 처리를 다시 시도해 주세요.');await api('/api/customer/copy',{method:'POST',body:blob,token,confirmed:true});done();$('customerMessage').textContent='';}catch(e){$('customerMessage').textContent=e.message;}finally{busy=false;$('capture').disabled=$('sample').disabled=$('resetMask').disabled=$('maskAll').disabled=false;update();}};
 try{const data=await api('/api/customer/request',{token});$('hospitalName').textContent=data.hospital;data.documents.forEach(d=>el('li',d,$('documentList')));$('customerPanel').hidden=false;if(data.identity==='prepared')done();}catch(e){$('customerMessage').textContent=e.message;}
 window.addEventListener('pagehide',()=>{bitmap?.close();canvas.width=0;canvas.height=0;});
}
(document.body.dataset.pro==='planner'?planner():customer()).catch(e=>{const host=$('formMessage')||$('customerMessage');host.textContent=e.message;});
