import http from 'node:http';import path from 'node:path';import {randomBytes} from 'node:crypto';import {readFile,mkdir} from 'node:fs/promises';import {build} from 'esbuild';import {openTestDatabase,ACTORS} from '../src/test-flow/database.mjs';import {documentType,safeFilename} from '../netlify/functions/_shared/expert-documents.mjs';
export async function startTestFlow({port=3194,memory=false,dataDir,env=process.env}={}){
 await mkdir('artifacts',{recursive:true});await build({entryPoints:['src/test-flow/ui.js'],bundle:true,format:'esm',outfile:'artifacts/test-flow.js'});const db=await openTestDatabase({memory,dataDir,env});const sessions=new Map();const lastExperts=new Map();
 const errors={test_login_required:'테스트 계정을 선택해 주세요.',admin_required:'관리자 테스트 계정에서만 가능합니다.',expert_required:'전문가 테스트 계정을 선택해 주세요.',customer_required:'소비자 테스트 계정에서 신청해 주세요.',invalid_profile:'이름·소속·활동지역을 확인해 주세요.',invalid_registration:'등록번호 형식을 확인해 주세요. 주민번호를 입력하지 마세요.',pledge_required:'소비자보호 서약 3개에 모두 동의해 주세요.',document_consent_required:'서류 수집·이용 및 마스킹 확인이 필요합니다.',documents_required:'신분증·자격 서류와 등록번호를 준비한 뒤 심사를 요청해 주세요.',expert_unavailable:'해당 전문가는 현재 상담 접수가 불가합니다. 지도를 다시 확인해 주세요.',reason_required:'심사·제재 사유를 5자 이상 입력해 주세요.',verification_required:'서류와 등록정보 확인이 필요합니다.',stale_revision:'다른 화면에서 변경됐습니다. 새로고침 후 다시 처리해 주세요.',request_consent_required:'상담 접수 동의를 확인해 주세요.',invalid_transition:'현재 상태에서는 처리할 수 없습니다.',invalid_period:'경고 후 유효한 노출정지 기간을 입력해 주세요.',application_locked:'제명된 계정은 변경할 수 없습니다.'};
 const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
 const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');
  try{const origin='http://127.0.0.1:'+server.address().port;if(req.headers.host!==new URL(origin).host){json(res,{error:'Local host only'},403);return;}const url=new URL(req.url,origin);const cookies=Object.fromEntries((req.headers.cookie||'').split(';').filter(x=>x.includes('=')).map(x=>x.trim().split('=')));let sid=cookies.test_flow;if(!sessions.has(sid)){sid=randomBytes(24).toString('hex');sessions.set(sid,ACTORS.customer);res.setHeader('Set-Cookie','test_flow='+sid+'; HttpOnly; SameSite=Strict; Path=/');}let actor=sessions.get(sid);
   if(url.pathname==='/api/test-flow/state'){json(res,{workspace:await db.command(actor,'workspace'),backend:db.backend,publicDeployment:false,realMembers:false,payments:false,kakaoMap:false});return;}
   if(url.pathname==='/api/test-flow/command'||url.pathname==='/api/test-flow/switch'){
    if(req.method!=='POST'||req.headers.origin!==origin){json(res,{error:'잘못된 요청입니다.'},403);return;}let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>6*1024*1024){json(res,{error:'파일 용량은 4MB 이하로 줄여 주세요.'},413);return;}chunks.push(chunk);}const body=JSON.parse(Buffer.concat(chunks));
    if(url.pathname.endsWith('/switch')){if(body.actor==='new_expert'){actor=(await db.command(ACTORS.admin,'new_expert')).id;lastExperts.set(sid,actor);}else if(body.actor==='expert')actor=lastExperts.get(sid)||ACTORS.expert;else if(ACTORS[body.actor])actor=ACTORS[body.actor];else{json(res,{error:'알 수 없는 테스트 계정'},400);return;}sessions.set(sid,actor);json(res,{actor:await db.command(actor,'session')});return;}
    const allowed=['catalog','register','profile','upload','delete_document','submit_review','request','admin_list','review','sanction','intake','document'];if(!allowed.includes(body.operation)){json(res,{error:'지원하지 않는 동작'},400);return;}const p=body.payload||{};
    if(body.operation==='upload'){if(typeof p.data!=='string'||!/^[A-Za-z0-9+/]*={0,2}$/.test(p.data))throw Error('invalid_document');const bytes=Buffer.from(p.data,'base64');if(bytes.length>4*1024*1024||documentType(bytes)!==p.mime)throw Error('invalid_document');p.filename=safeFilename(p.filename);}
    const result=await db.command(actor,body.operation,p);
    if(body.operation==='document'){res.setHeader('Content-Type',result.mime);res.setHeader('Content-Disposition','attachment; filename="test-document"');res.setHeader('Content-Security-Policy',"sandbox; default-src 'none'");res.end(Buffer.from(result.data,'base64'));return;}
    json(res,result);return;
   }
   if(url.pathname.startsWith('/api/')||/payment/.test(url.pathname)){json(res,{error:'공개 가입·결제·외부 전송 OFF'},403);return;}
   const routes=['/','/index.html','/claim','/find.html','/consult.html','/expert','/partner','/partner.html','/signup.html','/login.html','/account.html','/partner-work.html','/admin','/admin.html','/admin-requests.html','/requests.html','/dashboard.html'];
   if(routes.includes(url.pathname)){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(await readFile('public/test-flow.html'));return;}
   if(url.pathname==='/assets/test-flow.js'){res.setHeader('Content-Type','text/javascript');res.end(await readFile('artifacts/test-flow.js'));return;}
   const permitted=['/styles.css','/visual.css','/account.css','/test-flow.css'];if(permitted.includes(url.pathname)){res.setHeader('Content-Type','text/css');res.end(await readFile(path.join('public',url.pathname)));return;}
   json(res,{error:'이 테스트 화면은 메뉴에서 이동해 주세요.'},404);
  }catch(e){json(res,{error:errors[e.message]||'처리하지 못했습니다. 입력값과 최신 상태를 확인해 주세요.',code:errors[e.message]?e.message:'invalid_request'},400);}
 });await new Promise(resolve=>server.listen(port,'127.0.0.1',resolve));return {server,db,close:async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await db.close();}};
}
if(process.argv[1]?.endsWith('test-flow.mjs')){const app=await startTestFlow();console.log('Private connected test: http://127.0.0.1:3194/ · '+app.db.backend);}
