import {createSocialLogin,normalizeContact,validContact} from '../src/test-flow/social-server.mjs';
import http from 'node:http';import path from 'node:path';import {randomBytes} from 'node:crypto';import {readFile,mkdir} from 'node:fs/promises';import {build} from 'esbuild';import {openTestDatabase,ACTORS} from '../src/test-flow/database.mjs';import {documentType,safeFilename} from '../netlify/functions/_shared/expert-documents.mjs';
export async function startTestFlow({port=3195,memory=false,dataDir,env=process.env}={}){
 await mkdir('artifacts',{recursive:true});await build({entryPoints:['src/test-flow/ui.js'],bundle:true,format:'esm',outfile:'artifacts/test-flow.js'});const db=await openTestDatabase({memory,dataDir,env});const sessions=new Map();const lastExperts=new Map();const social=createSocialLogin(env);const consumers=new Map();
 const errors={invalid_booking_time:'예약 날짜와 시간을 확인해 주세요. 한국 시간 기준 10시부터 17시까지 한 시간 단위로 선택할 수 있습니다.',contact_consent_required:'연락처 공개 동의와 예시 번호(010-0000-0000 형식)를 확인해 주세요.',contact_reassignment_forbidden:'이미 배정된 전문가 변경은 새 고객 동의가 필요합니다.',contact_use_workflow:'아래 연락·사후관리에서 담당 전문가가 상태를 변경해 주세요.',support_invalid:'글자 수와 필수 항목, 접수 동의를 확인해 주세요.',test_login_required:'테스트 계정을 선택해 주세요.',admin_required:'관리자 테스트 계정에서만 가능합니다.',expert_required:'전문가 테스트 계정을 선택해 주세요.',customer_required:'소비자 테스트 계정에서 신청해 주세요.',invalid_profile:'이름·소속·활동지역을 확인해 주세요.',invalid_registration:'등록번호 형식을 확인해 주세요. 주민번호를 입력하지 마세요.',invalid_specialty:'전문분야를 확인해 주세요.',pledge_required:'소비자보호 서약 3개에 모두 동의해 주세요.',document_consent_required:'서류 수집·이용 및 마스킹 확인이 필요합니다.',documents_required:'신분증·자격 서류와 등록번호를 준비한 뒤 심사를 요청해 주세요.',expert_unavailable:'해당 전문가는 현재 상담 접수가 불가합니다. 지도를 다시 확인해 주세요.',reason_required:'심사·제재 사유를 5자 이상 입력해 주세요.',verification_required:'서류와 등록정보 확인이 필요합니다.',stale_revision:'다른 화면에서 변경됐습니다. 새로고침 후 다시 처리해 주세요.',request_consent_required:'상담 접수 동의를 확인해 주세요.',invalid_transition:'현재 상태에서는 처리할 수 없습니다.',invalid_period:'경고 후 유효한 노출정지 기간을 입력해 주세요.',application_locked:'제명된 계정은 변경할 수 없습니다.',branch_required:'보험소 거점 운영자 계정에서만 가능합니다.',branch_unavailable:'해당 보험소 거점은 현재 예약을 받을 수 없습니다. 지도를 다시 확인해 주세요.',booking_forbidden:'우리 거점의 예약만 처리할 수 있습니다.',expert_forbidden:'우리 거점 소속의 인증된 전문가만 배정할 수 있습니다.',request_forbidden:'본인에게 접수된 신청만 처리할 수 있습니다.',request_key_conflict:'같은 신청이 다르게 접수됐습니다. 새로고침 후 다시 시도해 주세요.'};
 const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
 const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');
  try{const origin='http://127.0.0.1:'+server.address().port;if(req.headers.host!==new URL(origin).host){json(res,{error:'Local host only'},403);return;}const url=new URL(req.url,origin);const cookies=Object.fromEntries((req.headers.cookie||'').split(';').filter(x=>x.includes('=')).map(x=>x.trim().split('=')));let sid=cookies.test_flow;if(!sessions.has(sid)){sid=randomBytes(24).toString('hex');sessions.set(sid,ACTORS.customer);res.setHeader('Set-Cookie','test_flow='+sid+'; HttpOnly; SameSite=Lax; Path=/');}let actor=sessions.get(sid);
   if(url.pathname==='/auth/callback'){try{await social.finish(sid,url.searchParams);res.writeHead(303,{Location:lastExperts.get(sid)===actor?'/expert':'/signup.html'});res.end();}catch{res.writeHead(303,{Location:'/signup.html?auth_error=1'});res.end();}return;}
   if(url.pathname==='/api/test-flow/state'){json(res,{workspace:await db.command(actor,'workspace'),signupProfile:consumers.get(sid)||null,social: social.status(sid),backend:db.backend,publicDeployment:false,realMembers:false,payments:false,kakaoMap:false});return;}
   if(url.pathname==='/api/test-flow/command'||url.pathname==='/api/test-flow/switch'){
    if(req.method!=='POST'||req.headers.origin!==origin){json(res,{error:'잘못된 요청입니다.'},403);return;}let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>6*1024*1024){json(res,{error:'파일 용량은 4MB 이하로 줄여 주세요.'},413);return;}chunks.push(chunk);}const body=JSON.parse(Buffer.concat(chunks));
    if(url.pathname.endsWith('/switch')){if(body.actor==='new_expert'){actor=(await db.command(ACTORS.admin,'new_expert')).id;lastExperts.set(sid,actor);}else if(body.actor==='expert')actor=lastExperts.get(sid)||ACTORS.expert;else if(ACTORS[body.actor])actor=ACTORS[body.actor];else{json(res,{error:'알 수 없는 테스트 계정'},400);return;}sessions.set(sid,actor);json(res,{actor:await db.command(actor,'session')});return;}
    if(body.operation==='social_start'){try{json(res,{url:social.start(sid,body.payload?.provider,origin)});}catch{json(res,{error:'소셜 로그인 키 설정이 필요합니다.'},400);}return;}
    if(body.operation==='social_demo'){if(env.SOCIAL_TEST_ENABLED==='true'){json(res,{error:'실제 소셜 연결 모드에서는 체험 로그인을 사용할 수 없습니다.'},403);return;}json(res,social.demo(sid));return;}
    if(body.operation?.startsWith('signup_')){const p=body.payload||{};const fail=message=>json(res,{error:message},400);const identity=social.status(sid).identity;if(!identity)return fail('소셜 로그인 또는 테스트 체험을 먼저 시작하세요.');if(!validContact(p.phone))return fail('연락받을 번호 형식을 확인하세요.');if(typeof p.name!=='string'||p.name.trim().length<2||p.name.length>60)return fail('이름을 확인하세요.');
     if(!['signup_customer','signup_expert'].includes(body.operation))return fail('지원하지 않는 동작');
     const profile={name:p.name.trim(),region:p.region||'',phone:normalizeContact(p.phone),phone_verified:false,phone_source:'manual',email:identity.email,provider:identity.provider,test:identity.test};
     if(body.operation==='signup_expert'){const result=await db.command(actor,'register',p);consumers.set(sid,profile);json(res,result);return;}consumers.set(sid,profile);json(res,{complete:true,test:identity.test});return;
    }
    const allowed=['contact_list','contact_admin','contact_view','contact_state','contact_survey','contact_report','contact_report_review','contact_erase','support_faq','support_mine','support_submit','support_admin','support_reply','support_faq_save','support_faq_delete','catalog','register','profile','upload','delete_document','submit_review','request','request_state','admin_list','review','sanction','intake','document','branch_catalog','branch_detail','book','branch_workspace','branch_bookings','assign_expert','booking_state','branch_register_expert'];if(!allowed.includes(body.operation)){json(res,{error:'지원하지 않는 동작'},400);return;}const p=body.payload||{};
    if(body.operation==='upload'){if(typeof p.data!=='string'||!/^[A-Za-z0-9+/]*={0,2}$/.test(p.data))throw Error('invalid_document');const bytes=Buffer.from(p.data,'base64');if(bytes.length>4*1024*1024||documentType(bytes)!==p.mime)throw Error('invalid_document');p.filename=safeFilename(p.filename);}
    const result=await db.command(actor,body.operation,p);
    if(body.operation==='document'){res.setHeader('Content-Type',result.mime);res.setHeader('Content-Disposition','attachment; filename="test-document"');res.setHeader('Content-Security-Policy',"sandbox; default-src 'none'");res.end(Buffer.from(result.data,'base64'));return;}
    json(res,result);return;
   }
   if(url.pathname.startsWith('/api/')||/payment/.test(url.pathname)){json(res,{error:'공개 가입·결제·외부 전송 OFF'},403);return;}
   const routes=['/','/index.html','/claim','/find.html','/consult.html','/expert','/partner','/partner.html','/signup.html','/login.html','/account.html','/partner-work.html','/branch.html','/admin','/admin.html','/admin-requests.html','/requests.html','/dashboard.html'];
   if(routes.includes(url.pathname)){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(await readFile('public/test-flow.html'));return;}
   if(url.pathname==='/assets/test-flow.js'){res.setHeader('Content-Type','text/javascript');res.end(await readFile('artifacts/test-flow.js'));return;}
   if(url.pathname==='/vendor/leaflet.js'){res.setHeader('Content-Type','text/javascript');res.end(await readFile('public/vendor/leaflet.js'));return;}
   if(url.pathname==='/brand.css'){res.setHeader('Content-Type','text/css');res.end(await readFile('public/brand.css'));return;}
   if(url.pathname==='/manifest.webmanifest'){res.setHeader('Content-Type','application/manifest+json');res.end(await readFile('public/manifest.webmanifest'));return;}
   if(/^\/brand\/[a-z0-9-]+\.(svg|png)$/.test(url.pathname)){res.setHeader('Content-Type',url.pathname.endsWith('.svg')?'image/svg+xml':'image/png');res.end(await readFile('public'+url.pathname));return;}
   const permitted=['/vendor/leaflet.css','/styles.css','/visual.css','/account.css','/test-flow.css'];if(permitted.includes(url.pathname)){res.setHeader('Content-Type','text/css');const css=await readFile(path.join('public',url.pathname),'utf8');res.end(css.replace(/^@import[^;]+;/gm,''));return;}
   json(res,{error:'이 테스트 화면은 메뉴에서 이동해 주세요.'},404);
  }catch(e){json(res,{error:errors[e.message]||'처리하지 못했습니다. 입력값과 최신 상태를 확인해 주세요.',code:errors[e.message]?e.message:'invalid_request'},400);}
 });await new Promise(resolve=>server.listen(port,'127.0.0.1',resolve));return {server,db,close:async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await db.close();}};
}
if(process.argv[1]?.endsWith('test-flow.mjs')){const app=await startTestFlow();console.log('Private connected test: http://127.0.0.1:3195/ · '+app.db.backend);}
