import {pendingAction,safeNext} from './member-access.js';
import {renderServiceArea} from './urgent.js';
export const BETA_VERSION='2026-10-05-beta-v1';
const key='bohumso-beta-invite';
const labels={ACTIVE:'사용 가능',USED:'사용 완료',EXPIRED:'만료',REVOKED:'폐기',PENDING:'심사 대기',APPROVED:'승인',REJECTED:'보완 요청',SUSPENDED:'중지',requested:'예약 요청',coordinating:'수락·일정 확인',scheduled:'확정',awaiting_completion:'완료 확인 대기',completed:'상담 완료',cancelled:'취소',no_show:'노쇼',dispute:'문의',unmatched:'배정 대기'};
const errors={phone_verification_required:'운영자의 전화 확인 후 진행할 수 있어요.',invalid_invite:'초대 링크를 사용할 수 없습니다. 초대해주신 분에게 새 링크를 요청해주세요.',consent_required:'베타 안내와 필수 동의를 확인해 주세요.',phone_requires_email:'전화번호를 제한할 때는 허용 이메일도 입력해 주세요.',beta_membership_inactive:'참여 상태를 운영자에게 확인해 주세요.'};
export function betaCode(){const q=new URLSearchParams(location.search).get('invite');if(q&&/^[a-f0-9]{64}$/.test(q)){try{sessionStorage.setItem(key,JSON.stringify({code:q,at:Date.now()}));}catch{}return q;}try{const v=JSON.parse(sessionStorage.getItem(key)||'null');return v&&Date.now()-v.at<86400000?v.code:'';}catch{return '';}}
export function betaReturn(){const q=new URLSearchParams({next:safeNext(pendingAction())});const code=betaCode();if(code)q.set('invite',code);return '/account.html?'+q;}
export function clearBeta(){try{sessionStorage.removeItem(key);}catch{}const u=new URL(location.href);u.searchParams.delete('invite');history.replaceState(null,'',u.pathname+u.search+u.hash);}
function el(tag,text,root,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;root?.append(n);return n;}
function button(text,root,run){const b=el('button',text,root,'btn');b.type='button';b.onclick=async()=>{b.disabled=true;try{await run();}catch(e){let p=root.querySelector('[role=alert]')||el('p','',root);p.setAttribute('role','alert');p.textContent=errors[e.message]||'처리하지 못했어요. 입력 내용과 연결을 확인해 주세요.';}finally{b.disabled=false;}};return b;}
function input(root,label,name,type='text'){const l=el('label',label,root,'field'),i=el('input','',l);i.name=name;i.type=type;return i;}
async function rpc(client,name,args){const {data,error}=await client.rpc(name,args);if(error)throw Error(error.message);return data;}
export async function renderBetaSignup({client,root,message}){
 root.innerHTML='<section class="card auth-card"><p>예약과 상담 내용을 안전하게 관리하기 위해 로그인이 필요합니다.</p><div id="betaLogin"></div><div class="auth-divider">또는</div><h2>초대받으셨나요?</h2><p>초대코드를 확인하면 베타 가입을 이어갈 수 있어요.</p><div id="inviteEntry"></div><div id="inviteSignup" hidden></div><p class="muted">현재 우리곁에 보험소는 초대된 분들과 클로즈드 베타를 진행하고 있습니다. 기존 회원은 바로 로그인할 수 있습니다.</p><button type="button" disabled class="btn secondary">카카오 로그인 · 준비중</button><p><a href="/beta-terms.html">베타 이용 안내</a> · <a href="/beta-privacy.html">개인정보 안내</a></p></section>';
 const login=root.querySelector('#betaLogin');
 const oauth=()=>client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+betaReturn()}}).then(r=>{if(r.error)throw r.error;});
 button('Google로 계속하기',login,oauth);
 const emailLink=el('a','이메일로 로그인',login,'btn secondary');emailLink.href='/login.html?next='+encodeURIComponent(pendingAction());
 const entry=root.querySelector('#inviteEntry'),code=input(entry,'초대코드','invite');code.autocomplete='off';code.maxLength=64;code.value=betaCode();
 const verify=async()=>{const value=code.value.trim();const result=await rpc(client,'beta_invite_check',{code:value});if(!result.valid)throw Error('invalid_invite');try{sessionStorage.setItem(key,JSON.stringify({code:value,at:Date.now()}));}catch{}if((await client.auth.getUser()).data?.user){location.assign(betaReturn());return;}const signup=root.querySelector('#inviteSignup');signup.hidden=false;signup.replaceChildren();el('h2',result.role==='EXPERT'?'전문가 베타 가입':'고객 베타 가입',signup);el('p','초대를 확인했어요. 인증 후 베타 동의를 마치면 가입됩니다.',signup);button('Google로 베타 가입',signup,oauth);const f=el('form','',signup);const email=input(f,'이메일','email','email'),pw=input(f,'비밀번호 (8자 이상)','password','password');email.required=pw.required=true;email.autocomplete='email';pw.autocomplete='new-password';pw.minLength=8;pw.maxLength=128;const consent=input(f,'베타 이용·개인정보 안내를 확인했고 만 14세 이상입니다.','consent','checkbox');consent.required=true;const links=el('p','',f);for(const [title,url] of [['베타 이용 안내','/beta-terms.html'],['개인정보 안내','/beta-privacy.html']]){const a=el('a',title+' ',links);a.href=url;a.target='_blank';a.rel='noopener';}const submit=el('button','인증 메일 받기',f,'btn');submit.type='submit';f.onsubmit=async e=>{e.preventDefault();if(!f.reportValidity())return;submit.disabled=true;try{const r=await client.auth.signUp({email:email.value.trim(),password:pw.value,options:{emailRedirectTo:location.origin+betaReturn()}});if(r.error)throw r.error;message('등록 가능한 이메일이면 인증 메일이 발송됩니다. 메일의 가입 완료하기를 눌러 주세요.');if(r.data?.session)location.assign(betaReturn());}catch{message('이메일과 연결 상태를 확인해 주세요. 기존 계정은 이메일로 로그인할 수 있습니다.');}finally{submit.disabled=false;}};};
 button('초대코드로 베타 가입',entry,verify);if(code.value)try{await verify();}catch(e){message(errors[e.message]||'초대를 확인하지 못했어요.');}
}
export async function renderBetaFinish({client,root,onDone}){
 const code=betaCode();if(!code)return false;
 const checked=await rpc(client,'beta_invite_check',{code});
 const card=el('section','',root,'card');el('h2','베타 가입 마무리',card);
 if(!checked.valid){el('p',errors.invalid_invite,card);const a=el('a','새 초대코드 입력',card,'btn');a.href='/signup.html?next='+encodeURIComponent(pendingAction());a.onclick=e=>{e.preventDefault();clearBeta();card.remove();renderBetaSignup({client,root,message:text=>{document.getElementById('accountMessage').textContent=text;}});};return true;}
 el('p','예약 기능을 함께 점검하는 비공개 베타입니다. 실제 신분증·주민번호·의료서류는 입력하지 마세요.',card);
 const f=el('form','',card);const age=input(f,'만 14세 이상입니다.','age','checkbox'),terms=input(f,'베타 이용 안내에 동의합니다.','terms','checkbox'),privacy=input(f,'베타 개인정보 처리에 동의합니다.','privacy','checkbox');for(const i of [age,terms,privacy])i.required=true;
 for(const [label,path] of [['베타 이용 안내','/beta-terms.html'],['베타 개인정보 안내','/beta-privacy.html']]){const a=el('a',label+' ',f);a.href=path;a.target='_blank';a.rel='noopener';}
 const b=el('button','동의하고 가입 완료',f,'btn');b.type='submit';f.onsubmit=async e=>{e.preventDefault();if(!f.reportValidity())return;b.disabled=true;try{const {data}=await client.auth.getSession();const r=await fetch('/api/beta/join',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+data.session.access_token},body:JSON.stringify({code,ageAccepted:true,termsVersion:BETA_VERSION,privacyVersion:BETA_VERSION})});const result=await r.json();if(!r.ok)throw Error(result.error);clearBeta();card.remove();await onDone(result);}catch(error){const p=card.querySelector('[role=alert]')||el('p','',card);p.setAttribute('role','alert');p.textContent=errors[error.message]||'가입을 마무리하지 못했어요. 잠시 후 다시 시도해 주세요.';}finally{b.disabled=false;}};return true;
}
export async function renderBetaAdmin(client,host){
 const panel=el('section','',host,'card beta-admin');panel.id='betaInvites';el('h2','베타 초대·참여자',panel);const body=el('div','',panel);
 const load=async()=>{const data=await rpc(client,'beta_admin',{operation:'dashboard'});body.replaceChildren();el('p',`초대 ${data.issued} · 사용 ${data.used} · 가입 ${data.joined} · 고객 ${data.customers} · 전문가 ${data.experts}`,body);el('p','베타 예약 · '+Object.entries(data.bookings).map(([s,n])=>`${labels[s]||s} ${n}`).join(' / '),body);
 el('p',`최근 7일 가입 오류 ${data.errors} · 베타 참여자 예약만 집계합니다.`,body);const f=el('form','',body);const role=el('select','',el('label','초대할 분',f));for(const [value,label] of [['CUSTOMER','고객'],['EXPERT','전문가']]){const o=el('option',label,role);o.value=value;}const email=input(f,'허용 이메일 (선택)','email','email'),phone=input(f,'허용 전화번호 (선택·이메일 함께 입력)','phone','tel'),expiry=input(f,'만료일','expiry','date'),uses=input(f,'사용 횟수','uses','number');expiry.required=true;expiry.value=new Date(Date.now()+7*86400000).toISOString().slice(0,10);uses.value='1';uses.min='1';uses.max='100';const create=el('button','초대 만들기',f,'btn');create.type='submit';f.onsubmit=async e=>{e.preventDefault();if(!f.reportValidity())return;create.disabled=true;try{const result=await rpc(client,'beta_admin',{operation:'create',payload:{role:role.value,email:email.value,phone:phone.value,expiresAt:new Date(expiry.value+'T23:59:00+09:00').toISOString(),maxUses:Number(uses.value)}});const link=location.origin+'/signup.html?'+new URLSearchParams({invite:result.code,next:'/map.html'});const out=el('div','',f);const value=input(out,'초대링크 (지금 복사해 주세요)','link');value.value=link;value.readOnly=true;button('초대링크 복사',out,()=>navigator.clipboard.writeText(link));}catch(e){el('p',errors[e.message]||'초대 설정을 확인해 주세요.',f).setAttribute('role','alert');}finally{create.disabled=false;}};
 const list=el('details','',body);el('summary','발급한 초대',list);for(const i of data.invites){const row=el('article','',list,'card');el('p',`${i.role==='EXPERT'?'전문가':'고객'} · ${i.used_count}/${i.max_uses} · ${labels[i.status]||i.status} · ${i.allowed_email||'이메일 제한 없음'}`,row);if(i.status==='ACTIVE')button('초대 폐기',row,async()=>{await rpc(client,'beta_admin',{operation:'revoke',payload:{id:i.id}});await load();});}
 for(const m of data.members){const row=el('article','',body,'card');el('h3',m.email,row);el('p',(m.role==='EXPERT'?'전문가':'고객')+' · '+(m.phone_status==='UNVERIFIED'?'전화 확인 대기':'베타 전화 확인 완료')+(m.active?'':' · 이용 중지'),row);const phone=input(row,'직접 확인한 참여자의 전화번호','phone','tel');phone.value=m.phone||'';const check=input(row,'이 참여자의 번호를 직접 확인했습니다.','checked','checkbox');button('베타 전화 확인',row,async()=>{if(!check.checked)throw Error('consent_required');await rpc(client,'beta_admin',{operation:'verify_phone',payload:{userId:m.user_id,phone:phone.value,checked:true}});await load();});}
 const experts=await rpc(client,'beta_expert',{operation:'list'});for(const x of experts){const row=el('article','',body,'card');el('h3',x.name+' · 전문가 심사',row);el('p',x.region+' · '+x.hours+' · '+(labels[x.status]||x.status),row);el('p',x.phoneVerified?'베타 전화 확인 완료':'전화 확인 필요',row);const reason=input(row,'검토 내용','reason');for(const [title,decision] of [['베타 지도 노출 승인','APPROVED'],['보완 요청','REJECTED'],['노출 중지','SUSPENDED']])button(title,row,async()=>{if(reason.value.trim().length<3)throw Error('consent_required');await rpc(client,'beta_expert',{operation:'review',payload:{userId:x.user_id,decision,reason:reason.value}});await load();});}
 };await load();button('현황 새로고침',panel,load);
}
export async function renderBetaExpert(client,root){
 const state=await rpc(client,'beta_expert',{operation:'settings'});const card=el('section','',root,'card');el('h2',state.expert?.status==='APPROVED'?'보험소 PRO · 베타':'전문가 베타 참여',card);
 el('p','신분증·자격서류를 받지 않는 비공개 기능 점검입니다. 공개 자격 인증과 구분됩니다.',card);
 if(!state.phoneVerified){el('p','초대한 운영자가 전화번호를 확인하면 다음 단계로 진행할 수 있어요.',card);const a=el('a','내 계정',card,'btn');a.href='/account.html';return;}
 if(state.expert){el('p',({PENDING:'활동지역 설정 후 운영자 검토를 기다려 주세요.',APPROVED:'베타 참여자에게 활동지역이 표시됩니다.',REJECTED:'보완 후 다시 제출해 주세요.',SUSPENDED:'활동이 중지되었습니다. 운영자에게 문의해 주세요.'})[state.expert.status],card);if(state.expert.review_note)el('p',state.expert.review_note,card);}
 const f=el('form','',card),profile=state.profile||{};const name=input(f,'이름','name'),org=input(f,'소속','organization');name.value=profile.name||'';org.value=profile.organization||'';name.required=org.required=true;name.minLength=org.minLength=2;name.maxLength=60;org.maxLength=120;const job=el('select','',el('label','직군',f));for(const [value,label] of [['planner','보험설계사'],['adjuster','손해사정사']]){const o=el('option',label,job);o.value=value;}job.value=profile.profession||'planner';const tags=el('fieldset','',f);el('legend','도움을 드릴 수 있는 분야',tags);const fields=[];for(const [value,label] of [['claim','보험금 청구'],['coverage','내 보험 확인'],['death','가족 사망'],['illness','진단'],['medical','입원·수술'],['accident','사고']]){const c=input(tags,label,'specialty','checkbox');c.value=value;c.checked=profile.specialties?.includes(value)||false;fields.push(c);}const hours=input(f,'상담 가능 시간','hours');hours.placeholder='평일 09:00~18:00';hours.value=profile.hours||'';hours.required=true;hours.maxLength=200;const pledge=input(f,'부당한 금전 요구·보험 가입 강요·규정 우회 유인을 하지 않겠습니다.','pledge','checkbox');pledge.required=true;const submit=el('button','기본정보 저장 · 다음',f,'btn');submit.type='submit';const areas=el('div','',root);
 f.onsubmit=async e=>{e.preventDefault();if(!f.reportValidity())return;submit.disabled=true;try{await rpc(client,'beta_expert',{operation:'save',payload:{name:name.value,organization:org.value,profession:job.value,hours:hours.value,specialties:fields.filter(c=>c.checked).map(c=>c.value),pledge:true}});areas.replaceChildren();await renderServiceArea(client,areas);areas.scrollIntoView({behavior:'smooth',block:'start'});}catch(e){el('p',errors[e.message]||'이름·분야·가능시간을 확인해 주세요.',card).setAttribute('role','alert');}finally{submit.disabled=false;}};
 if(state.expert)await renderServiceArea(client,areas);
 if(state.expert?.status==='APPROVED'){const a=el('a','새 예약 확인',card,'btn');a.href='/partner-work.html';}
}
