import {memberService} from './member-access.js';
import {resources} from '../public/claim-resources-data.js';
import {mountCustomerSupport,supportAvailable} from './support-ui.js';
const root=document.getElementById('rightsContent');
const reportResource=resources.find(r=>r.id===new URLSearchParams(location.search).get('resource'));
if(reportResource){const login=root.querySelector('a');if(login)login.href='/login.html?next='+encodeURIComponent('/support.html?resource='+encodeURIComponent(reportResource.id));}
async function start(){const {client}=await memberService();const {data}=await client.auth.getUser();if(!data.user)return;
 if(await supportAvailable(client))return mountCustomerSupport({client,host:root,userId:data.user.id,initialKind:reportResource?'REPORT':'INQUIRY',initialBody:reportResource?'공식 링크 오류 제보\n기관: '+reportResource.name+'\n주소: '+reportResource.url+'\n확인한 문제: ':''});
 root.innerHTML='<h2>내 정보와 문의</h2><form id="rightsForm"><label>요청 유형<select name="kind"><option value="INQUIRY">문의</option><option value="ACCESS">개인정보 열람</option><option value="CORRECT">개인정보 정정</option><option value="DELETE">개인정보 삭제</option><option value="REPORT">전문가·오류 신고</option><option value="WITHDRAW">회원탈퇴</option></select></label><label>내용<textarea name="detail" maxlength="2000" rows="4" placeholder="비밀번호·인증번호·건강 상세정보는 입력하지 마세요."></textarea></label><p>삭제는 보관 의무와 처리 범위를 확인한 뒤 결과를 안내합니다. 탈퇴하면 회원 기능 이용이 즉시 중지됩니다.</p><button class="btn">요청 접수</button></form><p id="rightsStatus" role="status"></p><div id="rightsHistory"></div>';
 const status=document.getElementById('rightsStatus'),history=document.getElementById('rightsHistory');
 if(reportResource){const form=document.getElementById('rightsForm');form.elements.kind.value='REPORT';form.elements.detail.value='공식 링크 오류 제보\n기관: '+reportResource.name+'\n주소: '+reportResource.url+'\n확인한 문제: ';status.textContent='문제를 적고 접수 버튼을 눌러 주세요. 아직 전송되지 않았습니다.';}
 const draw=async()=>{const result=await client.rpc('member_rights',{operation:'list'});if(result.error)throw result.error;history.replaceChildren();for(const r of result.data.requests){const p=document.createElement('p');p.textContent=new Date(r.created_at).toLocaleDateString('ko-KR')+' · '+({INQUIRY:'문의',ACCESS:'열람',CORRECT:'정정',DELETE:'삭제',REPORT:'신고',WITHDRAW:'탈퇴'}[r.kind]||r.kind)+' · '+(r.status==='RECEIVED'?'접수됨':r.status);history.append(p);if(r.response){const reply=document.createElement('p');reply.textContent=r.response;history.append(reply);}}};
 let busy=false;
 document.getElementById('rightsForm').onsubmit=async event=>{event.preventDefault();if(busy)return;const form=event.currentTarget,d=new FormData(form),operation=String(d.get('kind'));if(operation==='WITHDRAW'&&!confirm('회원 이용을 중지하고 탈퇴를 접수할까요?'))return;const button=form.querySelector('button');busy=true;button.disabled=true;try{const result=await client.rpc('member_rights',{operation,payload:{detail:d.get('detail'),confirmed:operation==='WITHDRAW'}});if(result.error)throw result.error;if(operation==='WITHDRAW'){try{await client.auth.signOut({scope:'global'});}catch{}root.replaceChildren();const p=document.createElement('p');p.textContent='탈퇴 요청을 접수하고 회원 이용을 중지했습니다. 자료 삭제 처리 결과는 운영자가 안내합니다.';root.append(p);return;}status.textContent='접수했습니다. 처리 결과는 운영자가 안내합니다.';form.elements.detail.value='';try{await draw();}catch{status.textContent='문의는 저장됐지만 이력을 불러오지 못했습니다. 다시 접수하지 말고 페이지를 새로고침해 주세요.';}}catch{status.textContent='저장 여부를 확인하지 못했습니다. 입력 내용은 유지했습니다. 이력을 먼저 확인한 뒤 다시 시도해 주세요.';}finally{busy=false;button.disabled=false;}};
 try{await draw();}catch{status.textContent='이력을 불러오지 못했지만 문의를 작성할 수 있습니다. 중복 접수 전에는 이력을 다시 확인해 주세요.';}
}
start().catch(()=>{root.textContent='온라인 요청 연결을 확인하지 못했습니다. 아래 이메일로 문의해 주세요.';});
