import {setupPush} from './push-provider.js';
import {memberService,safeNext,authURL} from './member-access.js';
let started=false;
export function notificationLink(value){const link=safeNext(value,'/requests.html');return /^\/(notifications|requests|partner-work|admin-requests|urgent)\.html(?:[?#]|$)/.test(link)?link:'/requests.html';}
export async function startNotifications(){
 if(started)return;started=true;
 const {client,config}=await memberService();if(config.inAppNotificationsEnabled!==true)return;
 void setupPush(client,config).catch(()=>{});
 let userId=null,seen=new Set(),loaded=false,sequence=0;
 const host=document.querySelector('[data-notification-center]');
 if(host&&config.pushNotificationsEnabled){void (async()=>{const {data}=await client.rpc('my_membership');if(!data?.admin)return;const button=document.createElement('button');button.textContent='대기 알림 전송';host.before(button);button.onclick=async()=>{button.disabled=true;try{const {data:auth}=await client.auth.getSession();const response=await fetch('/api/push/dispatch',{method:'POST',headers:{Authorization:'Bearer '+auth.session.access_token}});const result=await response.json();button.textContent=response.ok?'전송 요청 '+result.sent+'건 처리':'알림 연결을 확인해주세요.';}catch{button.textContent='연결 후 다시 확인해주세요.';}finally{button.disabled=false;}};})().catch(()=>{});}

 const badge=document.createElement('a');badge.href='/notifications.html';badge.className='notification-bell';badge.setAttribute('aria-label','알림함');badge.textContent='알림';badge.hidden=true;(document.querySelector('header.nav')||document.querySelector('main')||document.body).append(badge);
 const toast=document.createElement('aside');toast.className='notification-toast';toast.hidden=true;toast.setAttribute('role','status');document.body.append(toast);let hideTimer;
 function clear(){sequence++;userId=null;loaded=false;seen.clear();badge.hidden=true;toast.hidden=true;host?.replaceChildren();document.querySelector('[data-notification-reservation]')?.remove();document.querySelectorAll('.notification-count').forEach(n=>n.hidden=true);clearTimeout(hideTimer);}
 async function load(operation='list',id=null){const current=++sequence;const {data:auth}=await client.auth.getUser();if(current!==sequence)return;if(!auth?.user){clear();if(host)location.replace(authURL(location.pathname+location.search,'login'));return;}if(userId!==auth.user.id){userId=auth.user.id;loaded=false;seen.clear();toast.hidden=true;host?.replaceChildren();}
  const {data,error}=await client.rpc('notification_inbox',{operation,notification_id:id});if(current!==sequence)return;if(error){if(host)host.textContent='알림을 불러오지 못했어요. 잠시 후 다시 확인해주세요.';return;}
  badge.hidden=false;badge.textContent=data.unread?'알림 '+(data.unread>99?'99+':data.unread):'알림';badge.setAttribute('aria-label','알림함 · 읽지 않은 알림 '+data.unread+'개');
  const reservation=document.querySelector('.customer-nav a[href="/requests.html"]');if(reservation){let dot=reservation.querySelector('.notification-count');if(!dot){dot=document.createElement('span');dot.className='notification-count';reservation.append(dot);}dot.hidden=!data.unread;dot.textContent=data.unread>99?'99+':String(data.unread);}
  const fresh=data.items.find(n=>!n.read_at&&!seen.has(n.id));if(loaded&&fresh){toast.replaceChildren();const text=document.createElement('span');text.textContent=fresh.title;const link=document.createElement('a');link.textContent='확인';link.href=notificationLink(fresh.deep_link);const close=document.createElement('button');close.textContent='닫기';close.onclick=()=>toast.hidden=true;toast.append(text,link,close);toast.hidden=false;clearTimeout(hideTimer);hideTimer=setTimeout(()=>toast.hidden=true,5000);window.dispatchEvent(new Event('bohumso-reservation-updated'));}loaded=true;data.items.forEach(n=>seen.add(n.id));
  if(host){host.replaceChildren();const all=document.createElement('button');all.textContent='모두 읽음';all.disabled=!data.unread;all.onclick=()=>void load('read_all');host.append(all);if(!data.items.length){const empty=document.createElement('p');empty.textContent='새로운 알림이 없어요.';host.append(empty);}for(const n of data.items){const row=document.createElement('article');row.className='card notification-item';const title=document.createElement('h2');title.textContent=n.title;const body=document.createElement('p');body.textContent=n.body;const time=document.createElement('p');time.textContent=new Date(n.created_at).toLocaleString('ko-KR')+' · '+(n.read_at?'읽음':'안 읽음');const link=document.createElement('a');link.href=notificationLink(n.deep_link);link.textContent='예약 확인하기';link.onclick=async event=>{event.preventDefault();try{await client.rpc('notification_inbox',{operation:'read',notification_id:n.id});}finally{location.assign(notificationLink(n.deep_link));}};const read=document.createElement('button');read.textContent='읽음 표시';read.disabled=!!n.read_at;read.onclick=()=>void load('read',n.id);row.append(title,body,time,link,read);host.append(row);}}
 }
 client.auth.onAuthStateChange(()=>{clear();setTimeout(()=>void load().catch(()=>{}),0);});
 const reservationId=new URLSearchParams(location.search).get('reservation');
 async function detail(){if(!host||!reservationId||!userId)return;const owner=userId;const result=await client.rpc('notification_reservation',{reservation_id:reservationId});if(owner!==userId)return;let panel=document.querySelector('[data-notification-reservation]');if(!panel){panel=document.createElement('section');panel.className='card';panel.dataset.notificationReservation='';host.before(panel);}panel.replaceChildren();if(result.error){panel.textContent='예약을 확인할 수 없어요. 로그인한 계정과 담당 예약을 확인해주세요.';return;}const r=result.data;const heading=document.createElement('h2');heading.textContent=r.office_name||'상담 예약';const status=document.createElement('p');status.textContent=({requested:'요청 전달',coordinating:'일정 확인 중',confirmed:'예약 확정',scheduled:'예약 확정',cancelled:'취소',completed:'상담 완료',unmatched:'다시 예약해주세요',awaiting_completion:'완료 확인 대기'}[r.state]||'진행 중')+' · '+new Date(r.preferred_at).toLocaleString('ko-KR');panel.append(heading,status);if(r.workspace){const link=document.createElement('a');link.href=notificationLink(r.workspace+'?reservation='+r.id);link.textContent='예약 관리';panel.append(link);}}
 await load();await detail();window.addEventListener('bohumso-push-received',()=>void load().catch(()=>{}));window.addEventListener('bohumso-reservation-updated',()=>void detail().catch(()=>{}));const poll=setInterval(()=>{if(!document.hidden)void load().catch(()=>{});},20000);window.addEventListener('pagehide',()=>{clearInterval(poll);clearTimeout(hideTimer);},{once:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)void load().catch(()=>{});});
}
