import {el,kst} from './consultation-ui.js';
const day=value=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(value);
const shortDate=value=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'short',day:'numeric',weekday:'short'}).format(value);
const purposeLabels={claim:'보험금 청구',coverage:'보장 확인',management:'내 보험 확인',new:'가입 상담',other:'기타 상담'};
export function renderOfficeRequest({form,command,refresh,message}){
 const params=new URLSearchParams(location.search);let region=params.get('region')||'',purpose=Object.hasOwn(purposeLabels,params.get('purpose'))?params.get('purpose'):'claim',date='',time='',step=region?1:0,busy=false;let requestKey=crypto.randomUUID();
 const chosenDate=params.get('date')||'',chosenTime=params.get('time')||'',chosenStamp=new Date(chosenDate+'T'+chosenTime+':00+09:00').getTime();
 if(region&&/^\d{4}-\d{2}-\d{2}$/.test(chosenDate)&&/^(09|1[0-7]):(00|30)$|^18:00$/.test(chosenTime)&&chosenStamp>=Date.now()+1800000&&chosenStamp<=Date.now()+90*86400000){date=chosenDate;time=chosenTime;step=2;}
 const method=['phone','nearby','scheduled'].includes(params.get('method'))?params.get('method'):'scheduled';
 form.classList.add('request-wizard');form.hidden=false;form.onsubmit=e=>e.preventDefault();
 function button(parent,label,fn,cls=''){const b=el('button',label,parent);b.type='button';b.className=cls;b.onclick=fn;return b;}
 function icon(parent,name,cls){const n=el('span',undefined,parent);n.className=cls||'';n.innerHTML=window.uiIcon?.(name)||'';return n;}
 function render(){form.replaceChildren();el('p',step===0?'지역 선택':step===1?'● ○ · 1 / 2':'● ● · 2 / 2',form).className='step-dots';
  if(region)el('p',region+' · '+purposeLabels[purpose]+' · 보험소 배정',form).className='wizard-context';
  if(step===0){el('h2','어디에서 도움받으실까요?',form);const label=el('label','상담 지역',form),regions=el('select',undefined,label);regions.name='region';regions.setAttribute('aria-label','상담 지역');el('option','지역을 선택하세요',regions).value='';for(const area of window.COVERAGE_AREAS||[]){const option=el('option',area.region+' '+area.name,regions);option.value=area.region+' '+area.name;}const next=button(form,'다음',()=>{if(regions.value){region=regions.value;step=1;render();}},'primary');next.disabled=true;regions.onchange=()=>next.disabled=!regions.value;return;}
  if(step===1){el('h2','어느 날이 편하세요?',form);el('p','담당 전문가 배정은 보험소가 도와드려요.',form);const choices=el('div',undefined,form);choices.className='choice-grid';for(let i=0;i<7;i++){const d=new Date(Date.now()+i*86400000),v=day(d);button(choices,(i===0?'오늘 · ':i===1?'내일 · ':'')+shortDate(d),()=>{requestKey=crypto.randomUUID();date=v;time='';step=2;render();}).setAttribute('aria-pressed',String(date===v));}const more=el('details',undefined,form);el('summary','다른 날짜',more);const label=el('label','희망 날짜',more),input=el('input',undefined,label);input.type='date';input.min=day(new Date());input.max=day(new Date(Date.now()+90*86400000));input.onchange=()=>{if(input.checkValidity()&&input.value){requestKey=crypto.randomUUID();date=input.value;time='';step=2;render();}};button(form,'지역 변경',()=>{step=0;render();},'text-button');return;}
  el('h2','몇 시가 편하세요?',form);el('p',shortDate(new Date(date+'T12:00:00+09:00')),form);const choices=el('div',undefined,form);choices.className='choice-grid';for(let minute=540;minute<=1080;minute+=30){const value=String(Math.floor(minute/60)).padStart(2,'0')+':'+String(minute%60).padStart(2,'0');const slot=new Date(date+'T'+value+':00+09:00');const b=button(choices,value,()=>{requestKey=crypto.randomUUID();time=value;choices.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));submit.disabled=false;});b.setAttribute('aria-pressed',String(time===value));b.disabled=slot.getTime()<Date.now()+1800000;}
  const notice=el('p','보험소가 담당자와 일정을 확인한 후 확정해요.',form);notice.setAttribute('role','status');
  const submit=button(form,'이 시간으로 신청',async()=>{if(busy||!time)return;busy=true;submit.disabled=true;notice.textContent='예약을 전달하고 있어요.';try{const when=new Date(date+'T'+time+':00+09:00').toISOString();await command('request',{office_assignment:true,request_key:requestKey,purpose,region,method,preferred_at:when});form.replaceChildren();icon(form,'check','success-icon');el('h2','소중한 요청이 전달됐어요.',form);el('p',region+' · '+kst(when),form);el('p','담당자 배정과 확인 상태는 내 예약에서 볼 수 있어요.',form);button(form,'예약 확인',()=>document.getElementById('requestList').scrollIntoView({behavior:'smooth',block:'start'}),'primary');message('');await refresh();}catch(error){notice.textContent=error.message==='request_limit'?'진행 중인 예약이 5건 있어요. 내 예약을 먼저 확인해 주세요.':error.message==='invalid_slot'?'시간이 지나갔어요. 다른 시간을 선택해 주세요.':'요청을 전달하지 못했어요. 잠시 후 다시 시도해 주세요.';submit.disabled=false;}finally{busy=false;}},'primary');submit.disabled=!time;
  button(form,'날짜 변경',()=>{step=1;render();},'text-button');
 }render();
}
export function renderTimeline(card,row){const timeline=el('ol',undefined,card);timeline.className='booking-timeline';timeline.setAttribute('aria-label','예약 진행 상태');let current=['completed'].includes(row.state)?3:['confirmed','scheduled','awaiting_completion'].includes(row.state)?2:1;const labels=['요청 전달',row.planner_id?'전문가 확인':'담당자 배정','예약 확정','상담 완료'];for(const [index,label]of labels.entries()){const li=el('li',undefined,timeline);li.className=index<current?'done':index===current?'current':'';if(index===current)li.setAttribute('aria-current','step');const symbol=el('span',undefined,li);symbol.className='step-symbol';symbol.innerHTML=window.uiIcon?.(index<current?'check':['send','person','calendar','check'][index])||'';el('span',label,li);}if(['cancelled','no_show','dispute','unmatched'].includes(row.state))timeline.remove();}
