import {el,kst} from './consultation-ui.js';
const day=value=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(value);
const shortDate=value=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'short',day:'numeric',weekday:'short'}).format(value);
const purposeLabels={claim:'보험금 청구',coverage:'보장 확인',management:'내 보험 확인',new:'가입 상담',other:'기타 상담',corporate:'기업보험 상담'};
export function renderOfficeRequest({form,command,refresh,message,selectedOffice=null,selectedPlanner=null,availability=null}){
 const params=new URLSearchParams(location.search);let region=selectedOffice?.region||selectedPlanner?.region||params.get('region')||'',purpose=Object.hasOwn(purposeLabels,params.get('purpose'))?params.get('purpose'):'claim',date='',time='',step=region?1:0,busy=false;let requestKey=crypto.randomUUID();
 const chosenDate=params.get('date')||'',chosenTime=params.get('time')||'',chosenStamp=new Date(chosenDate+'T'+chosenTime+':00+09:00').getTime();
 if(region&&/^\d{4}-\d{2}-\d{2}$/.test(chosenDate)&&/^(09|1[0-7]):(00|30)$|^18:00$/.test(chosenTime)&&chosenStamp>=Date.now()+1800000&&chosenStamp<=Date.now()+90*86400000){date=chosenDate;time=chosenTime;step=2;}
 const method=['phone','nearby','scheduled'].includes(params.get('method'))?params.get('method'):'scheduled';
 form.classList.add('request-wizard');form.hidden=false;form.onsubmit=e=>e.preventDefault();
 function button(parent,label,fn,cls=''){const b=el('button',label,parent);b.type='button';b.className=cls;b.onclick=fn;return b;}
 function icon(parent,name,cls){const n=el('span',undefined,parent);n.className=cls||'';n.innerHTML=window.uiIcon?.(name)||'';return n;}
 function render(){form.replaceChildren();el('p',step===0?'지역 선택':step===1?'● ○ · 1 / 2':'● ● · 2 / 2',form).className='step-dots';
  if(region)el('p',region+' · '+purposeLabels[purpose]+(selectedOffice?' · '+selectedOffice.name:selectedPlanner?' · '+selectedPlanner.name:' · 보험소 배정'),form).className='wizard-context';
  if(step===0){el('h2','어디에서 도움받으실까요?',form);const label=el('label','상담 지역',form),regions=el('select',undefined,label);regions.name='region';regions.setAttribute('aria-label','상담 지역');el('option','지역을 선택하세요',regions).value='';for(const area of window.COVERAGE_AREAS||[]){const option=el('option',area.region+' '+area.name,regions);option.value=area.region+' '+area.name;}const next=button(form,'다음',()=>{if(regions.value){region=regions.value;step=1;render();}},'primary');next.disabled=true;regions.onchange=()=>next.disabled=!regions.value;return;}
  if(step===1){el('h2','어느 날이 편하세요?',form);el('p',selectedPlanner?selectedPlanner.name+' 전문가에게 요청해요.':'담당 전문가 배정은 보험소가 도와드려요.',form);const choices=el('div',undefined,form);choices.className='choice-grid';for(let i=0;i<7;i++){const d=new Date(Date.now()+i*86400000),v=day(d);button(choices,(i===0?'오늘 · ':i===1?'내일 · ':'')+shortDate(d),()=>{requestKey=crypto.randomUUID();date=v;time='';step=2;render();}).setAttribute('aria-pressed',String(date===v));}const more=el('details',undefined,form);el('summary','다른 날짜',more);const label=el('label','희망 날짜',more),input=el('input',undefined,label);input.type='date';input.min=day(new Date());input.max=day(new Date(Date.now()+90*86400000));const dateHint=el('p','',more);dateHint.setAttribute('role','alert');input.onchange=()=>{if(input.checkValidity()&&input.value){requestKey=crypto.randomUUID();date=input.value;time='';step=2;render();}else{dateHint.textContent='오늘부터 90일 이내의 날짜를 선택해 주세요.';input.setAttribute('aria-invalid','true');input.focus();}};button(form,'지역 변경',()=>{step=0;render();},'text-button');return;}
  el('h2','몇 시가 편하세요?',form);el('p',shortDate(new Date(date+'T12:00:00+09:00')),form);const choices=el('div',undefined,form);choices.className='choice-grid';for(let minute=540;minute<=1080;minute+=(selectedOffice?60:30)){const value=String(Math.floor(minute/60)).padStart(2,'0')+':'+String(minute%60).padStart(2,'0');const slot=new Date(date+'T'+value+':00+09:00');const b=button(choices,value,()=>{requestKey=crypto.randomUUID();time=value;choices.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));submit.disabled=false;});b.setAttribute('aria-pressed',String(time===value));b.disabled=slot.getTime()<Date.now()+1800000;}
  const notice=el('p','담당자 수락 후 서로 연락하고 일정을 확정해요.',form);notice.setAttribute('role','status');
  if(availability&&(selectedOffice||selectedPlanner)){const requestedDay=date;choices.querySelectorAll('button').forEach(b=>b.disabled=true);notice.textContent='가능한 시간을 확인하고 있어요.';queueMicrotask(async()=>{try{const slots=await availability(selectedOffice?.id||null,selectedPlanner?.id||null,requestedDay,method);if(date!==requestedDay||!choices.isConnected)return;choices.querySelectorAll('button').forEach(b=>b.disabled=!slots.includes(b.textContent));if(!slots.includes(time)){time='';submit.disabled=true;}notice.textContent=slots.length?'가능한 시간만 표시됩니다.':'이 날짜에는 가능한 시간이 없습니다.';}catch{if(choices.isConnected){time='';submit.disabled=true;notice.textContent='가능한 시간을 확인하지 못했습니다. 날짜를 다시 선택해 주세요.';}}});}
  const submit=button(form,'이 시간으로 신청',async()=>{if(busy||!time)return;const stamp=new Date(date+'T'+time+':00+09:00').getTime();if(!Number.isFinite(stamp)||stamp<Date.now()+1800000||stamp>Date.now()+90*86400000){notice.textContent='예약시간을 다시 선택해 주세요.';time='';submit.disabled=true;return;}busy=true;submit.disabled=true;notice.textContent='예약을 전달하고 있어요.';try{const when=new Date(date+'T'+time+':00+09:00').toISOString();await command('request',{office_assignment:!selectedPlanner,...(selectedOffice?{office_id:selectedOffice.id}:{}),...(selectedPlanner?{planner_id:selectedPlanner.id}:{}),request_key:requestKey,purpose,region,method,preferred_at:when});form.replaceChildren();icon(form,'check','success-icon');el('h2','상담 요청이 접수되었습니다.',form);el('p',region+' · '+kst(when),form);el('p','담당자 수락 후 연락처 공개에 동의하고, 전화·연락을 마친 뒤 확정해 주세요. 내 예약과 알림에서 확인할 수 있어요.',form);button(form,'예약 확인',()=>document.getElementById('requestList').scrollIntoView({behavior:'smooth',block:'start'}),'primary');message('');await refresh();}catch(error){notice.textContent=error.message==='reception_paused'?'새 상담 접수를 쉬고 있어요. 주변 전문가를 다시 확인해 주세요.':error.message==='request_limit'?'진행 중인 예약이 5건 있어요. 내 예약을 먼저 확인해 주세요.':['invalid_slot','slot_unavailable'].includes(error.message)?'이 시간은 이용할 수 없습니다. 다른 시간을 선택해 주세요.':error.message==='membership_required'?'회원가입을 완료한 후 이용할 수 있습니다.':error.message==='office_not_active'?'아직 방문예약을 준비 중인 보험소입니다.':error.message==='visit_not_available'?'전문가 방문 요청은 준비 중입니다. 전화상담이나 상담 예약을 선택해 주세요.':error.code==='23505'?'이미 예약된 시간입니다. 다른 시간을 선택해 주세요.':'네트워크 연결을 확인한 뒤 다시 시도해 주세요.';submit.disabled=false;}finally{busy=false;}},'primary');submit.disabled=!time;
  button(form,'날짜 변경',()=>{step=1;render();},'text-button');
 }render();
}
export function renderTimeline(card,row){const timeline=el('ol',undefined,card);timeline.className='booking-timeline';timeline.setAttribute('aria-label','예약 진행 상태');let current=['completed'].includes(row.state)?3:['confirmed','scheduled','awaiting_completion'].includes(row.state)?2:1;const labels=['요청 전달',row.planner_id?(row.planner_ok?'연락·일정 확인':'전문가 확인'):'담당자 배정','예약 확정','상담 완료'];for(const [index,label]of labels.entries()){const li=el('li',undefined,timeline);li.className=index<current?'done':index===current?'current':'';if(index===current)li.setAttribute('aria-current','step');const symbol=el('span',undefined,li);symbol.className='step-symbol';symbol.innerHTML=window.uiIcon?.(index<current?'check':['send','person','calendar','check'][index])||'';el('span',label,li);}if(['cancelled','no_show','dispute','unmatched'].includes(row.state))timeline.remove();}
