import {memberService,requireActiveMember} from './member-access.js';
export const ENABLE_LIVE_LOCATION=false;
export const ENABLE_BACKGROUND_LOCATION=false;
const labels={REQUESTED:'요청 전달',ACCEPTED:'전문가 확인',PREPARING:'출발 준비',DEPARTED:'상담 장소로 출발',EN_ROUTE:'이동 중',ARRIVED:'도착',COMPLETED:'상담 완료',CANCELLED:'취소',EXPIRED:'요청 종료'};
const purposes={death:'가족 사망 관련 도움',illness:'진단 후 보험 확인',medical:'입원·수술 보험 확인',accident:'사고 후 보험 확인',claim:'보험금 청구',coverage:'내 보험 확인'};
const errorCopy={policies_not_approved:"약관 검토가 끝난 뒤 요청을 열 예정입니다.",beta_invitation_required:"초대된 베타 참여자만 요청할 수 있어요.",phone_verification_required:"휴대전화 인증이 필요합니다. 인증 연결을 준비 중입니다.",expert_verification_required:'휴대전화·전문가 등록 확인과 활동지역 설정이 필요합니다.',no_available_expert:'지금 가능한 전문가가 없습니다. 예약 상담을 이용해 주세요.',request_limit:'진행 중인 요청을 확인하거나 잠시 후 다시 시도해 주세요.',offer_unavailable:'이미 다른 전문가가 수락했거나 종료된 요청입니다.',expert_busy:'현재 진행 중인 상담이 있습니다.',live_location_disabled:'위치공유는 아직 준비 중입니다.',invalid_location:'정확한 현재 위치를 확인하지 못했어요. 다시 시도해 주세요.'};
function el(tag,text,root,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;if(root)root.append(n);return n;}
function button(text,root,fn){const b=el('button',text,root,'btn');b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){status(root,errorCopy[e.message]||'연결 또는 입력을 확인한 뒤 다시 시도해 주세요.');}finally{b.disabled=false;}};return b;}
function status(root,text){let n=root.querySelector('.urgent-status');if(!n){n=el('p','',root,'urgent-status');n.setAttribute('role','status');}n.textContent=text;}
function field(root,title,type='text'){const l=el('label',title,root,'field'),n=el(type==='textarea'?'textarea':'input','',l);if(type!=='textarea')n.type=type;return n;}
async function rpc(client,operation,payload={}){const r=await client.rpc('urgent_command',{operation,payload});if(r.error)throw Error(r.error.message);return r.data;}
async function areas(client){const r=await client.rpc('service_area_catalog');if(r.error)throw Error('areas_unavailable');return r.data;}
function locationOnce(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('invalid_location'));navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),()=>reject(Error('invalid_location')),{enableHighAccuracy:true,timeout:20000,maximumAge:0});});}
function nearest(list,p){return [...list].sort((a,b)=>((a.latitude-p.latitude)**2+(a.longitude-p.longitude)**2)-((b.latitude-p.latitude)**2+(b.longitude-p.longitude)**2))[0];}
function miniMap(root,area){const target=el('div','',root,'service-area-map');target.setAttribute('aria-label',area.name+' 활동권역 지도');if(!window.L){el('p',area.region+' '+area.name,target);return;}const m=window.L.map(target,{scrollWheelZoom:false}).setView([area.latitude,area.longitude],12);window.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(m);window.L.circle([area.latitude,area.longitude],{radius:1800,color:getComputedStyle(document.documentElement).getPropertyValue('--brand').trim()||getComputedStyle(document.documentElement).getPropertyValue('--blue').trim(),fillOpacity:.1}).addTo(m);setTimeout(()=>{if(target.isConnected)m.invalidateSize();},0);}
function picker(root,list,onSelect){const search=field(root,'지역 검색');search.placeholder='분당, 판교, 수지…';const results=el('div','',root,'area-options');const render=()=>{results.replaceChildren();const matches=list.filter(a=>(a.region+' '+a.name).includes(search.value.trim())).slice(0,12);for(const a of matches)button(a.region+' '+a.name,results,()=>onSelect(a));if(!matches.length)el('p','등록된 활동지역이 없어요. 다른 지역명을 입력해 주세요.',results);};search.oninput=render;render();}
export async function renderServiceArea(client,root){
 const card=el('section','',root,'card urgent-panel');let list,settings;try{list=await areas(client);settings=await rpc(client,'settings');}catch{el('p','활동지역 기능을 연결하고 있습니다.',card);return;}
 const summary=()=>{card.replaceChildren();el('h2','주활동지역',card);const s=settings.areas;el('strong',list.find(a=>a.id===s?.primary_area)?.name||'아직 설정하지 않았어요',card);el('p',s?.secondary_areas?.length?'추가 활동지역 · '+s.secondary_areas.map(id=>list.find(a=>a.id===id)?.name||id).join(' · '):'추가 활동지역은 최대 2곳까지',card);button(s?'변경':'활동지역 설정',card,()=>flow());};
 const flow=()=>{let primary=list.find(a=>a.id===settings.areas?.primary_area),secondary=[...(settings.areas?.secondary_areas||[])];const step1=()=>{card.replaceChildren();el('p','1 / 3',card);el('h2','주로 어디에서 활동하세요?',card);button('현재 위치로 찾기',card,async()=>{status(card,'기기에서 지역을 찾습니다. 현재 위치는 저장하지 않습니다.');primary=nearest(list,await locationOnce());step2();});picker(card,list,a=>{primary=a;step2();});button('취소',card,summary);};const step2=()=>{card.replaceChildren();el('p','2 / 3',card);el('h2',primary.name,card);el('p','공개 활동권역입니다. 현재 위치를 공개하지 않아요.',card);miniMap(card,primary);button('이 지역으로 설정',card,()=>{secondary=secondary.filter(id=>id!==primary.id);step3();});button('다시 찾기',card,step1);};const step3=()=>{card.replaceChildren();el('p','3 / 3',card);el('h2','함께 활동할 지역이 있나요?',card);const chips=el('div','',card,'area-options');const renderChips=()=>{chips.replaceChildren();secondary.forEach(id=>button((list.find(a=>a.id===id)?.name||id)+' ×',chips,()=>{secondary=secondary.filter(x=>x!==id);renderChips();}));};renderChips();picker(card,list.filter(a=>a.id!==primary.id),a=>{if(secondary.includes(a.id))return;if(secondary.length>=2){status(card,'추가 지역은 2곳까지 선택할 수 있어요.');return;}secondary.push(a.id);renderChips();});button('완료',card,async()=>{await rpc(client,'save_areas',{primary:primary.id,secondary});settings=await rpc(client,'settings');summary();});button('이전',card,step2);};step1();};summary();
}
export async function renderInstant(client,root){const card=el('section','',root,'card urgent-panel');let timer;const load=async()=>{const data=await rpc(client,'settings');card.replaceChildren();el('h2','지금 바로 상담 가능',card);const active=data.instant?.enabled;el('p',active?'ON · '+new Date(data.instant.expires_at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})+'까지':'OFF · 필요할 때만 켜세요',card);if(!data.eligible)el('p','휴대전화·전문가·노출 승인 확인 후 사용할 수 있어요.',card);const toggle=button(active?'지금 가능 끄기':'지금 가능 켜기',card,async()=>{if(active){await rpc(client,'stop');await load();return;}const dialog=el('dialog','',document.body,'card instant-dialog');el('h2','현재 위치 주변의 급한 상담 요청을 받을까요?',dialog);const duration=el('div','',dialog,'area-options');let minutes='30';for(const [value,title] of [['30','30분'],['60','1시간'],['18','오늘 18시까지']]){const b=button(title,duration,()=>{minutes=value;for(const c of duration.children)c.setAttribute('aria-pressed',String(c===b));});b.setAttribute('aria-pressed',String(value===minutes));}const consent=field(dialog,'급한 상담 매칭을 위해 현재 위치를 한 번 확인·보관하는 데 동의합니다.','checkbox');el('p','고객에게 정확한 위치는 공개하지 않아요. 끄거나 시간이 끝나면 좌표를 삭제합니다.',dialog);button('시작하기',dialog,async()=>{if(!consent.checked){status(dialog,'위치 사용 동의를 확인해 주세요.');return;}const point=await locationOnce();await rpc(client,'start',{duration:minutes,consent:true,...point});dialog.close();dialog.remove();await load();});button('닫기',dialog,()=>{dialog.close();dialog.remove();});dialog.addEventListener('cancel',()=>dialog.remove());dialog.showModal();});toggle.disabled=!active&&!data.eligible;clearTimeout(timer);if(active)timer=setTimeout(()=>{if(card.isConnected)load().catch(()=>{});},Math.min(2147483647,Math.max(1000,new Date(data.instant.expires_at)-Date.now()+1000)));};try{await load();}catch{el('p','지금 가능 기능을 연결하고 있습니다.',card);} }
export async function renderUrgentWorkspace(client,root){const panel=el('section','',root,'card urgent-panel');el('h2','지금 요청',panel);const body=el('div','',panel);let busy=false;const load=async()=>{if(busy)return;busy=true;try{const rows=await rpc(client,'workspace');body.replaceChildren();if(!rows.length)el('p','진행 중인 긴급 요청이 없습니다.',body);for(const r of rows){const c=el('article','',body,'card urgent-request');el('h3',purposes[r.purpose]||r.purpose,c);el('p',r.region+' · '+labels[r.state],c);if(r.expertName)el('strong',r.expertName+' 전문가',c);if(r.distanceKm!=null)el('p','약 '+r.distanceKm+'km · 방문 상담',c);const timeline=el('ol','',c,'urgent-timeline');for(const t of r.timeline)el('li',(t.state==='REQUESTED'?'✓ ':t.state===r.state?'● ':'✓ ')+(labels[t.state]||t.state),timeline);if(r.details){el('p','만날 장소 · '+r.details.place,c);const phone=el('a',r.details.phone,c);phone.href='tel:'+r.details.phone;if(r.details.note)el('p',r.details.note,c);}else el('p','수락한 한 명에게만 연락처와 만날 장소를 공개합니다.',c);
 const act=(title,operation,payload={})=>button(title,c,async()=>{await rpc(client,operation,{id:r.id,...payload});await load();});
 if(!r.mine&&!r.assigned&&r.state==='REQUESTED'){act('수락','accept');act('패스','pass');}
 if(r.assigned){if(['ACCEPTED','PREPARING'].includes(r.state)){if(r.state==='ACCEPTED')act('출발 준비','trip',{state:'PREPARING'});button('출발하기',c,()=>{const d=el('dialog','',document.body,'card instant-dialog');el('h2','고객에게 이동상태를 알릴까요?',d);el('p','정확한 위치 공유는 준비 중입니다.',d);const share=button('위치공유 시작 · 준비 중',d,()=>{});share.disabled=true;button('상태만 알리기',d,async()=>{await rpc(client,'trip',{id:r.id,state:'DEPARTED',shareLocation:false});d.close();d.remove();await load();});button('닫기',d,()=>{d.close();d.remove();});d.showModal();});}if(r.state==='DEPARTED')act('이동 중','trip',{state:'EN_ROUTE'});if(['DEPARTED','EN_ROUTE'].includes(r.state))act('도착','trip',{state:'ARRIVED'});if(r.state==='ARRIVED')act('상담완료','trip',{state:'COMPLETED'});}
 if((r.mine||r.assigned)&&!['COMPLETED','CANCELLED','EXPIRED'].includes(r.state))act('요청 취소','cancel');
 }}finally{busy=false;}};button('새로고침',panel,load);try{await load();}catch{status(panel,'긴급 요청 기능을 연결하고 있습니다.');}const timer=setInterval(()=>{if(!panel.isConnected){clearInterval(timer);return;}if(document.visibilityState==='visible'&&!document.querySelector('dialog[open]'))load().catch(()=>{});},15000);}
async function customerPage(client,root){const list=await areas(client);el('h1','지금 도움 요청',root);el('p','가능한 전문가가 요청을 확인한 후 연결됩니다.',root);const browse=el('section','',root,'card urgent-panel');const tracking=el('div','',root);let chosen;const region=new URLSearchParams(location.search).get('region');const show=async a=>{chosen=a;browse.replaceChildren();el('h2',a.name+' · 지금 가능',browse);el('p',a.expertCount>=10?a.name+' 지역 서비스 오픈':'서비스 준비 중 · 등록 전문가 '+a.expertCount+'명',browse);miniMap(browse,a);const candidates=await rpc(client,'catalog',{area:a.id});if(!candidates.length){el('p','지금 가능한 전문가가 없습니다.',browse);const link=el('a','시간을 정해 상담 예약',browse,'btn');link.href='/requests.html?region='+encodeURIComponent(a.region+' '+a.name);}for(const p of candidates){const row=el('article','',browse,'card');el('h3',p.name+' 전문가',row);el('p','● 지금 출발 가능',row);el('p','선택 지역 중심에서 약 '+p.distanceKm+'km · 도착시간은 수락 후 안내',row);el('p','주활동지역 · '+p.primaryServiceArea,row);}
 if(candidates.length)button('지금 도움 요청',browse,()=>requestFlow(a));button('지역 변경',browse,selectArea);};const selectArea=()=>{browse.replaceChildren();el('h2','어디에서 도움이 필요하세요?',browse);button('현재 위치로 지역 찾기',browse,async()=>show(nearest(list,await locationOnce())));picker(browse,list,show);};
 function requestFlow(area){const requestKey=crypto.randomUUID(),values={area:area.id,purpose:new URLSearchParams(location.search).get('situation')||'claim',place:'',phone:'',note:''};if(!purposes[values.purpose])values.purpose='claim';const step1=()=>{browse.replaceChildren();el('p','1 / 3',browse);el('h2','어떤 도움이 필요하세요?',browse);for(const [id,title] of Object.entries(purposes))button(title,browse,()=>{values.purpose=id;step2();});button('취소',browse,()=>show(area));};const step2=()=>{browse.replaceChildren();el('p','2 / 3',browse);el('h2','어디에서 만나실까요?',browse);el('p',area.region+' '+area.name,browse);const place=field(browse,'만날 장소');place.value=values.place;place.maxLength=160;place.placeholder='예: 분당구청 정문';const remember=()=>values.place=place.value.trim();place.oninput=remember;button('현재 위치 사용',browse,async()=>{status(browse,'요청을 전달할 때 매칭 목적으로 위치를 사용합니다.');Object.assign(values,await locationOnce());status(browse,'현재 위치를 확인했어요. 만날 장소도 적어 주세요.');});button('다음',browse,()=>{remember();if(values.place.length<2){status(browse,'만날 장소를 적어 주세요.');place.focus();return;}step3();});button('이전',browse,step1);};const step3=()=>{browse.replaceChildren();el('p','3 / 3',browse);el('h2','이 요청을 전달할까요?',browse);el('p',purposes[values.purpose]+' · '+values.place,browse);const phone=field(browse,'연락 가능한 휴대전화','tel');phone.value=values.phone;phone.autocomplete='tel';const note=field(browse,'간단한 요청내용 (선택)','textarea');note.value=values.note;note.maxLength=300;el('p','주민번호·진단서 등 민감한 정보는 적지 마세요.',browse);const consent=field(browse,'매칭을 위한 위치 이용과 수락한 전문가 한 명에게 연락처·만날 장소·요청내용 제공에 동의합니다.','checkbox');button('요청하기',browse,async()=>{values.phone=phone.value.replace(/\D/g,'');values.note=note.value.trim();if(!/^01\d{8,9}$/.test(values.phone)){status(browse,'연락 가능한 휴대전화를 확인해 주세요.');phone.focus();return;}if(!consent.checked){status(browse,'요청 전달 동의를 확인해 주세요.');return;}await rpc(client,'request',{...values,consent:true,request_key:requestKey});browse.replaceChildren();el('h2','고객님의 요청이 전달되었습니다.',browse);el('p','아래에서 진행 상태를 확인하세요.',browse);tracking.replaceChildren();await renderUrgentWorkspace(client,tracking);});button('이전',browse,()=>{values.phone=phone.value;values.note=note.value;step2();});};step1();}
 const initial=list.find(a=>region&&(a.id===region||region.includes(a.name)));if(initial)await show(initial);else selectArea();await renderUrgentWorkspace(client,tracking);
}
const root=document.querySelector('[data-urgent-page]');if(root)(async()=>{if(!await requireActiveMember({next:location.pathname+location.search}))return;const {client,config}=await memberService();if(config.closedBeta!==undefined){const {data,error}=await client.rpc('release_status');if(error)throw error;if(!data.policiesApproved||!data.betaAllowed||!data.phoneVerified){el('h2',!data.policiesApproved?'약관 검토 후 긴급 상담을 열 예정이에요.':!data.betaAllowed?'초대된 베타 참여자만 요청할 수 있어요.':'휴대전화 확인이 필요해요.',root);const a=el('a',data.policiesApproved&&data.betaAllowed?'휴대전화 확인':'지도 둘러보기',root,'btn');a.href=data.policiesApproved&&data.betaAllowed?'/phone-verification.html?next='+encodeURIComponent(location.pathname+location.search):'/map.html';await renderUrgentWorkspace(client,root);return;}}await customerPage(client,root);})().catch(()=>status(root,'긴급 상담 기능을 준비하고 있습니다. 기존 예약 상담을 이용해 주세요.'));
