export {renderInstant,renderUrgentWorkspace} from './expert-visits.js';
import {memberService,requireActiveMember} from './member-access.js';
export const ENABLE_LIVE_LOCATION=false;
export const ENABLE_BACKGROUND_LOCATION=false;
const labels={REQUESTED:'요청 전달',ACCEPTED:'전문가 확인',PREPARING:'출발 준비',DEPARTED:'상담 장소로 출발',EN_ROUTE:'이동 중',ARRIVED:'도착',COMPLETED:'상담 완료',CANCELLED:'취소',EXPIRED:'요청 종료'};
export const purposes={death:'가족 사망 관련 도움',illness:'진단 후 보험 확인',medical:'입원·수술 보험 확인',accident:'사고 후 보험 확인',claim:'보험금 청구',coverage:'내 보험 확인',other:'기타 도움'};
const errorCopy={policies_not_approved:"현재 긴급 상담 접수를 준비하고 있습니다. 문의하기에서 이용 문의를 남겨 주세요.",beta_invitation_required:"초대된 베타 참여자만 요청할 수 있어요.",phone_verification_required:"휴대전화 인증이 필요합니다. 인증 연결을 준비 중입니다.",expert_verification_required:'휴대전화·전문가 등록 확인과 활동지역 설정이 필요합니다.',no_available_expert:'지금 가능한 전문가가 없습니다. 예약 상담을 이용해 주세요.',request_limit:'진행 중인 요청을 확인하거나 잠시 후 다시 시도해 주세요.',offer_unavailable:'이미 다른 전문가가 수락했거나 종료된 요청입니다.',expert_busy:'현재 진행 중인 상담이 있습니다.',live_location_disabled:'위치공유는 아직 준비 중입니다.',invalid_location:'정확한 현재 위치를 확인하지 못했어요. 다시 시도해 주세요.'};
function el(tag,text,root,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;if(root)root.append(n);return n;}
function button(text,root,fn){const b=el('button',text,root,'btn');b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){status(root,errorCopy[e.message]||'연결 또는 입력을 확인한 뒤 다시 시도해 주세요.');}finally{b.disabled=false;}};return b;}
function status(root,text){let n=root.querySelector('.urgent-status');if(!n){n=el('p','',root,'urgent-status');n.setAttribute('role','status');}n.textContent=text;}
function field(root,title,type='text'){const l=el('label',title,root,'field'),n=el(type==='textarea'?'textarea':'input','',l);if(type!=='textarea')n.type=type;return n;}
async function rpc(client,operation,payload={}){const r=await client.rpc('urgent_command',{operation,payload});if(r.error)throw Error(r.error.message);return r.data;}
async function areas(client){const r=await client.rpc('service_area_catalog');if(r.error)throw Error('areas_unavailable');return r.data;}
function locationOnce(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('invalid_location'));navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),()=>reject(Error('invalid_location')),{enableHighAccuracy:true,timeout:20000,maximumAge:0});});}
function nearest(list,p){return [...list].sort((a,b)=>((a.latitude-p.latitude)**2+(a.longitude-p.longitude)**2)-((b.latitude-p.latitude)**2+(b.longitude-p.longitude)**2))[0];}
function miniMap(root,area){const target=el('div','',root,'service-area-map');target.setAttribute('aria-label',area.name+' 활동권역 지도');if(!window.L){el('p',area.region+' '+area.name,target);return;}const m=window.L.map(target,{scrollWheelZoom:false}).setView([area.latitude,area.longitude],12);window.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(m);window.L.circle([area.latitude,area.longitude],{radius:1800,color:getComputedStyle(document.documentElement).getPropertyValue('--brand').trim()||getComputedStyle(document.documentElement).getPropertyValue('--blue').trim(),fillOpacity:.1}).addTo(m);setTimeout(()=>{if(target.isConnected)m.invalidateSize();},0);}
function picker(root,list,onSelect){const search=field(root,'지역 검색');search.placeholder='분당, 판교, 수지…';const results=el('div','',root,'area-options');const render=()=>{results.replaceChildren();const matches=list.filter(a=>(a.region+' '+a.name).includes(search.value.trim())).slice(0,12);for(const a of matches)button(a.region+' '+a.name,results,()=>onSelect(a));if(!matches.length)el('p','등록된 활동지역이 없어요. 다른 지역명을 입력해 주세요.',results);};search.oninput=render;render();}
export async function renderServiceArea(client,root){
 const card=el('section','',root,'card urgent-panel');let list,settings;try{list=await areas(client);settings=await rpc(client,'settings');}catch{el('p','활동지역 기능을 연결하고 있습니다.',card);return;}
 const summary=()=>{card.replaceChildren();el('h2','주활동지역',card);const s=settings.areas;el('strong',list.find(a=>a.id===s?.primary_area)?.name||'아직 설정하지 않았어요',card);el('p',s?.secondary_areas?.length?'추가 활동지역 · '+s.secondary_areas.map(id=>list.find(a=>a.id===id)?.name||id).join(' · '):'추가 활동지역은 최대 2곳까지',card);button(s?'변경':'활동지역 설정',card,()=>flow());};
 const flow=()=>{let primary=list.find(a=>a.id===settings.areas?.primary_area),secondary=[...(settings.areas?.secondary_areas||[])];const step1=()=>{card.replaceChildren();el('p','1 / 3',card);el('h2','주로 어디에서 활동하세요?',card);button('현재 위치로 찾기',card,async()=>{status(card,'기기에서 지역을 찾습니다. 현재 위치는 저장하지 않습니다.');primary=nearest(list,await locationOnce());step2();});picker(card,list,a=>{primary=a;step2();});button('취소',card,summary);};const step2=()=>{card.replaceChildren();el('p','2 / 3',card);el('h2',primary.name,card);el('p','공개 활동권역입니다. 현재 위치를 공개하지 않아요.',card);miniMap(card,primary);button('이 지역으로 설정',card,()=>{secondary=secondary.filter(id=>id!==primary.id);step3();});button('다시 찾기',card,step1);};const step3=()=>{card.replaceChildren();el('p','3 / 3',card);el('h2','함께 활동할 지역이 있나요?',card);const chips=el('div','',card,'area-options');const renderChips=()=>{chips.replaceChildren();secondary.forEach(id=>button((list.find(a=>a.id===id)?.name||id)+' ×',chips,()=>{secondary=secondary.filter(x=>x!==id);renderChips();}));};renderChips();picker(card,list.filter(a=>a.id!==primary.id),a=>{if(secondary.includes(a.id))return;if(secondary.length>=2){status(card,'추가 지역은 2곳까지 선택할 수 있어요.');return;}secondary.push(a.id);renderChips();});button('완료',card,async()=>{await rpc(client,'save_areas',{primary:primary.id,secondary});settings=await rpc(client,'settings');summary();});button('이전',card,step2);};step1();};summary();
}
